### ISSUE TITLE
Feature Request: Set environment variable in meson.build

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#541] opened 2016-05-20 06:13 UTC
There are lots of reasons that setting environment variables in meson.build might be useful. I would like to see this feature added to meson.

Not a valid reason to add the feature, but it is supported by [cmake](https://cmake.org/cmake/help/v3.0/command/set.html).

**Comment by jpakkane** [comment] 2016-05-23 16:41
The problem here is doing that reliably over all backends. For example Ninja does not permit setting envvars for individual command invocations. I don't know if you can do this at all on XCode and VS. The only option would be to wrap each executable invocation with a wrapper script to set those values and that is massively slow, especially on Windows.

**Comment by tobimensch** [comment] 2016-05-26 01:18
@jpakkane:

I don't think things should be overcomplicated. Did rhd even ask for the ability to set env vars for individual commands? I think the feature request is just for setting env vars that are the same for all commands. That shouldn't be hard to implement on any platform.

**Comment by nirbheek** [comment] 2016-05-26 01:21
The problem is that Ninja doesn't support setting environment variables in a cross-platform way at all. Not per command and not globally. All build-time commands are run through Ninja.

**Comment by tobimensch** [comment] 2016-05-26 01:25
Maybe this should be a feature request for ninja then?

Theoretically it would be easy to create a wrapper around ninja that would do that, but
then the user would have to call that wrapper instead or set an alias for ninja, which
would lead to a lot of confusion.

**Comment by nirbheek** [comment] 2016-05-26 01:33
Upstream Ninja already discussed this and rejected for reasons that I don't understand. I've already asked them about it: https://github.com/ninja-build/ninja/issues/1002#issuecomment-221169296

**Comment by nirbheek** [comment] 2016-08-01 05:25
In retrospect, this makes sense only for targets that run some generated or custom/external command. We already have open issues for `run_target`, `custom_target`, and `gnome.generate_gir`, so we should do this on a as-needed basis instead of adding something that the entire build process inherits which can have unintended consequences (and is impossible to support in any of the backends anyway).

(closing bug; please reopen if you disagree, @jpakkane)

**Closed by nirbheek** 2016-08-01 05:25 UTC

**Comment by shmerl** [comment] 2019-01-24 21:31
So what's the current recommended method to replace Cmake's:

```
set(ENV{foo} "bar")
```
In Meson?

**Comment by jpakkane** [comment] 2019-01-24 21:35
It depends. What is the exact thing you want to accomplish by setting that variable?

**Comment by shmerl** [comment] 2019-01-24 21:38
In my case it's some custom pkgconfig location. I.e.:

```
set(ENV{PKG_CONFIG_PATH} "/something/pkgconfig:/usr/local/lib64/pkgconfig:$ENV{PKG_CONFIG_PATH}")
```

**Comment by jpakkane** [comment] 2019-01-24 21:42
Yes. Found dependencies are cached over invocations so it should work.

In general setting things about "the system" from within build files is a bit suspicious, because then your build files become dependent on the system you run them on. People on other machines may need to edit the build files to get things to work for them.

**Comment by shmerl** [comment] 2019-01-24 21:44
Depends on the use case. If  you are making a generic build, then yeah. But for a reproducible build with fixed environment, that's a normal thing.

**Comment by marc-h38** [comment] 2020-01-17 21:32
> In general setting things about "the system" from within build files is a bit suspicious, because then your build files become dependent on the system you run them on.

Only if these "things" are absolute paths hardcoded in the build files. Not if they're relative paths or absolute paths but computed at setup time (and yes the latter does break reproducibility, but that's not a meson issue)

I'm not a fan of using environment variables as parameters, I find them too "implicit". However sometimes it's the only way Kconfig for instance requires $srctree for out of source  builds.

>We already have open issues for run_target, custom_target, and gnome.generate_gir, so we should do this on a as-needed basis instead of adding something that the entire build process inherits which can have unintended consequences (and is impossible to support in any of the backends anyway).

Thanks! envvars don't have to be "global" either. Adding some (missing?) links:

Feature request: provide a way to specify environment variables for custom targets #266
Add env: argument to custom_target, run_target, run_command #2723
run_command: add env kwarg #4804

**Comment by lb90** [comment] 2020-09-18 14:24
This would be needed for static builds of GLib on Windows.

to spawn processes on Windows, GLib uses a small exe wrapper called **g-spawn-win32-helper.exe**. It's used to overcome some limitations of the OS. Now, when GLib is built as a static library, the developer must place g-spawn-win32-helper.exe in the same directory of the EXE (or DLL) where GLib is embedded, so the helper can be found using GetModuleFileNameW().

During a Meson build, If not using a flat layout, g-spawn-win32-helper.exe should be copied in almost every subdirectory of the build dir. All subdirectories that contain executable()s should have this helper. The helper is used extensively by built generators and tests.

Instead, if we could set an environment variable from meson.build, we could set G_SPAWN_WIN32_HELPER_DIR right after building g-spawn-win32-helper.exe, and every executable could find the built helper through that.

If there's a better way, please advice :)

**Comment by xclaesse** [comment] 2020-09-18 20:05
@lb90 is that helper only used at build time, or is it used at runtime too by g_subprocess? I can't find references to that in master, is it a new thing in in MR? Any reason that wrapper is not a python script?

**Comment by lb90** [comment] 2020-09-18 20:41
Hi! It's not used during the build process, it's used by GLib at runtime when using the g_spawn API. Here are some links:

* https://gitlab.gnome.org/GNOME/glib/-/blob/7b17c57a/glib/meson.build#L409
* https://gitlab.gnome.org/GNOME/glib/-/blob/master/glib/gspawn-win32-helper.c

**Comment by xclaesse** [comment] 2020-09-18 21:08
@lb90 Ok, so anyone who runs a glib program from the build directory will need that env, Thinking about gst-uninstalled.py here (from GStreamer project). This sounds similar to the idea I had there: https://github.com/mesonbuild/meson/pull/6229.

**Comment by lb90** [comment] 2020-09-18 21:25
Looks good, thanks! Will take a look at it.

**Comment by nirbheek** [comment] 2020-09-19 11:47
I think it should be called `meson run`, since `uninstalled` is not a verb.

**Comment by xclaesse** [comment] 2020-09-19 12:03
Yes it need to be renamed, gst-build renamed it too.
