### ISSUE TITLE
Support for Python 3.13

### ISSUE THREAD

**Issue by alkino** [mesonbuild/meson#12714] opened 2024-01-08 14:54 UTC
`meson` is not yet ready for Python 3.13.

The first reason I have found is that [importlib](https://docs.python.org/3.13/library/importlib.resources.html) has lost a lot of deprecated functions.

https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/python.py#L106 use `importlib.resources.path`. The documentation of [3.12](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.path) tells it can be replaced by:
```
importlib.resources.as_file(importlib.resources.file('mesonbuild.scripts').joinpath('python_info.py'))
```

The problem is that [as_file](https://docs.python.org/3.13/library/importlib.resources.html#importlib.resources.as_file) only appear in 3.9 and meson support python 3.7

What should be done?

**Comment by eli-schwartz** [comment] 2024-01-08 14:58
Duplicate of #12401

**Closed by eli-schwartz** 2024-01-08 14:58 UTC

**Comment by eli-schwartz** [comment] 2024-01-08 15:01
I have a small WIP to enhance the importlib.resources API for this which I need to get back to.

**Comment by alkino** [comment] 2024-01-08 15:03
You see me really sorry to have open this issue as a duplicate, I promise I searched for it.

Maybe pinning one of the issue with `Python 3.13` in the title could help.

I stay tuned for the fix, thanks for you great work.
