### ISSUE TITLE
Feature request: Add support for qt5_add_dbus_interface()

### ISSUE THREAD

**Issue by lgbaldoni** [mesonbuild/meson#7857] opened 2020-10-16 14:27 UTC
As it's done in cmake. I would do it myself, but my knowledge of python (and meson itself) is too rudimental.

I'm leaving this here so that someone who is also interested may take inspiration.

**Comment by dcbaker** [comment] 2020-10-16 16:11
Looks like this double opened.

Duplicate of: #7856

**Closed by dcbaker** 2020-10-16 16:11 UTC
