### ISSUE TITLE
gnome.compile_schemas does not work with generated schemas

### ISSUE THREAD

**Issue by chergert** [mesonbuild/meson#4265] opened 2018-09-26 01:13 UTC
Sometimes you need to generate your `*.gschema.xml` from options provided in `meson_options.txt`. This breaks the `gnome.compile_schemas()` command because it relies on the current source directory only.

Of course, to make this work otherwise would require copying the rest of the schemas to the build directory as well.

**Comment by TingPing** [comment] 2018-09-26 12:12
Duplicate of #2219

**Closed by TingPing** 2018-09-26 12:12 UTC
