### ISSUE TITLE
install is ignored in configure_file if install_dir is set

### ISSUE THREAD

**Issue by 3v1n0** [mesonbuild/meson#4160] opened 2018-09-12 03:53 UTC
If I have something like:

```
foreach pc: [PACKAGE_NAME, PACKAGE_NAME + '-uninstalled']
  configure_file(input: pc + '.pc.in',
    output: pc + '.pc',
    configuration: pc_conf,
    install: not pc.contains('-uninstalled'),
    install_dir: join_paths(libdir, 'pkgconfig'))
endforeach
```

The `-uninstalled` file is always installed, although `install` is set to false. The only way not to install it setting `install_dir` to `[]`.

In `executable` instead this works as expected, while setting an empty path doesn't work if install is true.

**Comment by nirbheek** [comment] 2018-09-12 07:05
Duplicate of https://github.com/mesonbuild/meson/issues/3983

**Closed by nirbheek** 2018-09-12 07:05 UTC

**Comment by xclaesse** [comment] 2018-11-08 03:01
Unrelated to your issue, but you could be interested by this PR https://github.com/mesonbuild/meson/pull/4436 to generate -uninstalled.pc files.

**Comment by 3v1n0** [comment] 2018-11-08 06:01
@xclaesse yeah, I was looking at it few minutes before you mentioned... Because yes I might need it.

Thanks :)
