### ISSUE TITLE
built-in options from native-file are ignored

### ISSUE THREAD

**Issue by SSE4** [mesonbuild/meson#7697] opened 2020-09-05 19:34 UTC
**Describe the bug**
according to the [meson documentation](https://mesonbuild.com/Machine-files.html#meson-builtin-options), native files may specify built-in options, such as `default_library`. however, it appears that meson ignores them.

**To Reproduce**
**meson.build**:
```
project('tutorial', 'cpp')
library('xx', 'xx.cpp')
```
**xx.cpp** might be an empty, it's not important:
```
```
**native.ini**:
```
[built-in options]
default_library = 'static'
```
running the following commands:
```
meson --native-file native.ini build .
meson compile -C build
```
results in:
```
[2/2] Linking target xx.dll
```
running the following commands instead:
```
meson --native-file native.ini -Ddefault_library=static build .
meson compile -C build
```
results in the correct output:
```
[2/2] Linking static target libxx.a
```
same result with the following command line:
```
meson -Ddefault_library=static build .
meson compile -C build
```
it means built-in options specified in native files have no effect.

**Expected behavior**
I'd expect `default_library` specified in native file to be respected by meson, thus given native file should produce static library.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
nope, plain build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10
* what Python version are you using e.g. 3.8.0
Python 3.8.1
* what `meson --version`
0.55.1
* what `ninja --version` if it's a Ninja build
1.8.2

**Comment by dcbaker** [comment] 2020-09-06 01:24
Duplicate of #7699

**Closed by dcbaker** 2020-09-06 01:24 UTC
