### ISSUE TITLE
Ninja no longer accepts dupbuild=err

### ISSUE THREAD

**Issue by gruenich** [mesonbuild/meson#13176] opened 2024-05-02 15:53 UTC
**Describe the bug**
With the release 1.12, Ninja no longer accepts dupbuild=err, see https://github.com/ninja-build/ninja/pull/2356
It gives a hard error.

**Comment by eli-schwartz** [comment] 2024-05-02 16:00
Duplicate of #13087

**Closed by eli-schwartz** 2024-05-02 16:00 UTC
