### ISSUE TITLE
[0.52.0] Failed test-suite 47 pkgconfig-gen

### ISSUE THREAD

**Issue by DimStar77** [mesonbuild/meson#6004] opened 2019-10-07 13:16 UTC
After updating Meson to 0.52.0 its own test suite fails:

```
[  240s] The Meson build system
[  240s] Version: 0.52.0
[  240s] Source dir: /home/abuild/rpmbuild/BUILD/meson-0.52.0/test cases/common/47 pkgconfig-gen/dependencies
[  240s] Build dir: /home/abuild/rpmbuild/BUILD/meson-0.52.0/tmp342kl9m2
[  240s] Build type: native build
[  240s] Project name: pkgconfig-gen-dependencies
[  240s] Project version: 1.0
[  240s] C compiler for the host machine: cc (gcc 9.2.1 "cc (SUSE Linux) 9.2.1 20190903 [gcc-9-branch revision 275330]")
[  240s] C linker for the host machine: GNU ld.bfd 2.32.0.20190909-7
[  240s] Host machine cpu family: x86_64
[  240s] Host machine cpu: x86_64
[  240s] Found pkg-config: /usr/bin/pkg-config (1.6.3)
[  240s] Run-time dependency libfoo found: YES 1.0
[  240s] Dependency libfoo found: YES (cached)
[  240s] Found CMake: /usr/bin/cmake (3.15.3)
[  240s] Run-time dependency notfound found: NO (tried pkgconfig and cmake)
[  240s] Run-time dependency threads found: YES 
[  240s] Build targets in project: 7
[  240s] Found ninja-1.9.0 at /usr/bin/ninja
[  240s] 
[  240s] /home/abuild/rpmbuild/BUILD/meson-0.52.0/tmp342kl9m2/meson-private/dependency-test.pc:7: warning: malformed version field with whitespace, trimming to [1.0]
[  240s] /home/abuild/rpmbuild/BUILD/meson-0.52.0/tmp342kl9m2/meson-private/libexposed.pc:7: warning: malformed version field with whitespace, trimming to [1.0]
[  240s] 
[  240s] libexposed
[  240s] libfoo >= 1.0
[  240s] libhello
[  240s] 
[  240s] libexposed
[  240s] libfoo >= 1.0
[  240s] libhello
[  240s] 
[  240s] -L/usr/lib -llibmain2 -llibinternal 
[  240s] 
[  240s] error: Bad exit status from /var/tmp/rpm-tmp.nzjD9p (%check)
```

**Comment by DimStar77** [comment] 2019-10-07 13:23
```
======================================================================
FAIL: test_pkgconfig_gen_deps (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 4655, in test_pkgconfig_gen_deps
    self.assertEqual(out, ['-llibmain2', '-llibinternal'])
AssertionError: Lists differ: ['-L/usr/lib', '-llibmain2', '-llibinternal'] != ['-llibmain2', '-llibinternal']

First differing element 0:
'-L/usr/lib'
'-llibmain2'

First list contains 1 additional elements.
First extra element 2:
'-llibinternal'

- ['-L/usr/lib', '-llibmain2', '-llibinternal']
?  --------------

+ ['-llibmain2', '-llibinternal']

```

**Comment by dcbaker** [comment] 2019-10-07 17:17
I think this may be a duplicate of #6003

**Comment by DimStar77** [comment] 2019-10-08 06:21
I backported the fix from https://github.com/mesonbuild/meson/commit/225c93c5c056f6afebb3b1d0635cc974f36b095b but that did not make the test suite pass

**Comment by dcbaker** [comment] 2019-10-08 16:40
Okay, I've added it to the list of issues to be resolved for 0.52.1

**Comment by jpakkane** [comment] 2019-11-04 20:02
This is weird. Does master fail for you too? Can you bisect the problematic commit?

**Comment by michaelbadcrumble** [comment] 2020-01-07 16:58
Is this being worked on?

**Comment by floppym** [comment] 2020-01-14 05:03
Please give #6458 a try.

**Comment by DimStar77** [comment] 2020-01-14 16:56
> Please give #6458 a try.

[  312s] Succeeded test: test cases/common/47 pkgconfig-gen

**Closed** 2020-01-22 22:10 UTC
Labels: bug, regression
