### ISSUE TITLE
--backend vs2015 always crashes on non-english Windows

### ISSUE THREAD

**Issue by msink** [mesonbuild/meson#1079] opened 2016-11-21 14:20 UTC
```
The Meson build system
Version: 0.36.0
Source dir: F:\avian\hello-c                                                                                        19:18Build dir: F:\avian\hello-c\build
Build type: native build
Project name: hello
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\mesonmain.py", line 283, in run
    app.generate()
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\mesonmain.py", line 163, in generate
    intr = interpreter.Interpreter(b, g)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1190, in __init__
    self.parse_project()
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1260, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1358, in evaluate_codeblock

    raise e
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1352, in evaluate_codeblock

    self.evaluate_statement(cur)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1473, in evaluate_statement

    return self.function_call(cur)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 2494, in function_call
    return self.funcs[func_name](node, self.flatten(posargs), kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 74, in wrapped
    return f(self, node, args, kwargs)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1688, in func_project
    self.add_languages(args[1:], True)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1804, in add_languages
    (comp, cross_comp) = self.detect_compilers(lang, need_cross_compiler)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\interpreter.py", line 1773, in detect_compilers
    comp.sanity_check(self.environment.get_scratch_dir(), self.environment)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\compilers.py", line 684, in sanity_check
    return self.sanity_check_impl(work_dir, environment, 'sanitycheckc.c', code)
  File "c:\program files (x86)\python35-32\lib\site-packages\mesonbuild\compilers.py", line 659, in sanity_check_impl
    stde = stde.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
```

**Comment by msink** [comment] 2016-11-21 16:09
Simpest test - hello.c builds by msvc(32/64), mingw(32/64)

https://github.com/msink/hello-c

On appveyor all 4 test passed, on my local windows mingw passed, msvc crashes.

**Comment by msink** [comment] 2016-11-23 07:51
`chcp 65001` fixes this, at least on my computer (win7-x64 russian)

```
rem script for local testing

chcp 65001

for %%t in (mingw,msvc) do (
  for %%p in (x86,x64) do (
    for %%c in (debug,release) do (
      setlocal
      set Compiler=%%t
      set Platform=%%p
      set Configuration=%%c
      call appveyor.bat
      endlocal
    )
  )
)

```

**Comment by nirbheek** [comment] 2016-11-23 08:07
Apparently this is fixed with Python 3.6: https://www.python.org/dev/peps/pep-0528/

However, we should also include a workaround inside Meson itself instead of telling people to run `chcp` before running Meson. Apparently there is also a module that does this: https://pypi.org/project/win_unicode_console/

Could you please try to use that and tell us if it works? If so, it would be great to have a patch to Meson that does what the module does on Windows.

**Comment by QuLogic** [comment] 2016-11-23 08:26
That PEP is about console I/O (as is the package) but Meson here is crashing due to a bad decode out of `subprocess`. Could using `universal_newlines=True` fix the problem?

**Comment by msink** [comment] 2016-11-23 08:40
> a module that does this: https://pypi.org/project/win_unicode_console/
No, I tried this - no result.
`chcp 65001` fixes by build.
Dont know why.

**Comment by nirbheek** [comment] 2016-11-24 11:06
My Windows doesn't have Russian or any European language available (probably because of ridiculous OEM things). I tested this with Hindi as my display language but I couldn't reproduce it (probably because it retained `cp1252` as the codepage). I'm going to try shooting in the dark now and send you some patches to test.

**Comment by msink** [comment] 2016-11-24 11:18
Okey, or I can pull a branch of your repository ( https://github.com/centricular/meson.git ) and test...

**Comment by msink** [comment] 2016-11-25 08:54
This patch fixes msvc on my computer:
```
diff --git a/mesonbuild/compilers.py b/mesonbuild/compilers.py
index ced2b6f..96af423 100644
--- a/mesonbuild/compilers.py
+++ b/mesonbuild/compilers.py
@@ -12,6 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+import sys
 import shutil
 import contextlib
 import subprocess, os.path
@@ -461,8 +462,8 @@ class Compiler():
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE)
                 (stde, stdo) = p.communicate()
-                stde = stde.decode()
-                stdo = stdo.decode()
+                stde = stde.decode(sys.stderr.encoding)
+                stdo = stdo.decode(sys.stdout.encoding)
                 mlog.debug('Compiler stdout:\n', stdo)
                 mlog.debug('Compiler stderr:\n', stde)
 
@@ -655,8 +656,8 @@ class CCompiler(Compiler):
         cmdlist = self.exelist + extra_flags + [source_name] + self.get_output_args(binary_name)
         pc = subprocess.Popen(cmdlist, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=work_dir)
         (stdo, stde) = pc.communicate()
-        stdo = stdo.decode()
-        stde = stde.decode()
+        stdo = stdo.decode(sys.stdout.encoding)
+        stde = stde.decode(sys.stderr.encoding)
         mlog.debug('Sanity check compiler command line:', ' '.join(cmdlist))
         mlog.debug('Sanity check compile stdout:')
         mlog.debug(stdo)
@@ -774,8 +775,8 @@ int main () {{
                 return RunResult(False)
 
             (so, se) = pe.communicate()
-        so = so.decode()
-        se = se.decode()
+        so = so.decode(sys.stdout.encoding)
+        se = se.decode(sys.stderr.encoding)
         mlog.debug('Program stdout:\n')
         mlog.debug(so)
         mlog.debug('Program stderr:\n')
```

Dont know if it is correct way (I'm total noob in python) but it works for me.

**Comment by nirbheek** [comment] 2016-12-07 01:36
@msink could you please try the branch at #1156 and see if that fixes it for you?

**Closed** 2016-12-10 23:59 UTC
Labels: bug, regression, windows
