### ISSUE TITLE
Auto generation of code doesn't work using custom_target()

### ISSUE THREAD

**Issue by lkammath** [mesonbuild/meson#6054] opened 2019-10-16 13:59 UTC
I am trying to generate some header/c files using a custom Perl script using curtom_target

here is the code snippet

env = environment()
env.set('SRCPATH', project_source_root, 'src')
auto_generate_src = run_command('env', env: env)

message('Autogenerating of ecmd & client CAPI code')
makedll_cmd = find_program('tool/mkscripts/autogen.pl')
foreach code_gen : ['A.C', 'A.H', 'X.H']
   autogen_target = custom_target(
     code_gen,
     output: code_gen,
     input:'autogen.pl',
     command: [perl, '@INPUT@','--opt','@OUTPUT@'])
endforeach

The autogen script creates the files in the path where SRCPATH environment pointing to . that is how the perl script is written

I am unable make the meson snippet work for some reason. Could some one throw some light here ?

**Comment by eli-schwartz** [comment] 2021-11-24 01:48
Duplicate of #6052

**Closed by eli-schwartz** 2021-11-24 01:48 UTC
