### ISSUE TITLE
Get option list before first configuration from CLI

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#4013] opened 2018-08-11 14:29 UTC
As far as I could test/read in docs, we cannot currently get the list of options from CLI before the first configuration. Basically I want to be able to get the output of a simple `meson configure` before the first configuration (same as we can run `./configure --help` before the first `./configure`).

Currently here is the output:

```
$ meson configure
Meson configurator encountered an error:

ERROR: Directory /home/jehan/dev/src/glib does not seem to be a Meson build directory.
```

This is very annoying, even more as some options may change the dependency list. So we may end up having to install useless dependencies just to make a first configuration, then changing the options for reconfiguration (where these dependencies are no more).

So I propose that `meson configure` works even when unconfigured (in which case `Current Value` column would either be absent, show nothing or the default value which would be selected if we were to run a configuration with no option). Or course, it could take the source path as parameter so that we can run it from the build directory.

P.S.: I know that options can be checked in `meson_options.txt` but this is not as practical. Meson really needs the `--help` equivalent of autotools IMO.

**Comment by nirbheek** [comment] 2018-08-11 15:26
Duplicate of https://github.com/mesonbuild/meson/issues/2402

**Comment by nirbheek** [comment] 2018-08-11 15:26
See also https://github.com/mesonbuild/meson/issues/2543

**Closed by nirbheek** 2018-08-11 15:26 UTC
