### ISSUE TITLE
Coverage regression on macOS Catalina

### ISSUE THREAD

**Issue by kyonifer** [mesonbuild/meson#6188] opened 2019-11-15 17:10 UTC
On macOS Mojave, enabling `b_coverage=true` resulted in successfully instrumented test executables generating .gcno files. On Catalina, I instead get

```
ERROR: Linker APPLE ld doesn't implement coverage data generation.
```

The following patch seems to fix coverage generation on Catalina for me:

```diff
diff --git a/mesonbuild/linkers.py b/mesonbuild/linkers.py
index 84bfceb4..371220bf 100644
--- a/mesonbuild/linkers.py
+++ b/mesonbuild/linkers.py
@@ -580,6 +580,9 @@ class AppleDynamicLinker(PosixDynamicLinkerMixin, DynamicLinker):
             result.append(a)
         return result

+    def get_coverage_args(self) -> typing.List[str]:
+        return ['--coverage']
+
     def sanitizer_args(self, value: str) -> typing.List[str]:
         if value == 'none':
             return []
```

#6160 may be relevant here, as it suggests that clang coverage shouldn't be working at all with meson. I didn't investigate further to figure out why the above patch wasn't necessary on Mojave but now is.

If desired, I can open a PR with the above patch, but at this point I'm not confident I know what the root issue is.

**Comment by krader1961** [comment] 2019-11-17 03:21
FWIW, I opened issue #6191 a few minutes ago. After someone pointed out it was essentially a duplicate of this issue I applied this fix to the meson master branch on my system and it does indeed correct the problem for me on macOS 10.15.1. It's not obvious this fix is correct in all situations since it might be incorrect for older macOS/Xcode versions (but probably isn't).

**Comment by scivision** [comment] 2019-11-17 05:50
Yes perhaps open a PR on this to run it through the CI which is still on Mojave last I looked.

**Comment by krader1961** [comment] 2019-11-18 02:18
I looked at the code before commit PR #5681 that separated the linker from the compiler. The old code simply assumed the `--coverage` flag was the appropriate way to enable coverage data if the compiler looked like a typical C compiler. PR #5681 simply overlooked that the fix proposed in this issue was the default behavior on macOS prior to that PR; that is, the bug is an understandable oversight in PR #5681. This fix simply reinstates the old behavior and therefore should be correct even on macOS/Xcode versions prior to Catalina. This issue only superficially looks like a macOS Catalina release issue because people who recently upgraded to that OS release are also likely to have updated their meson version at the same time.

**Closed** 2019-11-19 10:46 UTC
Labels: macos
