### ISSUE TITLE
Handling Qt5 resource files results in ninja dependency errors

### ISSUE THREAD

**Issue by Framstag** [mesonbuild/meson#2763] opened 2017-12-11 16:17 UTC
This directora structure for the given Qt sub project: https://github.com/Framstag/libosmscout/tree/master/OSMScout2

As you can see there is a res.qrc in the top-level directory (though the OSMScout2 application is only a sub directory of the full project). The file references actual resources in the res sub directory.

Now a `meson debug` call and  `ninja` call in the created `debug` directory results in:

```
ninja: error: '../OSMScout2/OSMScout2/pics/Search.svg', needed by 'OSMScout2/qt5-res_qrc.cpp', missing and no known rule to make it
```

Looking at the build.ninja one sees:

```
build OSMScout2/qt5-res_qrc.cpp: CUSTOM_COMMAND ../OSMScout2/./res.qrc | ../OSMScout2/OSMS
cout2/./pics/Search.svg ../OSMScout2/OSMScout2/./qml/custom/LocationSearch.qml ../OSMScout
2/OSMScout2/./pics/Download.svg ../OSMScout2/OSMScout2/./qml/custom/MapDialog.qml ../OSMSc
out2/OSMScout2/./qml/custom/LineEdit.qml ../OSMScout2/OSMScout2/./pics/DeleteText.svg ../O
SMScout2/OSMScout2/./resources/online-tile-providers.json ../OSMScout2/OSMScout2/./pics/Mi
nus.svg ../OSMScout2/OSMScout2/./qml/custom/MapButton.qml ../OSMScout2/OSMScout2/./qml/cus
tom/DialogActionButton.qml ../OSMScout2/OSMScout2/./qml/main.qml ../OSMScout2/OSMScout2/./
qml/SearchDialog.qml ../OSMScout2/OSMScout2/./qml/custom/ScrollIndicator.qml ../OSMScout2/
OSMScout2/./resources/map-providers.json ../OSMScout2/OSMScout2/./qml/MapDownloadDialog.qm
l ../OSMScout2/OSMScout2/./pics/Route.svg ../OSMScout2/OSMScout2/./qml/AboutDialog.qml ../
OSMScout2/OSMScout2/./pics/Plus.svg /usr/local/Cellar/qt/5.10.0/bin/rcc
 COMMAND = /usr/local/Cellar/qt/5.10.0/bin/rcc -name res -o OSMScout2/qt5-res_qrc.cpp ../OSMScout2/./res.qrc
 description = Generating$ qt5-res_qrc$ with$ a$ custom$ command.
```

For me it looks like meson gets into problems with the actual directory structure and claims (resource) files being positioned in directories more "up" in the directory structure then they actually are.

An (simple) workaround would be helpful (since builds break now), I can also try to test (simple) patches to test potential fixes.

**Comment by Framstag** [comment] 2017-12-11 18:18
This is with meson 0.44.0, 0.43.0 worked without problems.

**Comment by TheAssassin** [comment] 2018-01-31 19:39
The same bug affects https://github.com/GNOME/gnome-multi-writer.

**Comment by nirbheek** [comment] 2018-02-19 17:46
@TheAssassin do you mean https://github.com/mesonbuild/meson/issues/2860?

**Comment by jeandet** [comment] 2018-02-19 17:49
@Framstag Does #2956 solve the issue?

**Comment by nirbheek** [comment] 2018-02-19 18:01
Yes, I just tested it by building OSMScout. It's fixed. The fix is already in the 0.44 branch, and will be in the 0.44.1 release.

**Closed by nirbheek** 2018-02-19 18:01 UTC
Labels: bug, qt, regression

**Comment by TheAssassin** [comment] 2018-02-19 19:23
@nirbheek could be, I was just looking for a similar error message in this issue tracker, and this one seemed similar.

**Comment by Framstag** [comment] 2018-02-19 19:29
As you already checked, I do not need to test anymore?

We do still have a permanent red build for this (https://ci.appveyor.com/project/Framstag/libosmscout), for the other builds we have fixed it temporary by setting links in the file system, but this did not work out under Windows ;-) So if 0.44.1 should enter msys/mingw, the build should be green again.

**Comment by nirbheek** [comment] 2018-02-19 20:10
> As you already checked, I do not need to test anymore?

It never hurts to do extra testing, so if you want to verify it that would be great :)

> for the other builds we have fixed it temporary by setting links in the file system, but this did not work out under Windows ;-)

You can do that with `mklink` on NTFS too, but you need admin privileges :wink:

**Comment by TheAssassin** [comment] 2018-02-19 20:25
@nirbheek see https://travis-ci.org/TheAssassin/gnome-multi-writer/jobs/335810298#L2916.

**Comment by nirbheek** [comment] 2018-02-19 20:30
@TheAssassin that looks like https://github.com/mesonbuild/meson/issues/2845? However, I can't reproduce it locally.

**Comment by TheAssassin** [comment] 2018-02-19 20:33
I can reproduce this issue on my xenial machine locally, with the latest meson installed. What system are you running? I'll try to build it in a container then.

**Comment by nirbheek** [comment] 2018-02-19 20:58
I am running Fedora 27 with meson master.

**Comment by nirbheek** [comment] 2018-02-19 20:59
Also, let's continue discussion on https://github.com/mesonbuild/meson/issues/2845 once you have more information.

**Comment by TheAssassin** [comment] 2018-02-19 21:09
Thanks, @nirbheek. I appreciate your help. I'll post more information there. Please beware I'm trying to build an AppImage that should run on as many systems as possible, and for AppImages the lower compatibility limit is always the distro they're built on, i.e., distros older than the build system won't be able to run the system.

**Comment by Framstag** [comment] 2018-02-22 20:09
meson 0.44.1 is already available for Arch-Linux. After reverting the symlink I set to fix the problem, it does build the source. I removed the workaround in the central builds and see if they work, too.
