### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 669: invalid start byte

### ISSUE THREAD

**Issue by antekone** [mesonbuild/meson#10968] opened 2022-10-30 10:52 UTC
**Describe the bug**

I'm trying to compile libadwaita e8622df35b8cc6ef1470c1a9aa2f0fd164ab4349 on Windows 10. I'm getting this error on project configuraton:

```
antek@MORDOR C:\dev\adwaita\libadwaita>meson setup builddir --prefix=c:/runtime/adwaita
The Meson build system
Version: 0.63.3
Source dir: C:\dev\adwaita\libadwaita
Build dir: C:\dev\adwaita\libadwaita\builddir
Build type: native build
Project name: libadwaita
Project version: 1.3.alpha
Traceback (most recent call last):
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\msetup.py", line 303, in run
    app.generate()
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\msetup.py", line 186, in generate
    self._generate(env)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\msetup.py", line 208, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 344, in __init__
    self.parse_project()
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 580, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1257, in func_project
    if mesonlib.setup_vsenv(force_vsenv):
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\mesonlib\vsenv.py", line 110, in setup_vsenv
    return _setup_vsenv(force)
  File "C:\Users\antek\scoop\apps\python\current\lib\site-packages\mesonbuild\mesonlib\vsenv.py", line 65, in _setup_vsenv
    bat_info = json.loads(bat_json)
  File "C:\Users\antek\scoop\apps\python\current\lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 669: invalid start byte

meson.build:1:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

1. C:\dev\adwaita>git clone https://gitlab.gnome.org/GNOME/libadwaita.git

2. C:\dev\adwaita\libadwaita>meson setup builddir --prefix c:/runtime/adwaita

**Expected behavior**
Meson can build the project

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
It's a plain native build on Windows 10 amd64
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Windows 10 amd64
* what Python version are you using e.g. 3.8.0
 
```
antek@MORDOR C:\dev\adwaita\libadwaita>python --version
Python 3.10.4
```

* what `meson --version`

```
antek@MORDOR C:\dev\adwaita\libadwaita>meson --version
0.63.3
```

* what `ninja --version` if it's a Ninja build

Don't have Ninja

**Comment by antekone** [comment] 2022-10-30 10:58
I've added a dump of the `bat_json` variable that is the argument to json.loads:

```
bat=b'[\r\n  {\r\n    "instanceId": "b6dcfd31",\r\n    "installDate": "2022-05-16T10:23:59Z",\r\n    "installationName": "VisualStudio/17.2.5+32616.157",\r\n    "installationPath": "C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\
\\Community",\r\n    "installationVersion": "17.2.32616.157",\r\n    "productId": "Microsoft.VisualStudio.Product.Community",\r\n    "productPath": "C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\Common7\\\\IDE\\\\
devenv.exe",\r\n    "state": 4294967295,\r\n    "isComplete": true,\r\n    "isLaunchable": true,\r\n    "isPrerelease": false,\r\n    "isRebootRequired": false,\r\n    "displayName": "Visual Studio Community 2022",\r\n    "description": "
Zaawansowane \x98rodowisko IDE - bezp\x88atne dla uczni\xa2w i student\xa2w, wsp\xa2\x88autor\xa2w oprogramowania open source oraz indywidualnych os\xa2b",\r\n    "channelId": "VisualStudio.17.Release",\r\n    "channelUri": "https://aka.m
s/vs/17/release/channel",\r\n    "enginePath": "C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\Installer\\\\resources\\\\app\\\\ServiceHub\\\\Services\\\\Microsoft.VisualStudio.Setup.Service",\r\n    "installedChannelUri": "https
://aka.ms/vs/17/release/channel",\r\n    "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.2#17.2.5",\r\n    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",\r\n    "updat
eDate": "2022-07-08T04:46:56.4238015Z",\r\n    "catalog": {\r\n      "buildBranch": "d17.2",\r\n      "buildVersion": "17.2.32616.157",\r\n      "id": "VisualStudio/17.2.5+32616.157",\r\n      "localBuild": "build-lab",\r\n      "manifest
Name": "VisualStudio",\r\n      "manifestType": "installer",\r\n      "productDisplayVersion": "17.2.5",\r\n      "productLine": "Dev17",\r\n      "productLineVersion": "2022",\r\n      "productMilestone": "RTW",\r\n      "productMileston
eIsPreRelease": "False",\r\n      "productName": "Visual Studio",\r\n      "productPatchVersion": "5",\r\n      "productPreReleaseMilestoneSuffix": "1.0",\r\n      "productSemanticVersion": "17.2.5+32616.157",\r\n      "requiredEngineVers
ion": "3.2.2159.37022"\r\n    },\r\n    "properties": {\r\n      "campaignId": "2030:e10f446e-51c3-494a-93ef-3e832dbe29a9",\r\n      "channelManifestId": "VisualStudio.17.Release/17.2.5+32616.157",\r\n      "nickname": "",\r\n      "setup
EngineFilePath": "C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\Installer\\\\setup.exe"\r\n    }\r\n  }\r\n]\r\n'
```

It seems that my visual studio localization is Polish, and the "description" string is stored using Windows1250 encoding, is this the bug?

**Comment by antekone** [comment] 2022-10-30 11:05
It seems that the `vswhere` tool ignores the `-utf8` argument and uses my terminal's encoding anyway. I've changed the terminal codepage to utf-8 manually:

```
antek@MORDOR C:\dev\adwaita\libadwaita>chcp 65001
Active code page: 65001
```

and now Meson works.

**Comment by eli-schwartz** [comment] 2022-10-30 11:25
Duplicate of #10799

**Closed by eli-schwartz** 2022-10-30 11:25 UTC
