### ISSUE TITLE
Unhandled python exception when compiling outside build directory

### ISSUE THREAD

**Issue by oskar-qrt** [mesonbuild/meson#9846] opened 2022-01-19 09:17 UTC
**Describe the bug**
Unhandled python execption when compiling a project from outside the build directory.

**To Reproduce**
$ meson init --name testproject --build
$ meson compile

Output:
ERROR: Unhandled python exception
    This is a Meson bug and should be reported!

**Expected behavior**
Either the project should compile or meson should quit gracefully.

**system parameters**
* Plain native build
* Kali-Linux on WSL2
* Python 3.9.2
* Meson 0.61.0
* Ninja 1.10.1

**Comment by wbthomason** [comment] 2022-01-19 18:40
I'm running into the same bug whether I build inside or outside the build directory. The traceback is as follows, for the minimal reproducing example given by @oskar-qrt :
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/mcompile.py", line 325, in run
    cdata = coredata.load(options.wd)
  File "/usr/lib/python3.10/site-packages/mesonbuild/coredata.py", line 1033, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wil/mesontest/meson-private/coredata.dat'
```
**System:**
- Arch Linux
- Python 3.10.1
- Meson 0.61.1
- Ninja 1.10.2

**Comment by wbthomason** [comment] 2022-01-19 18:45
I've also reproduced this issue with Meson 0.60.3.

**Comment by eli-schwartz** [comment] 2022-01-21 19:14
Duplicate of #9584

**Closed by eli-schwartz** 2022-01-21 19:14 UTC
