### ISSUE TITLE
Meson module "features" (required by numpy)?

### ISSUE THREAD

**Issue by hergljkds** [mesonbuild/meson#12928] opened 2024-03-02 22:03 UTC
Where is the meson module 'features'?

**Comment by eli-schwartz** [comment] 2024-03-03 00:50
See #11307 -- note that numpy is writing this functionality (and also a blas dependency) and also, as I understand it, field-testing it to make sure it handles everything it needs to handle, which is why @seiko2plus and @rgommers aren't quite ready to land it. This means that numpy will only build using their vendored fork for the moment.

**Comment by eli-schwartz** [comment] 2024-03-03 00:51
Duplicate of #12572

**Closed by eli-schwartz** 2024-03-03 00:51 UTC
