### ISSUE TITLE
The default libdir for non system-wide prefix should be 'lib'

### ISSUE THREAD

**Issue by arteymix** [mesonbuild/meson#2197] opened 2017-08-15 20:49 UTC
Meson currently uses `lib64` when installing with `--prefix=$HOME/.local` and `prefix=/usr/local`, but that's an exception for system-wide installation and not a general rule.

I think that `lib64` should be checked relatively to the prefix of installation instead.

To be more concise, this is happening on system that have a `/usr/lib64` directory (i.e. Fedora) as it is hard-coded in  https://github.com/mesonbuild/meson/blob/master/mesonbuild/mesonlib.py#L325

**Comment by nirbheek** [comment] 2017-08-17 10:29
The main problem seems to be that our default libdir doesn't take the prefix into account. It will require a bit of refactoring to pass that to `default_libdir()`, but it is doable.

**Comment by ccope** [comment] 2018-04-24 06:07
I just hit the linked issue with libfuse. On Ubuntu 16.04 it's installing the library into `/usr/local/lib/x86_64-linux-gnu`, but only ld only searches `/usr/local/lib`.

**Comment by nirbheek** [comment] 2018-05-25 14:39
(consolidating libdir detection issues in one place)

Duplicate of #2038

**Closed by nirbheek** 2018-05-25 14:39 UTC
Labels: bug
