### ISSUE TITLE
Provide a meson.bat for Windows users

### ISSUE THREAD

**Issue by elig0n** [mesonbuild/meson#3217] opened 2018-03-11 15:15 UTC
meson 0.45.0 install with pip3 on Windows 10  (Python 3.6.2 )

>\>python meson.py
Traceback (most recent call last):
  File "meson.py", line 17, in <module>
    from mesonbuild import mesonmain, mesonlib
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\mesonbuild\mesonmain.py", line 18, in <module>
    from . import environment, interpreter, mesonlib
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\mesonbuild\environment.py", line 17, in <module>
    from . import coredata
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\mesonbuild\coredata.py", line 20, in <module>
    from .mesonlib import MesonException
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\mesonbuild\mesonlib.py", line 78, in <module>
    meson_command = python_command + [detect_meson_py_location()]
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\mesonbuild\mesonlib.py", line 70, in detect_meson_py_location
    raise RuntimeError('Could not determine how to run Meson. Please file a bug with details.')
RuntimeError: Could not determine how to run Meson. Please file a bug with details.

**Comment by jpakkane** [comment] 2018-03-11 15:47
On Windows you should not run pip installed binaries like that. Instead you should do `meson <options>`. I just tested this and it seems to work on Windows 10 and Python 3.6.4. Can you test that?

**Comment by elig0n** [comment] 2018-03-11 19:31
I already did -
\>pip3 install meson
Requirement already satisfied: meson in c:\users\x\appdata\local\programs\python\python36\lib\site-packages
\>meson
'meson' is not recognized as an internal or external command, operable program or batch file.

**Comment by nirbheek** [comment] 2018-03-11 19:46
You have to ensure that the `py` launcher is installed with your installation. I don't know if that happens by default.

I think we should consider shipping a `meson.bat` file that contains `C:\path\to\python C:\path\to\meson.py %*`, and put it in `PATH`. That will make it easier for users.

**Comment by nirbheek** [comment] 2018-08-02 10:47
Duplicate of https://github.com/mesonbuild/meson/issues/1877

**Closed by nirbheek** 2018-08-02 10:47 UTC
Labels: bug, windows
