### ISSUE TITLE
Support path segments in output kwarg of custom_target()

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#8374] opened 2021-02-17 02:17 UTC
I am writing Java bindings for my project. I have a couple of Java dependencies, so I am using Maven to compile/package the Java portion of the bindings. Maven creates a lot of output files in various output directories. Maven has two commands: compile and package. Compile creates .class files out of your .java files, and package is a combination of compile and building the physical jar out of those class files. I want to be a good Meson developer, and specify the outputs accordingly, but because Maven places outputs in directories, I cannot correctly specify them in the output kwarg of custom_target() because I would need to specify path segments.

I am sure there are other tools with this same issue. I think I have seen similar issues in #gtk with the new gtk-doc development by @ebassi.

**Comment by bonzini** [comment] 2021-02-17 10:40
Duplicate of #2320. This is the number 1 annoyance in Meson for me too.

**Closed** 2021-02-17 14:59 UTC
