### ISSUE TITLE
Suppport unity option per subproject

### ISSUE THREAD

**Issue by 3v1n0** [mesonbuild/meson#8734] opened 2021-05-06 18:09 UTC
I would like to use `--unity on` in my project but exclude some subprojects that doesn't properly handle it, but it's not possible to use

```
subproject('foo', default_options: 'unity=off')
```

**Comment by bruchar1** [comment] 2023-02-17 19:18
Duplicates ##5392.

**Comment by eli-schwartz** [comment] 2023-02-24 16:07
Duplicate of #5392

**Closed by eli-schwartz** 2023-02-24 16:07 UTC
