### ISSUE TITLE
VS backend sometimes produces references to nonexistent obj files in both_libraries()

### ISSUE THREAD

**Issue by jenatali** [mesonbuild/meson#9235] opened 2021-09-09 00:29 UTC
**Describe the bug**
I see this when building [this gist](https://gist.github.com/jenatali/aecd7a5194a6eb3f1d4f9ced2b36c9cc) using the VS backend:

```
4>------ Build started: Project: both_lib, Configuration: debug x64 ------
4>LINK : fatal error LNK1181: cannot open input file 'static_lib@sta\meson-generated_.._generated.c.obj'
4>Done building project "both_lib@sta.vcxproj" -- FAILED.
```

The target `both_lib@sta.vcxproj` is the static version of a `both_libraries` target. It is set to `link_with` a static library (`static_lib`), which includes several source files, both checked in and generated. Due to the `install : true` property, this static library attempts to archive all of the object files from all of its dependencies. It also provides incorrect filenames for some of the object files.

Using the Ninja backend, I see the same behavior *except* that the files referenced actually are created, with a naming convention of `meson-generated_<path-to-file>.obj`, where `<path-to-file>` has path separators replaced with underscores.

**To Reproduce**
From a VS command prompt:
* Clone https://gist.github.com/aecd7a5194a6eb3f1d4f9ced2b36c9cc.git
* `mkdir build`
* `python meson.py setup build --backend=vs2019`
* `msbuild test.sln`

See that the build fails.

**Expected behavior**
I'd expect the build of the `static_lib` static library to produce files with the expected filenames, the same as the Ninja backend.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Windows 10
* what Python version are you using e.g. 3.8.0
  * 3.8.2
* what `meson --version`
  * 0.59.99 (sha 0fcd696b1e0c6ff9ca462ac2f8e0d497bf11e2c5)
* what `ninja --version` if it's a Ninja build
  * N/A

**Comment by xclaesse** [comment] 2021-09-09 00:57
When a static library A that will be installed links to another static library B that will not be installed, meson passes all objects from B to A.

```meson
a = static_library(...)
b = static_library(..., link_with: a, install: true)
```
Should be equivalent to
```meson
a = static_library(...)
b = static_library(..., a.extract_all_objects(), install: true)
```

**Comment by xclaesse** [comment] 2021-09-09 01:07
> `python meson.py setup build -Dspirv-to-dxil=true -Dgallium-drivers= -Dvulkan-drivers= -Dcpp_std=vc++latest --backend=vs2019`

Getting that:
`src\compiler\glsl\glcpp\meson.build:34:0: ERROR: Tried to use not-found external program in "command"`

**Comment by jenatali** [comment] 2021-09-09 01:09
Ah, I probably have more dependencies in my environment (e.g. flex/bison). Let me add some `install: true` to my attempted reproducer, thanks.

**Comment by xclaesse** [comment] 2021-09-09 01:14
@jenatali @dcbaker offtopic: you could want that hack to have bison/flex on Windows: https://gitlab.freedesktop.org/gstreamer/gst-build/-/tree/master/subprojects/win-flex-bison-binaries.

**Comment by jenatali** [comment] 2021-09-09 01:16
That's probably a good idea...

Either way, here's a proper minimal repro: https://gist.github.com/jenatali/aecd7a5194a6eb3f1d4f9ced2b36c9cc. I'll update the main issue description to add that `install: true` is the key, and add that link.

**Comment by xclaesse** [comment] 2021-09-09 01:35
@jenatali You could create a PR add that under `test cases/windows/`, to verify our CI can reproduce that bug.

**Comment by anarazel** [comment] 2021-09-17 19:29
I hit this as well, and I think I found the bug.

The problem is that, in @jenatali's reproducer, the output filename for 'generated.c' isn't set. Which leaves it to cl.exe to determine an output name, which will be just 'generated.obj'. Thus it ends up as build/static_lib@sta/generated.obj. But then the static_lib is built, which tries to reuse the object. But uses (via `flatten_object_list()`) `object_filename_from_source()` to link to the generated object as 'static_lib@sta\meson-generated_.._generated.c.obj'. Hence the link failure.

The problem is https://github.com/mesonbuild/meson/blob/e006e2ee993b3922eadbdb6abac72b9b580ce487/mesonbuild/backend/vs2010backend.py#L1344 - note that in contrast to the "plain" sources `ObjectFileName` isn't set for generated sources.

**Comment by anarazel** [comment] 2021-09-17 19:43
```python
    s = File.from_built_file(target.get_subdir(), s)
    ET.SubElement(inc_cl, 'ObjectFileName').text = "$(IntDir)" + self.object_filename_from_source(target, s)
```
looks like it might do the trick.

@jenatali Are you ok with me opening a PR that includes your test as a separate commit?

**Comment by jenatali** [comment] 2021-09-17 19:48
> @jenatali Are you ok with me opening a PR that includes your test as a separate commit?

By all means. There's a missing json file from the test causing the non-VS generators to fail. I mainly had the test as a POC so I didn't fix that yet. If you can fix it, go for it, otherwise I can push a fix for that later.

**Comment by anarazel** [comment] 2021-09-17 21:17
I think there's actually a separate buglet breaking make install for shared libraries (including both_libraries), separate from the 
```LINK : fatal error LNK1181: cannot open input file 'static_lib@sta\meson-generated_.._generated.c.obj'``` issue you reported. Apparently link.exe doesn't generate an import lib when there are no exported symbols. But meson install expects it to be present...

**Closed** 2021-09-22 17:40 UTC
