### ISSUE TITLE
mesonintrospect is broken

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#2778] opened 2017-12-13 16:54 UTC
`meson introspect` isn't.

```python
Traceback (most recent call last):
  File "/usr/bin/mesonintrospect", line 17, in <module>
    from mesonbuild import mesonmain
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 18, in <module>
    from . import environment, interpreter, mesonlib
  File "/usr/lib/python3.6/site-packages/mesonbuild/environment.py", line 17, in <module>
    from . import coredata
  File "/usr/lib/python3.6/site-packages/mesonbuild/coredata.py", line 20, in <module>
    from .mesonlib import MesonException, commonpath
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 60, in <module>
    meson_command = python_command + [detect_meson_py_location()]
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonlib.py", line 51, in detect_meson_py_location
    raise RuntimeError('Could not determine how to run Meson. Please file a bug with details.')
RuntimeError: Could not determine how to run Meson. Please file a bug with details.
```

**Comment by nirbheek** [comment] 2017-12-13 22:22
Duplicate of https://github.com/mesonbuild/meson/issues/2761.

**Closed by nirbheek** 2017-12-13 22:22 UTC
Labels: regression
