### ISSUE TITLE
meson creates symlink to unversioned so too early

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#1187] opened 2016-12-13 10:45 UTC
```
$ meson sdk/angelscript/projects/meson/ build
The Meson build system
Version: 0.37.0.dev1
Source dir: /home/brain/git/fedora/angelscript/angelscript-2.31.1/sdk/angelscript/projects/meson
Build dir: /home/brain/git/fedora/angelscript/angelscript-2.31.1/build
Build type: native build
Program python3 found: YES (/usr/bin/python3)
Project name: angelscript
Native cpp compiler: c++ (gcc 6.2.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Program python3 found: YES (/usr/bin/python3)
Build targets in project: 1
$ file build/libangelscript.so 
build/libangelscript.so: broken symbolic link to libangelscript.so.23101
```

I didn't run ninja yet, so it seems like bug.

**Comment by ignatenkobrain** [comment] 2016-12-13 10:46
it doesn't seem like regression, but definitely looks like bug.

**Comment by nirbheek** [comment] 2016-12-13 11:30
How is this a problem?

**Comment by ignatenkobrain** [comment] 2016-12-13 11:32
@nirbheek, it's not really problem.. But in theory, if you have -L/foo/build -langelscript this could end with some weird errors. We don't create libfoo.so.X symlink before we build libfoo.so.X.Y, right? IMO it's same situation.

**Comment by jpakkane** [comment] 2016-12-13 11:39
I changed this to do this on purpose. The symlink is created during Meson run rather than with Ninja because

a) it is always the same
b) it simplifies the Ninja rules

**Comment by ignatenkobrain** [comment] 2016-12-13 11:42
@jpakkane what will happen if you change soversion? will symlink automatically changed?

**Comment by jpakkane** [comment] 2016-12-13 11:49
The same thing as currently. That is, Meson will reinvoke itself, delete the old .so symlink and create a new one pointing to the new file.

**Comment by jpakkane** [comment] 2016-12-29 18:32
Closing since there does not seem to be an actual error caused by this. File a new bug with specific error case if one is found.

**Closed by jpakkane** 2016-12-29 18:32 UTC
