### ISSUE TITLE
Suppress ranlib warning when building on macOS

### ISSUE THREAD

**Issue by kirushyk** [mesonbuild/meson#2977] opened 2018-01-26 00:05 UTC
It looks like there is no way to pass "-no_warning_for_no_symbols" command line argument to ranlib.

**Comment by nirbheek** [comment] 2018-02-11 11:56
It's not clear what the issue is here, could you please elaborate?

**Comment by eli-schwartz** [comment] 2021-01-26 00:23
Closing due to lack of information about what the problem is.

Feel free to re-open if this is still a problem and the problem can be described in greater detail.

**Closed by eli-schwartz** 2021-01-26 00:23 UTC
Labels: OS:macos, support/RFC
