### ISSUE TITLE
Eliminate error about build directory being from a previous version of Meson

### ISSUE THREAD

**Issue by pwithnall** [mesonbuild/meson#2354] opened 2017-09-21 07:24 UTC
In my auto-builder, I frequently get errors like this:
```
Meson encountered an error:
Build directory has been generated with Meson version 0.42.0, which is incompatible with current version 0.42.1.
Please delete this build directory AND create a new one.
FAILED: build.ninja 
```

Why can’t Meson delete the build directory itself, if it knows it’s out of date? This causes builds to fail spuriously every time someone upgrades the Meson version in GNOME’s JHBuild moduleset.

**Comment by QuLogic** [comment] 2017-09-21 07:42
Dupe of #2026.

**Comment by nirbheek** [comment] 2017-09-21 07:45
See also: https://github.com/mesonbuild/meson/pull/1662 which actually implements this.

**Comment by pwithnall** [comment] 2017-09-21 09:02
#1662 looks like what I want, thanks!

> Dupe of #2026.

Not quite. I Meson to do whatever it takes to get the build to succeed; an error message which includes the old configuration information is just as useless to me as an error message which doesn’t.

**Comment by nirbheek** [comment] 2017-09-21 10:12
I'll rebase and update #1622 then.

**Comment by YaLTeR** [comment] 2020-07-28 06:45
I'm hitting this on my project, except I'm doing `ninja install` as usual and getting a super cryptic exception in the middle of meson's source:
```
└─ ninja install
[0/1] Installing files.
Installing meson-out/org.gnome.gitlab.YaLTeR.VideoTrimmerDevel.desktop to /home/yalter/source/rs/video-trimmer/install/share/applications
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/minstall.py", line 542, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.8/site-packages/mesonbuild/minstall.py", line 362, in do_install
    self.install_targets(d)
  File "/usr/lib/python3.8/site-packages/mesonbuild/minstall.py", line 515, in install_targets
    depfixer.fix_rpath(outname, t.rpath_dirs_to_remove, install_rpath, final_path,
AttributeError: 'TargetInstallData' object has no attribute 'rpath_dirs_to_remove'
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```
Only upon trying `meson configure` I find out that my meson has updated and now refuses to work with the build directory:
```
└─ meson configure

ERROR: Build directory has been generated with Meson version 0.54.0, which is incompatible with current version 0.55.0.
```
How am I supposed to know this? Why doesn't meson just fix it by itself?

**Closed** 2020-09-10 12:38 UTC
Labels: bug, gnome

**Comment by slyfox1186** [comment] 2024-02-02 05:51
this is happening to me as well.

```
sudo ninja -j32 -C build install
ninja: Entering directory `build'
[0/1] Installing files.

ERROR: Build directory has been generated with Meson version 1.3.1, which is incompatible with the current version 1.0.1.
FAILED: meson-internal__install
/usr/local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by QuLogic** [comment] 2024-02-02 06:00
That sounds like you have a different version installed as your user vs root (`sudo`).

**Comment by slyfox1186** [comment] 2024-02-02 08:21
You are probably right that sudo is interfering.
I scanned the entire computer with the find command for 'meson'
and the only one installed it the same one for both root and users.

So this may not be the full extent of the problem.

**Comment by eli-schwartz** [comment] 2024-02-02 13:47
What is the output of `type -a meson`?

**Comment by slyfox1186** [comment] 2024-02-04 00:11
```
meson is /usr/bin/meson
meson is /bin/meson
```
