### ISSUE TITLE
Failure when using python 3.7

### ISSUE THREAD

**Issue by jjardon** [mesonbuild/meson#3821] opened 2018-07-01 21:47 UTC
Using python 3.7 to compile gstreamer-plugins-base we are getting the following error:

```
[--:--:--] STATUS  [desktop/gstreamer-plugins-base.bst]: Running configure-commands

    meson _builddir --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --sysconfdir=/usr/etc \
    --datadir=/usr/share \
    --includedir=/usr/include \
    --libdir=/usr/lib/x86_64-linux-gnu \
    --libexecdir=/usr/libexec \
    --localstatedir=/usr/var \
    --sharedstatedir=/usr/com \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info   -Duse_orc=yes
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/compilers.py", line 799, in compile
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 364, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 135, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 186, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3261, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 215, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 239, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 231, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 244, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 504, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 99, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2919, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 239, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 231, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 244, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 504, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 99, in wrapped
    return f(s, node_or_state, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 2919, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 239, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 231, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 254, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 307, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 239, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 231, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 254, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 301, in evaluate_if
    result = self.evaluate_statement(i.condition)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 264, in evaluate_statement
    return self.evaluate_andstatement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 364, in evaluate_andstatement
    r = self.evaluate_statement(cur.right)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 248, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 538, in method_call
    return obj.method_call(method_name, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 140, in method_call
    return method(args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 115, in wrapped
    return f(obj, args, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 1163, in has_header_method
    haz = self.compiler.has_header(hname, prefix, self.environment, extra_args, deps)
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/c.py", line 280, in has_header
    dependencies, 'preprocess')
  File "/usr/lib/python3.7/site-packages/mesonbuild/compilers/c.py", line 339, in compiles
    return p.returncode == 0
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
RuntimeError: generator raised StopIteration
The Meson build system
Version: 0.46.1
```

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/304#note_85374626

**Comment by jpakkane** [comment] 2018-07-01 21:51
Can you test trunk? I think this has been fixed in it.

**Comment by nirbheek** [comment] 2018-07-01 21:55
Duplicate of https://github.com/mesonbuild/meson/issues/3622.

**Closed by nirbheek** 2018-07-01 21:55 UTC
Labels: support

**Comment by nirbheek** [comment] 2018-07-01 21:56
0.47 will be released tomorrow, and that's all we can do to fix this.
