### ISSUE TITLE
Meson 1.3.0 fails on current Homebrew

### ISSUE THREAD

**Issue by cartesius68** [mesonbuild/meson#12614] opened 2023-12-08 22:49 UTC
(Current MacOS Sonoma with updated Homebrew packages, C++ project)

**Probably Python 3.12 related issue**

meson --version
1.3.0

ninja --version
1.11.1

cmake --version
cmake version 3.28.0

Log:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/msetup.py", line 181, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/msetup.py", line 226, in _generate
    intr.run()
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 3004, in run
    super().run()
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 172, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_codeblock
    raise e
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 530, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 260, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 579, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 2423, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_codeblock
    raise e
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 208, in evaluate_statement
    self.assignment(cur)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 644, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 518, in function_call
    (h_posargs, h_kwargs) = self.reduce_arguments(node.args)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 609, in reduce_arguments
    reduced_val = self.evaluate_statement(val)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 227, in evaluate_statement
    return self.evaluate_arraystatement(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 261, in evaluate_arraystatement
    (arguments, kwargs) = self.reduce_arguments(cur.args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 602, in reduce_arguments
    reduced_pos = [self.evaluate_statement(arg) for arg in args.arguments]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 204, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 530, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 809, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 809, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 809, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 108, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 126, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 260, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 579, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 1794, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 355, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/interpreter/dependencyfallbacks.py", line 87, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/dependencies/detect.py", line 124, in find_external_dependency
    d = c()
        ^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/dependencies/cmake.py", line 156, in __init__
    self._detect_dep(name, package_version, modules, components, cm_args)
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/dependencies/cmake.py", line 552, in _detect_dep
    rtgt = resolve_cmake_trace_targets(i, self.traceparser, self.env,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/mesonbuild/cmake/tracetargets.py", line 58, in resolve_cmake_trace_targets
    res.libraries += clib_compiler.find_library(curr, env, [])
TypeError: 'NoneType' object is not iterable

src/meson.build:12:1: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**Comment by dcbaker** [comment] 2023-12-09 01:52
Duplicate of https://github.com/mesonbuild/meson/issues/12555

**Closed by dcbaker** 2023-12-09 01:52 UTC
