### ISSUE TITLE
Differing ninja target behavior when accessing cmake subproject via sub_proj.target() method versus via __CMake_build dir

### ISSUE THREAD

**Issue by Michael-Densberger** [mesonbuild/meson#6959] opened 2020-04-11 20:03 UTC
**Describe the bug**
I am importing a large cmake projectwith quite a few targets. If I attempt to use Meson to retrieve a cmake target from within the subproject and execute it, I get errors. If I use ninja directly on the __CMake_build dir I can run the same target with no issues.

**To Reproduce**
I've created a repo to showcase an example ESP/meson integrated project but at the moment it's serving as an example of the problem behavior:
https://github.com/Michael-Densberger/meson_esp32

To produce the behavior I ran:
`mkdir /opt/meson_esp32`
`cd /opt/meson_esp32/`
`git clone git@github.com:Michael-Densberger/meson_esp32.git .`
`meson esp32/ build/ --cross-file=esp32/cross.txt`
`ninja -C build/ flash_from_cmake_root` <- Works and flashes no problem.
`ninja -C build/ flash` <- Build errors that vary. 

Note flash and flash_from_cmake_root are Meson `run_targets` that I defined in `meson.build` in the repo.

**Expected behavior**
The flash from the top level which is a `cmake.subproject` target would behave the same as the flash target in the lower level subproject `__CMake_build` folder.

**system parameters**
* Cross build.
* Up-to-date Arch linux.
* Python: 3.8.2
* Meson: 0.54.0
* Ninja: 1.10.0

**Comment by Michael-Densberger** [comment] 2020-04-11 20:17
Note I've applied the changes proposed in #6941 to my local Meson installation. I imagine anyone reproducing would need to do the same.

**Comment by mensinda** [comment] 2020-04-11 20:36
I am unable to reproduce this with my AUR setup. I get the following CMake error:

```
||CMake Error at /home/daniel/builds/esp-idf/meson_esp32/esp32/subprojects/esp32/main/CMakeLists.txt:1 (idf_component_register):
||  Unknown CMake command "idf_component_register".
||Call Stack (most recent call first):
||  /opt/esp-idf/tools/cmake/scripts/expand_requirements.cmake:107 (include)
||  /opt/esp-idf/tools/cmake/scripts/expand_requirements.cmake:217 (expand_component_requirements)
||
||
||CMake Error at /opt/esp-idf/tools/cmake/idf_functions.cmake:338 (message):
||  Failed to expand component requirements
||Call Stack (most recent call first):
||  /opt/esp-idf/tools/cmake/project.cmake:173 (idf_import_components)
||  CMakeLists.txt:3 (project)
```

Are you running the newer version?

Also, `/subprojects/esp32/__CMake_build` is the build directory generated by CMake itself and (mostly) unaffected by meson. Meson generates it's own `build.ninja` from the CMake introspection data (+ other stuff but this is a different story) and never interacts with the generated build artifacts from CMake.

**Comment by Michael-Densberger** [comment] 2020-04-11 20:37
Yes, I'll push a version that works with the AUR package, sorry about that. Will update you.

**Comment by Michael-Densberger** [comment] 2020-04-11 21:06
Okay run a git pull and try now. The monitor target is not present in this version and has been removed. The `flash_from_cmake_root` target should build the libraries and executable and fail when /dev/ttyUSB0 is not found (or maybe you have an ESP32).

**Comment by Michael-Densberger** [comment] 2020-04-11 21:11
Interesting note, I think Meson gets confused during the introspection of `__CMake_build` about how to order headers.
The esp-idf toolchain has a scheme where there are base header files replaced or `#include_next`'d by controller specific header files. 

I noticed that when I was trying to build an link an executable to the cmake targets, I would get different behavior that I traced back to a difference in how meson was ordering the `-I/some/dir` statements. Sometimes it would get them in the right order, sometimes it wouldn't resulting in errors that would say some class or struct method isn't present because the wrong header file was found first.

**Comment by mensinda** [comment] 2020-04-12 09:28
Should be fixed with #6961. However, there seems to be another issue with a custom target.

**Comment by mensinda** [comment] 2020-04-12 13:24
Also, you need #6963 for the custom targets.

**Closed** 2020-04-12 16:39 UTC
Labels: cmake, subprojects/wraps

**Comment by mensinda** [comment] 2020-04-12 20:17
Some bad news: I am not sure if I will be able to get your project to work. This is because I have to parse this lovely CMake generator expression in meson to get some `add_custom_command`s to work: `$<JOIN:$<TARGET_PROPERTY:ldgen,FRAGMENT_FILES>,\t>`
