### ISSUE TITLE
has_header doesn't return a bool on 0.52.0

### ISSUE THREAD

**Issue by emersion** [mesonbuild/meson#6010] opened 2019-10-08 14:17 UTC
With a Meson file containing the following:

```meson
if not cc.has_header('libavutil/hwcontext_drm.h', dependencies: libavutil)
	libavutil = disabler()
endif
```

Meson fails with "ERROR: Argument to "not" is not a boolean" when `libavutil` is not found (it's optional).

Downstream issue: https://github.com/swaywm/wlroots/issues/1846

CI run with the failure: https://builds.sr.ht/~sircmpwn/job/94938#task-wlroots

CI run without the failure, Meson 0.51.2: https://builds.sr.ht/~sircmpwn/job/94937#task-wlroots

**Comment by xclaesse** [comment] 2019-10-08 14:50
This seems to happen only when one of the dependencies is a disabler(). The minimal test case is

```meson
if not disabler()
endif
```

**Comment by xclaesse** [comment] 2019-10-08 15:14
> `disabler()` returns a dependency object, not a bool. However `cc.has_header()` returns a bool. So I don't think the `if not disabler()` case is related to this issue.

disabler() is a special beast. Any statement that contains a disabler object return a disabler. So `has_header('foo.h', dependencies : disabler())` returns a disaber().

**Comment by xclaesse** [comment] 2019-10-08 15:15
@emersion please give a try to https://github.com/mesonbuild/meson/pull/6011

**Comment by xclaesse** [comment] 2019-10-08 15:54
@emersion I was currious how you're using disabler. 

https://github.com/swaywm/wlroots/blob/master/examples/meson.build
- https://github.com/mesonbuild/meson/pull/3386 has been merged, you can remove the hack
- You don't need `all_dep_found` at all, disabler() is made exactly for that case, unlike a not-found dependency, if you pass at least one disabler() to executable() then the whole executable function call is skipped. Not need of a if-block there.

**Comment by xclaesse** [comment] 2019-10-08 16:21
@emersion I think I understood why it is a regression you're seeing. The problem is there:
https://github.com/swaywm/wlroots/blob/master/examples/meson.build#L19

set_variable('foo', disabler()) used to skip the set_variable() function call instead of actually setting the variable. That means that your dep variables where still not-found dependencies instead of disabler objects.

**Comment by emersion** [comment] 2019-10-08 16:43
Thanks for the tips!

>set_variable('foo', disabler()) used to skip the set_variable() function call instead of actually setting the variable. That means that your dep variables where still not-found dependencies instead of disabler objects.

Ah, indeed, that makes sense. And the `if all_dep_found` would handle that case later on.

**Closed** 2019-10-09 21:47 UTC
