### ISSUE TITLE
py_installation.dependency() doesn't work with version karg

### ISSUE THREAD

**Issue by yashi** [mesonbuild/meson#9504] opened 2021-10-30 21:39 UTC
**Describe the bug**
The doc for `py_installation.dependency()` states that
> This method accepts no positional arguments, and the same keyword arguments as the standard dependency() function.

But `version` karg doesn't seem to work.

**To Reproduce**
Here is a `meson.build`.

```meson
project('tt', 'c')
py = import('python').find_installation('python3')
pydep = py.dependency(version : '>=3.99', required : true)
if pydep.found()
  message('ok')
  message(pydep.version())
  message(py.language_version())
endif
dependency('python3', version : '>=3.99', required : true)
```

This prints 'ok' but failed at the last `dependency()`.

**Expected behavior**

`py.dependency()` to fail when requirements doesn't meet.

[An example](https://github.com/mesonbuild/meson/blob/master/test%20cases/python3/2%20extmodule/meson.build) checks the version manually, so this might be know not to work?

**system parameters**
* This is plain native build
* Debian GNU Linux Unstable
* Python 3.9
* Meson 0.60.0
* Ninja 1.10.1

**Comment by eli-schwartz** [comment] 2021-10-31 01:06
Duplicate of #6792

**Closed by eli-schwartz** 2021-10-31 01:06 UTC
