### ISSUE TITLE
test setup: dependency for test target

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2418] opened 2017-10-03 14:26 UTC
Hi, I need to run a test setup script (or some code) before the tests can be run. This has to move a bunch of test data files into the build directory and set up a test environment. How can I do this in a good way? `run_target` was the obvious first try (with a shell script), but I was unable to add this as a dependency for the tests. Then I tried a `custom_target`, and add this as a `link_depends` for the test(exectuable()) - but this causes the test setup to be run just when tests are compiling - and I don't want to run this unless I am actually running the tests.

Also, is it possible to avoid having the tests build by default. Passing `build_by_default : false` to the test(executable()) did not work.

```
## Tests
test_setup = custom_target ('test_setup',
    command : [ find_program('tests/test_setup.sh').path(), '@INPUT@', '@OUTPUT@' ],
    input : 'tests',
    output : 'tests',
    install : false)

test_env = environment ()
test_env.set ('NOTMUCH_CONFIG', join_paths(meson.build_root (), 'tests', 'mail', 'test_config'))

src_o = astroid_exe.extract_objects (src)

boost_test = dependency ('boost', modules : [ 'unit_test_framework' ])
test_deps = deps
test_deps += boost_test

tests = [ [ 'generic test',   'test_generic', [ 'tests/test_generic.cc' ]],
          [ 'compose testing', 'test_composed_message',  [ 'tests/test_composed_message.cc' ]]
        ]

foreach t : tests
  test (t[0],
      executable (t[1], t[2], objects : src_o, include_directories : include_directories ('src'), dependencies : test_deps, link_depends : test_setup, build_by_default : false),
      env : test_env, workdir : meson.build_root())
endforeach
```

Full [meson.build](https://github.com/gauteh/astroid/blob/22f5d95ae5dadd6fc5a79efa4f97bfd8393e09b8/meson.build).

**Comment by db0451** [comment] 2017-10-27 20:45
> Also, is it possible to avoid having the tests build by default. Passing build_by_default : false to the test(executable()) did not work.

This also does not seem to work for me (with the result of executable() stored in a variable); the test executables are always built. This is a real pain if I'm testing new code in src/, or a new feature that doesn't have a formal test yet, or I simply decide I don't care about the test results and just want to build the core.

**Comment by nirbheek** [comment] 2017-12-12 18:44
Duplicate of https://github.com/mesonbuild/meson/issues/1704

**Closed by nirbheek** 2017-12-12 18:44 UTC
Labels: support

**Comment by stalkerg** [comment] 2020-06-23 22:30
@nirbheek I suppose it's a separate issue. Here we need something to prepare tests (run script, with some DB for example) and some action to stop tests (stop and clean DB for example). 
In #1704 you mostly talking about a separate run for tests. 

Of course, we can run some bash/bat script to do it but in that case semantic will not so clear for developers.
