### ISSUE TITLE
IndexError when running `meson configure` in source directory (meson 0.50.1)

### ISSUE THREAD

**Issue by 1ace** [mesonbuild/meson#5375] opened 2019-05-09 12:07 UTC
Running `meson configure` in [Mesa's source directory](https://gitlab.freedesktop.org/mesa/mesa) (at Mesa commit 8b3baa274406e9bcde42 in case the issue disappears later) crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mconf.py", line 200, in run
    c = Conf(builddir)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mconf.py", line 56, in __init__
    intr.analyze()
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/introspection.py", line 274, in analyze
    self.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 149, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 149, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 217, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 446, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 217, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 149, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 438, in evaluate_statement
    return self.assignment(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/interpreter.py", line 229, in assignment
    self.assign_vals[node.var_name] = [self.evaluate_statement(node.value)] # Evaluate the value just in case
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/introspection.py", line 234, in func_shared_lib
    return self.build_target(node, args, kwargs, SharedLibrary)
  File "/usr/lib/python3.7/site-packages/mesonbuild/ast/introspection.py", line 188, in build_target
    elemetary_nodes.pop(0)
IndexError: pop from empty list
```

**Comment by dcbaker** [comment] 2019-05-09 16:58
This is duplicate of  #5286, and should be fixed in master.

**Closed by dcbaker** 2019-05-09 16:58 UTC
