### ISSUE TITLE
Backslashes are converted to slashes in custom_target ?

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2705] opened 2017-11-29 11:36 UTC
I'm trying to use `sed` in a custom_target.
```
default_edl = custom_target('default.edl.inc',
  input : 'default.edl',
  output: 'default.edl.inc',
  command: [
    'sed', 's_\\_\\\\_g;s_\r_a_;s_"_\\"_g;s_^_"_;s_$$_\\n"_',
    '@INPUT@',
  ],
  capture: true
)
```
Should be read : '\\' will be replaced by '\\\\', etc.
`sed` was throwing back at me:
`sed: -e expression #1, char 40: unterminated 's' command`

After a bit of debugging with strace (because Meson does not show the custom_target commands, even with `ninja -v`), I find that:
```
execve("/usr/bin/sed", ["sed", "s_/_//_g;s_/r_a_;s_\"_/\"_g;s_^_\"_;s/$$/\n\"/", "../gcut/default.edl"], 0x555555a24c00 /* 66 vars */) = 0
```
Sooo… My backslashes were replaced with slashes ? That's not good. It may be due to some Windows/Linux paths portability stuff ?

**Comment by nirbheek** [comment] 2017-11-29 11:55
Duplicate of https://github.com/mesonbuild/meson/issues/1564.

**Closed by nirbheek** 2017-11-29 11:55 UTC

**Comment by Salamandar** [comment] 2017-11-29 12:57
Crap, I searched the keyword "backslash" in issues, but not "back-slash".
