### ISSUE TITLE
Dependency Cache Regression from 0.58.2 to 0.59.0

### ISSUE THREAD

**Issue by nosracd** [mesonbuild/meson#9036] opened 2021-07-27 17:27 UTC
**Describe the bug**
In version `0.59.0` `dependency` results are cached improperly. On a clean `meson build` it passes with no errors. On a reconfigure, the configure fails.

**To Reproduce**
On Ubuntu, have the `googletest` package installed but not `libgtest-dev` (`googletest` gets installed when `libgtest-dev` in installed but does not automatically get removed when `libgtest-dev` is removed).

Using the following `meson.build`:
```
project('foo', 'cpp')

gtest_dep = dependency('gtest', version: '>=1.8.0')
```

with the following wrap file at `subprojects/gtest.wrap`:
```
[wrap-file]
directory = googletest-release-1.10.0

source_url = https://github.com/google/googletest/archive/release-1.10.0.zip
source_filename = gtest-1.10.0.zip
source_hash = 94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91

patch_url = https://wrapdb.mesonbuild.com/v1/projects/gtest/1.10.0/1/get_zip
patch_filename = gtest-1.10.0-1-wrap.zip
patch_hash = 04ff14e8880e4e465f6260221e9dfd56fea6bc7cce4c4aff0dc528e4a2c8f514
```

Then configure a build directory using 
```
meson build
```
Then reconfigure using
```
meson build --reconfigure
```

**Expected behavior**
Using `0.58.2` results in expected behavior where `meson build` and `meson build --reconfigure` yield the same result. 

`meson build` results in
```
Dependency gtest found: NO unknown version, but need: ['>=1.8.0']
Run-time dependency GTest found: YES (building self)
```
and `meson build --reconfigure` results in the same output:
```
Dependency gtest found: NO unknown version, but need: ['>=1.8.0']
Run-time dependency GTest found: YES (building self)
```

**Actual behavior**
On `0.59.0`, the first `meson build` results in:
```
Dependency gtest found: NO unknown version, but need: ['>=1.8.0']
Run-time dependency GTest found: YES (building self)
```
but the `meson build --reconfigure` results in
```
Dependency gtest found: NO found unknown but need: '>=1.8.0' (cached)

meson.build:3:0: ERROR: Dependency 'gtest' is required but not found.
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
    * This is a plain bare-metal build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    * Ubuntu 20.04
* what Python version are you using e.g. 3.8.0
    * Python 3.8.10
* what `meson --version`
    * `0.59.0`
* what `ninja --version` if it's a Ninja build
    * N/A

**Comment by dcbaker** [comment] 2021-07-27 18:24
@xclaesse what is the right behavior here (since you know the most about fallbacks I think)? Should we put the fallback in the dependency cache?

**Comment by xclaesse** [comment] 2021-08-02 14:47
Hmm, IIRC it is not supposed to cache not-found dependencies. Probably my fault, I'll check that.

**Comment by xclaesse** [comment] 2021-08-02 15:15
Hmm, I can't reproduce this, it never goes into the case `Run-time dependency GTest found: YES (building self)` because `gtest` library is not part of googletest package, at least on ubuntu 20.04.

**Comment by xclaesse** [comment] 2021-08-02 15:24
nevermind, I could reproduce now. That seems to be an issue in DependencyFactory rather than DependencyFallbacksHolder.

**Comment by xclaesse** [comment] 2021-08-02 15:37
@eli-schwartz @dcbaker actually I don't understand how gtest dependecy can be found in the first place. GTestDependencySystem does not specify which version it is compiling from source, so ExternalDependency._check_version() should always make it fail, even on the first configure.

**Comment by xclaesse** [comment] 2021-08-02 15:39
The problem I see is on initial configure, GTestDependencySystem's version is not checked for some reason so it is accepted as found and gets into the cache. On a reconfigure `DependencyFallbacksHolder._get_cached_dep` find it in the cache and does a proper version check that fails.

**Comment by xclaesse** [comment] 2021-08-02 16:09
Ok, cracked the problem. It is _check_version() that is supposed to set `self.is_found = True` only if it passed the version check. But GTestDependencySystem sets it to True regardless. Also _check_version() only raise DependencyException only if self.required, but DependencyFallbacksHolder now sets self.required=False because it has a fallback subproject, so finding on the system is not required. That means in find_external_dependency() we have d.is_found is True, d.required is False so d._check_version() sees that version does not match but won't raise exception, so we end into the try's else case that accepts that dependency and return it.

The expected behaviour:
- On initial configure the version check fails and subproject is used.
- On reconfigure subproject is still used.
- If you remove `version: '>=1.8.0'` then it won't use the subproject.

**Comment by xclaesse** [comment] 2021-08-02 16:23
@nosracd This should be fixed with https://github.com/mesonbuild/meson/pull/9056.

**Closed** 2021-08-02 21:16 UTC
Labels: dependencies, regression
