### ISSUE TITLE
`meson -Dprefix=/some/prefix /src/path /build/path` does not work

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#2127] opened 2017-07-26 22:07 UTC
> meson --help

lists the -D option:

>   -D option             Set the value of an option, can be used several times
>                              to set multiple options.

But it does not work with -Dprefix=. I saw that there is a --prefix common option as well so I use this and it works. But -Dprefix= works in mesonconf for instance. It would make sense it could work for meson as well (being a synonym to --prefix).

**Comment by TingPing** [comment] 2017-08-04 18:01
Duplicate of #969

**Closed by TingPing** 2017-08-04 18:01 UTC
Labels: bug, easy
