### ISSUE TITLE
"Edit on github" link on documentation leads to 404

### ISSUE THREAD

**Issue by detly** [mesonbuild/meson#7462] opened 2020-07-17 00:32 UTC
The [online documentation](https://mesonbuild.com/index.html) has a link in the top right that says "Edit on github". When I click on the link, I get a 404 page eg. for the front page the URL is `https://github.com/mesonbuild/meson//edit/master/docs/builddir/markdown/index.md`, and this just shows the Github 404 page.

I would expect that if the link is visible, it works; if it's not a desired feature it should be switched off.

**Comment by eli-schwartz** [comment] 2021-02-21 16:51
Duplicate of #8061

**Closed by eli-schwartz** 2021-02-21 16:51 UTC
Labels: documentation
