### ISSUE TITLE
meson-0.38.0 dies with a traceback if you specify an absolute path for --bindir, --sbindir, --libdir or --libexecdir

### ISSUE THREAD

**Issue by williamh** [mesonbuild/meson#1345] opened 2017-01-31 00:35 UTC
Create a small hello.c project, and do this:

$ cd /my/project/path
$ mkdir build
$ meson --bindir /bin build

That should give you the traceback. If it doesn't, let me know and I'll attempt to paste one into the bug.
This happens for --bindir, --libdir, --libexecdir and --sbindir at least, I haven't tested the other options.

**Comment by nirbheek** [comment] 2017-01-31 00:47
Are you running Python 3.4.x? If so, it's because of https://github.com/mesonbuild/meson/pull/1342.

**Comment by williamh** [comment] 2017-01-31 03:00
Yes, Gentoo has python-3.4.x stable, but I don't know any time table for 
stabilizing python 3.5.

**Comment by nirbheek** [comment] 2017-01-31 03:00
That won't be a problem, we'll be releasing 0.38.1 in a week with bugfixes including that one.

**Comment by nirbheek** [comment] 2017-01-31 03:01
Going to close this as a duplicate of #1341. Cheers!

**Closed by nirbheek** 2017-01-31 03:01 UTC
