### ISSUE TITLE
Using Bazel

### ISSUE THREAD

**Issue by AnonymousRonin** [mesonbuild/meson#12474] opened 2023-11-05 00:19 UTC
Is it possible to use bazel to build projects in mesa?  Meson is so insufferable, invoke project but its' not a project so on and so on.  It's overlly complicated for what it's tasked to do.  It's not as bad as cmake  but the simplicity of bazel makes things quick and smooth.

**Comment by eli-schwartz** [comment] 2023-11-05 02:17
> Is it possible to use bazel to build projects in mesa?

If you delete all the meson.build files and replace them with bazel files written from scratch, yes.

> Meson is so insufferable, invoke project but its' not a project so on and so on. It's overlly complicated for what it's tasked to do.

If you run meson from the wrong directory, and it cannot find a project to build, then it cannot build it. Check out the documentation for the project you are trying to build -- they will usually tell you what to do. If in doubt, try running from the root of the git repository or extracted tarball.

**Comment by eli-schwartz** [comment] 2023-11-05 02:18
Duplicate of #12441

**Closed by eli-schwartz** 2023-11-05 02:18 UTC
