### ISSUE TITLE
configure_file cant output to a subdirectory

### ISSUE THREAD

**Issue by Apache-HB** [mesonbuild/meson#8595] opened 2021-03-28 16:55 UTC
`configure_file` currently cant `output` to a subdirectory.

```py
configure_file(
    input : 'header.h.in',
    output : 'subdir/header.h',
    configuration : data
)
```

currently produces `ERROR: Output file name must not contain a subdirectory.`
Could this restriction be relaxed to allow `configure_file` to create the subdirectories if needed?

**Comment by tristan957** [comment] 2021-04-06 17:05
This is a symptom of a larger issue with Meson. There is an issue that already tracks this somewhere, so this should be closed. Your best bet is to not use a subdir :). I hate this behavior too...

**Comment by eli-schwartz** [comment] 2021-04-07 00:09
Duplicate of #2320

**Closed by eli-schwartz** 2021-04-07 00:09 UTC
