### ISSUE TITLE
Regression when passing custom target as input file to gnome.compile_resources

### ISSUE THREAD

**Issue by ptomato** [mesonbuild/meson#10367] opened 2022-05-08 06:15 UTC
**Describe the bug**
Sometime between Meson 0.59 and 0.61, passing a custom target as the XML file to gnome.compile_resources broke. It was probably sketchy to do that in the first place, so it wouldn't be so bad, except that there no longer seems to be an obvious way to achieve the same thing.
(This bug is kind of the reverse of #5017.)

**To Reproduce**
```meson
project('example', 'c')
gnome = import('gnome')
generated_gresource_xml = custom_target('generated-gresource-xml',
    output: 'my.gresource.xml', capture: true,
    command: ['echo', '<?xml version="1.0" encoding="UTF-8"?><gresources/>'])
resources_generated = gnome.compile_resources('resources-generated',
    generated_gresource_xml)
```
This logs the following error:
> ../meson.build:6:0: ERROR: gnome.compile_resources argument 2 was of type "CustomTarget" but should have been one of: "str", "File"

I've tried to work around it by using the custom target's `full_path()` and adding the custom target to the dependencies keyword arg. (i.e., `gnome.compile_resources('resources-generated', generated_gresource_xml.full_path(), dependencies: generated_gresource_xml)`) This logs the following error:
> ninja: error: '/var/home/ptomato/workspace/scratch/res/_build/my.gresource.xml', needed by 'resources-generated.c', missing and no known rule to make it

So despite it being included in `dependencies`, it's not made first. However, if you ask for it specifically with `ninja my.gresource.xml`, it does get built.

**Expected behavior**
On running the build, `my.gresource.xml` should first be generated, then subsequently used as input for the `compile_resources` call. This worked correctly under 0.59.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native build
* what operating system? Fedora Silverblue 35, Meson installed via `pip3 install --user`
* what Python version are you using? 3.10.2
* what `meson --version`? 0.61.0
* what `ninja --version` if it's a Ninja build? 1.10.2

**Comment by ptomato** [comment] 2022-05-08 06:21
(Although I guess it can be worked around after all, using `configure_file()` with a bogus `input` argument instead of `custom_target()`)

**Comment by hughsie** [comment] 2022-06-17 16:16
I have exactly the same problem in fwupd, I'm doing something like this as a workaround:

	fwupd_gresource_xml = custom_target('fwupd-resources-xml',
	  input : [
	    'org.freedesktop.fwupd.xml',
	  ],
	  output : 'fwupd.gresource.xml',
	  command : [
	    join_paths(meson.project_source_root(), 'contrib', 'generate-gresource-xml.py'), '@OUTPUT@', '@INPUT@',
	  ],
	)
	resources_src = gnome.compile_resources(
	  'fwupd-resources',
	  join_paths(meson.current_build_dir(), 'fwupd.gresource.xml'),
	  dependencies: fwupd_gresource_xml,
	  source_dir: '.',
	  c_name: 'fu'
	)

when what I want to be doing is...

	fwupd_gresource_xml = custom_target('fwupd-resources-xml',
	  input : [
	    'org.freedesktop.fwupd.xml',
	  ],
	  output : 'fwupd.gresource.xml',
	  command : [
	    join_paths(meson.project_source_root(), 'contrib', 'generate-gresource-xml.py'), '@OUTPUT@', '@INPUT@',
	  ],
	)
	resources_src = gnome.compile_resources(
	  'fwupd-resources',
	  fwupd_gresource_xml,
	  source_dir: '.',
	  c_name: 'fu'
	)

**Comment by hughsie** [comment] 2022-06-17 16:17
Doing the latter I get:

    meson.build: ERROR: gnome.compile_resources argument 2 was of type "CustomTarget" but should have been one of: "str", "File"

**Comment by eli-schwartz** [comment] 2022-06-17 16:59
I submitted a PR to fix this. It's a regression in the typed_pos_args update, this should not have been disallowed.

@hughsie

I don't see that in the fwupd repo, so this confuses me a bit. It seems you have had it checked into git since 2015?

**Comment by eli-schwartz** [comment] 2022-06-17 17:00
> It was probably sketchy to do that in the first place

Maybe. On the other hand, it explicitly used to work.

I am surprised that it was only noticed 4 months after it initially got dropped.

It's not entirely clear to me what the benefits of generating it are, vs. checking it into git.

**Comment by hughsie** [comment] 2022-06-17 17:02
> I don't see that in the fwupd repo

See the wip/hughsie/gresource-quirks2 branch.

**Comment by dcbaker** [comment] 2022-06-17 17:11
I have a patch, I'll send it out shortly

**Closed** 2022-06-19 14:39 UTC
