### ISSUE TITLE
404 link in the documentation

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#8078] opened 2020-12-07 20:21 UTC
In the [documentation](https://mesonbuild.com/) there is a butten saying "Edit on Github" that has a broken link  to https://github.com/mesonbuild/meson//edit/master/docs/builddir/markdown/index.md

Slightly OT: Consider using an automated 404 checker.

**Comment by eli-schwartz** [comment] 2020-12-07 21:06
Duplicate of #8061

**Closed by eli-schwartz** 2020-12-07 21:06 UTC
