### ISSUE TITLE
test() implies build_by_default?

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#13378] opened 2024-07-02 09:17 UTC
**Describe the bug**

If I use an executable in a test() it gets built by default, even when build_by_default is set to false for the executable.

**To Reproduce**

meson.build
```
project('test', 'cpp') 
exe = executable('exe', 'main.cpp', build_by_default: false)
test('Test', exe)
```

with minimal main.cpp
```
int main() {
    return 0;
}
```

**Expected behavior**

If I'm running `meson compile`, I expect this executable to not be built (compiling and linking).
If I'm running `meson test`, I expect this executable to be built (compiling and linking) for the test.

**system parameters**

* OS: Linux
* Python: 3.11.9
* Meson: 1.4.1
* Ninja: 1.12.1

**Comment by QuLogic** [comment] 2024-07-02 22:18
This is a duplicate of #2518.

**Closed by QuLogic** 2024-07-02 22:18 UTC
