### ISSUE TITLE
tests compiled even when build_by_default is false

### ISSUE THREAD

**Issue by mqudsi** [mesonbuild/meson#3662] opened 2018-06-01 22:56 UTC
I'm not sure if this is by design, but there doesn't seem to be a way to suppress tests from being compiled by default (vs only when the test target is built/run).

```python
exe1 = executable('test1, ['test1.cpp'], build_by_default: false)
test('test1', exe1)
```

`ninja` here compiles test1 unconditionally. I would expect it to only be compiled when `ninja test` is run.

**Comment by nirbheek** [comment] 2018-06-06 07:37
There is a FIXME in the codebase about changing this. See: `mesonbuild/backends/backends.py` : `get_build_by_default_targets()`. Would you like to work on fixing it?

**Comment by QuLogic** [comment] 2019-08-06 00:37
This is a duplicate of #2518.

**Comment by eli-schwartz** [comment] 2022-01-13 03:50
Duplicate of #2518

**Closed by eli-schwartz** 2022-01-13 03:50 UTC
Labels: bug, help wanted, good first issue, test targets
