### ISSUE TITLE
0.50 regression: Default option c_std not applied when cross-compiling

### ISSUE THREAD

**Issue by lgrahl** [mesonbuild/meson#5097] opened 2019-03-17 16:52 UTC
When providing `default_options: ['c_std=c99']` to the `project`, it is not being applied on `meson build --cross-file <cross-file>` invocation on a simple test project using flexible array members:

`ninja -v`

> [1/2] cc -Itest-executable@exe -I. -I../../work -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pedantic -MD -MQ 'test-executable@exe/main.c.o' -MF 'test-executable@exe/main.c.o.d' -o 'test-executable@exe/main.c.o' -c ../../work/main.c
../../work/main.c:5:9: warning: ISO C90 does not support flexible array members [-Wpedantic]
     int array[];
         ^
[2/2] cc  -o test-executable 'test-executable@exe/main.c.o' -Wl,--no-undefined -Wl,--as-needed

However, after doing any kind of (even unrelated) configuration such as `meson configure -Db_asneeded=true`, the configuration is being fixed and applies as expected:

`ninja -v`

> [1/2] cc -Itest-executable@exe -I. -I../../work -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch **-std=c99** -g -pedantic -MD -MQ 'test-executable@exe/main.c.o' -MF 'test-executable@exe/main.c.o.d' -o 'test-executable@exe/main.c.o' -c ../../work/main.c
[2/2] cc  -o test-executable 'test-executable@exe/main.c.o' -Wl,--no-undefined -Wl,--as-needed

Note: I haven't tested whether this also applies to other default options.

---

#### main.c

```c
#include <stdio.h>

struct a {
    int foo;
    int array[];
};

int main(int argc, char* argv[]) {
    printf("Hey!\n");
    return 0;
}
```

#### meson.build

```meson
project('test-project', 'c', version: '0.0.1', default_options: ['c_std=c99'])
add_project_arguments('-pedantic', language: 'c')
executable('test-executable', 'main.c')
```

#### cross-file

```
[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
root = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64'
needs_exe_wrapper = true

[paths]
prefix = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot'

[binaries]
c = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang'
cpp = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang++'
ar = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar'
as = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-as'
ld = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld'
strip = '/usr/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-strip'
pkgconfig = '/usr/bin/pkg-config'
```

**Comment by lgrahl** [comment] 2019-03-17 17:59
What's also weird is that it's trying to use native `cc` to compile instead of using the cross-compiler. I've opened a new issue for that (#5102). However, the above described issue also happens when cross-compiling for ARM (using the appropriate cross-compiler).

**Comment by mgautierfr** [comment] 2019-03-18 16:58
I have the same issue. (with cpp_std).
This is a regression with `0.50.0`. `0.49.2` correctly pass the option (`-std=c++11` in my case) to the compiler.

It seems also that meson doesn't append `LDFLAGS` and `CPPFLAGS` from environment for c and cpp compiler. (Also a regression, 0.49.2 works)

**Comment by lgrahl** [comment] 2019-03-18 20:59
I can confirm that it works with 0.49.2

**Comment by michaelolbrich** [comment] 2019-03-20 07:50
I'm seeing the same thing here. The fist broken commit is 19f81d3e33c70c9c902dabaad732e5d33bf05bd4.

**Comment by nirbheek** [comment] 2019-03-20 08:04
CCing @Ericson2314

**Comment by Ericson2314** [comment] 2019-03-20 15:23
Hmm so this option affected native and cross compilation previously? That is fine, but inconsistent with the other options. I'll take a look.

**Comment by michaelolbrich** [comment] 2019-03-20 15:47
I'm not sure what you think should happen but systemd, mesa and libdrm set `c_std` in the `default_options` and with the current meson release the all fail to cross-compile with a compiler that uses an older standard by default.

**Comment by Ericson2314** [comment] 2019-03-20 15:52
@michaelolbrich for comparison what does `c_args` or `c_link_args` do in `default_options`, and what do all 3 do as `-D` cli args to meson?

(I'm in transit so can't check yet. Not just asking rhetorically :). )

**Comment by michaelolbrich** [comment] 2019-03-20 17:35
As soon as I use `--cross-file`, `c_args` `c_link_args` and `c_std` are all ignored. For `default_options` and as `-D` cli args.

**Comment by Ericson2314** [comment] 2019-03-20 18:49
@michaelolbrich Thanks! That is the new behavior?

**Comment by michaelolbrich** [comment] 2019-03-20 19:41
For `c_std` that's new. For `c_args` and `c_link_args` this was also the case in `0.49.0`.

I'm not sure what `c_args` is supposed to be used for but the correct C standard depends on the code that is compiled. Cross-compiling or not should not have an effect for this.

And after doing some testing, I must say that it is very confusing that command line options don't have any effect.

**Comment by Ericson2314** [comment] 2019-03-21 01:14
Yes it is confusing. So the regession was due to me trying to match the status quo in a pure refactor, but not realizing `c_std` worked differently. What I actually want is http://github.com/mesonbuild/meson/issues/4963 . This would solve your issue completely in that `default_options` works reliably whether or not the user is cross or native compiling.

**Comment by Ericson2314** [comment] 2019-03-29 20:17
Could somebody assign this to me?

**Comment by jpakkane** [comment] 2019-04-11 21:13
I debugged why this happens. In `get_compiler_options_for_target` an `OverrideProxy` is created and it overrides `c_std` to be `none`. It should not do that since `c_std` is not a per-machine setting. It should be the same for native and cross compilation (at least for now to preserve backwards compatibility).

Maybe once we get `cross_c_args` et al we could also have a `cross_c_std`, but I'm not sure even that is necessary.

**Comment by Ericson2314** [comment] 2019-04-12 15:35
@jpakkane So right now all compiler options are per-machine, since compilers target a single machine (as far as meson knows). The solution I think is when reading in the file to make a temporary hack to duplicate this one. 

> Maybe once we get cross_c_args et al we could also have a cross_c_std, but I'm not sure even that is necessary.

I have done GCC native, Clang cross builds where the clang might support a newer standard.

**Closed** 2019-06-06 16:19 UTC
