### ISSUE TITLE
[RFC] normalize build file and option file name

### ISSUE THREAD

**Issue by pynixwang** [mesonbuild/meson#6951] opened 2020-04-11 14:17 UTC
meson.build            -> build.meson
meson_options.txt ->options.meson

unified file extension

**Comment by pynixwang** [comment] 2020-04-11 14:31
meson developer is very "free" for naming.

**Comment by eligt** [comment] 2020-06-13 16:54
I strongly agree with this convention. File extensions are used in many places to determine a file's purpose, including for instance automatic syntax highlighting in editors. The ".build" extension is already abused while ".meson" is unique enough to be uniquely associated to the Meson build system.

**Comment by bruchar1** [comment] 2023-02-26 03:28
Related to #11179

**Comment by eli-schwartz** [comment] 2023-02-26 05:59
Duplicate of #11176

**Closed by eli-schwartz** 2023-02-26 05:59 UTC
