### ISSUE TITLE
meson bails at first dependency failure

### ISSUE THREAD

**Issue by ferdnyc** [mesonbuild/meson#4456] opened 2018-10-31 16:29 UTC
Apologies if this is already reported, a few searches on likely keywords didn't turn anything up.

meson takes the same frustrating approach to dependency-checking as autotools: it bails at the _first_ hint of a failed dependency. This leads to tedious and frustrating cycles like the one I just went through attempting to build `gnome-music`:

```console
$ cd gnome-music; meson _build
The Meson build system
Version: 0.47.2
Source dir: /home/ferd/rpmbuild/REPOS/gnome-music
Build dir: /home/ferd/rpmbuild/REPOS/gnome-music/_build
Build type: native build
Project name: gnome-music
Project version: 3.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)

meson.build:36:0: ERROR:  Native dependency 'goa-1.0' not found

A full log can be found at /home/ferd/rpmbuild/REPOS/gnome-music/_build/meson-logs/meson-log.txt

$ sudo dnf install gnome-online-accounts-devel
[...]
$ meson _build
The Meson build system
Version: 0.47.2
Source dir: /home/ferd/rpmbuild/REPOS/gnome-music
Build dir: /home/ferd/rpmbuild/REPOS/gnome-music/_build
Build type: native build
Project name: gnome-music
Project version: 3.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency goa-1.0 found: YES 3.28.0
Native dependency gobject-introspection-1.0 found: YES 1.56.1
Native dependency gtk+-3.0 found: YES 3.22.30

meson.build:39:0: ERROR:  Native dependency 'libdazzle-1.0' not found

A full log can be found at /home/ferd/rpmbuild/REPOS/gnome-music/_build/meson-logs/meson-log.txt

$ sudo dnf install libdazzle-devel
[...]
$ meson _build
The Meson build system
Version: 0.47.2
Source dir: /home/ferd/rpmbuild/REPOS/gnome-music
Build dir: /home/ferd/rpmbuild/REPOS/gnome-music/_build
Build type: native build
Project name: gnome-music
Project version: 3.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency goa-1.0 found: YES 3.28.0
Native dependency gobject-introspection-1.0 found: YES 1.56.1
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency libdazzle-1.0 found: YES 3.28.5

meson.build:40:0: ERROR:  Native dependency 'libmediaart-2.0' not found

A full log can be found at /home/ferd/rpmbuild/REPOS/gnome-music/_build/meson-logs/meson-log.txt

$ sudo dnf install libmediaart-devel
[...]
$ meson _build
The Meson build system
Version: 0.47.2
Source dir: /home/ferd/rpmbuild/REPOS/gnome-music
Build dir: /home/ferd/rpmbuild/REPOS/gnome-music/_build
Build type: native build
Project name: gnome-music
Project version: 3.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Native dependency goa-1.0 found: YES 3.28.0
Native dependency gobject-introspection-1.0 found: YES 1.56.1
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency libdazzle-1.0 found: YES 3.28.5
Native dependency libmediaart-2.0 found: YES 1.9.4
Native dependency libsoup-2.4 found: YES 2.62.3
Native dependency tracker-sparql-2.0 found: YES 2.1.4
Native dependency pygobject-3.0 found: NO found '3.28.3' but need: '>= 3.29.1'

meson.build:43:0: ERROR:  Invalid version of dependency, need 'pygobject-3.0' ['>= 3.29.1'] found '3.28.3'.

A full log can be found at /home/ferd/rpmbuild/REPOS/gnome-music/_build/meson-logs/meson-log.txt
```

...And so on.

It'd be really nice to have a way (and apologies, again, if this exists and I just missed it) to say, "Look, just keep going on the dependency checks even if errors are encountered" so that _all_ of the failed dependencies are listed in a single run. (Within reason, obviously. If there are dependency _chains_, this may not always be feasible. But it seems like it should be **more** achievable than the current "insta-bail" approach.)

**Comment by bw98** [comment] 2020-03-02 03:08
I encountered this problem, too! it's a bit upsetting, because some of dependencies cannot find in brew ...

**Comment by nirbheek** [comment] 2020-03-02 10:31
Duplicate of https://github.com/mesonbuild/meson/issues/985

**Closed by nirbheek** 2020-03-02 10:31 UTC

**Comment by ferdnyc** [comment] 2020-03-02 11:53
So it is! Don't know how I missed that originally.

**Comment by bw98** [comment] 2020-03-04 08:18
A dumb but useful solution here: copy the name of one dependency, search on the Internet. Then, download tar.gz or rpm, finally configure and make it in source code way. But it's so dumb, I still wait for other more suitable solutions, please tell me if you know ...
