### ISSUE TITLE
Meson does not detect wrap file changes

### ISSUE THREAD

**Issue by apache-hb** [mesonbuild/meson#12524] opened 2023-11-19 01:33 UTC
**Describe the bug**
After configuring a build using a wrap file, changing the wrap file does not cause a rerun of meson to apply the new wrap

**To Reproduce**
Create a meson project that uses a wrapfile, build the project, then change the wrap file contents and rebuild the project.

**Expected behavior**
Meson detects the wrapfile has changed and configures the build with the new wrap.

**system parameters**
meson 1.2.3
ninja 1.8.9
windows 11 build 22621
python 3.11

**Comment by mitchgrout** [comment] 2023-11-19 07:22
I can see reasons both for and against this behaviour. I personally find the current behaviour quite annoying when doing active development on a subproject, as the only effective way I have to clobber the pulled WIP dependency is to change the `version` to something else, or `meson subprojects purge` which is a little tedious. There's also the secondary issue of if your patch files/directory change, meson will not re-apply the patch either. I would personally be in favour of having a reconfigure performed in a wrapfile or associated patch directory changed, but there may be some costs to consider there.

**Comment by apache-hb** [comment] 2023-11-19 20:19
As the sources of every subproject are already tracked by meson I cant see tracking the wrapfile, diff_files, source_filename, etc. being a massive overhead. although tracking all of a `patch_directory` contents may prove costly on some systems depending on if ninja can track a folders last modified time or not.

**Comment by eli-schwartz** [comment] 2023-11-26 04:57
Duplicate of #10348

**Closed by eli-schwartz** 2023-11-26 04:57 UTC

**Comment by eli-schwartz** [comment] 2023-11-26 05:01
> I would personally be in favour of having a reconfigure performed in a wrapfile or associated patch directory changed, but there may be some costs to consider there.

Note that in that ticket we already discussed a pretty big cost: data loss.
