### ISSUE TITLE
compile_resources of Windows module regressed since 0.44

### ISSUE THREAD

**Issue by Sonderstorch** [mesonbuild/meson#3999] opened 2018-08-09 14:47 UTC
My build builds several executables in different subdirectories included in a main meson.build using 'subdir'.

Each of these sub meson.builds compiles a file named 'version.rc' using code like this:
```
  if host_machine.system() == 'windows'
    foo_sources += import('windows').compile_resources( 'src/version.rc' )
  endif
```

This works fine with meson versions up to 0.44.1. All later versions produce the error

> ERROR: Multiple producers for Ninja target "foo/version.res". Please rename your targets.

But renaming all 'version.rc' files to e.g. 'foo_version.rc' is not an option. And C++ files that carry identical names in different subdirectories aren't a problem either.

**Comment by nirbheek** [comment] 2018-08-09 14:52
What's the latest version of Meson that you have tested with?

**Comment by Sonderstorch** [comment] 2018-08-09 14:57
I tried 0.47.1 just before finally reporting the issue.

**Comment by nirbheek** [comment] 2018-08-09 15:00
So the main difference from before, is that now you should only call `compile_resources()` on a file exactly once. Can you try doing that instead of defining it multiple times? Earlier it would generate the resource file multiple times in different subdirs which is inefficient and also less flexible.

**Comment by Sonderstorch** [comment] 2018-08-09 15:11
Well, my source tree is like this:
```
    meson.build
    :
    +--exe1/
    :   :  meson.build
    :   :
    :   +--src/
    :       main.cpp
    :       version.rc
    +--exe2/
    :   :  meson.build
    :   :
    :   +--src/
    :        main.cpp
    :        version.rc
    +--exe3/
    :   :  meson.build
    :   :
    :   +--src_dll/
    :   :    main.cpp
    :   :    version.rc
    :   :
    :   +--src_exe/
    :        main.cpp
    :        version.rc
    :
```

And ASFAIK I'm calling ``compile_resources`` only once for each ``version.rc``. meson seems to pull each ``version.res`` to the top level of the build directory while it actually belongs to a subdir-build.

If I understand you correctly, it isn't possible anymore to have a structure like in ``exe3`` where two ``version.rc`` files exist in one subdir build?

**Comment by jon-turney** [comment] 2018-08-13 22:12
This looks similar (but not the same as) to #3575, which was supposed to be fixed by #3715.

**Comment by nirbheek** [comment] 2018-08-13 22:14
The error is different here because the problem seems to be:

> ERROR: Multiple producers for Ninja target "foo/version.res". Please rename your targets.

Which should be impossible if they are indeed being generated in different subdirs. Perhaps we are simply missing correct usage of `subdir` here.

**Comment by nirbheek** [comment] 2018-08-13 22:16
I guess the first step is creating a sample project that reproduces this, so it can be investigated further.

**Closed** 2018-08-20 21:56 UTC
Labels: generators, regression, windows
