### ISSUE TITLE
A request for a fallback name for meson_options.txt

### ISSUE THREAD

**Issue by ahlstromcj** [mesonbuild/meson#11176] opened 2022-12-14 15:05 UTC
This is more of a request than an issue.  Using meson_options.txt as an options file-name has two "defects" for me:

1. I use DIR_COLORS a lot, and I have a special color for build configurations, and a different color for plaintext files.  I would like to easily grok the build configurations in all my projects.
2. Usage of a text file-name for a build file is jolting.   One of the reasons I got turned off of cmake early on. Silly, I know.

Request:  Allow something like "meson.opts" as a fallback for "meson_options.txt" if the latter does not exist.

Workaround: On a UNIX, use soft links.

**Comment by xclaesse** [comment] 2022-12-14 15:24
I agree `meson_options.txt` name is not great, it has been discussed in the past. IMHO the requirement for a fallback name are:
- Starts with `meson` to be sorted together with `meson.build` file alphabetically.
- Do not already commonly used file extension like `.txt`.

My suggestion would be `meson_options.build`, to have common prefix and suffix as `meson.build`.

**Comment by dcbaker** [comment] 2022-12-14 15:43
Mine my thought was Meson.options, but I don’t care too much about the color of the bike shed

**Comment by eli-schwartz** [comment] 2023-02-26 05:58
This is basically a duplicate of #6951 but with more reasoning.

**Closed as completed** 2023-03-28 12:01 UTC
