### ISSUE TITLE
No warning/error when using named arguments

### ISSUE THREAD

**Issue by kaimast** [mesonbuild/meson#1817] opened 2017-05-18 15:49 UTC
Consider the following typo "dir:foo" in find_library instead of "dirs:foo".

What happens: find_library will just return it can't find the library.
What I would expected: Meson warns me that "dir:" has no effect.

**Comment by QuLogic** [comment] 2017-05-18 21:14
Dupe of #789.

**Closed** 2017-05-29 14:01 UTC
