### ISSUE TITLE
Cannot specify to find a static library with find_library instead of the shared one

### ISSUE THREAD

**Issue by nacho** [mesonbuild/meson#1816] opened 2017-05-18 06:40 UTC
If you have a library like IPP which provides both the .a and the .so on the same directory there is no way to tell find_library to look for the static library instead of the shared one.

**Comment by rhd** [comment] 2017-09-27 16:54
This is a dup of #328 and I really wish we could teach find_library to prefer static libs. Maybe I'll take another look and submit a PR.

**Comment by nirbheek** [comment] 2018-02-23 23:26
Duplicate of https://github.com/mesonbuild/meson/issues/328.

**Closed by nirbheek** 2018-02-23 23:26 UTC
Labels: bug, dependencies
