### ISSUE TITLE
Tests fail when rustc is not installed

### ISSUE THREAD

**Issue by seb128** [mesonbuild/meson#6588] opened 2020-02-05 14:16 UTC
The issue is new with 0.53, some Ubuntu architectures don't install rustc in the meson test environment and that used to work fine/have those tests skipped in 0.52 but now it fails with this error

```
======================================================================
ERROR: test_ld_environment_variable_rust (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 5897, in test_ld_environment_variable_rust
    self._check_ld('ld.gold', 'gold', 'rust', 'GNU ld.gold')
  File "run_unittests.py", line 5881, in _check_ld
    comp = getattr(env, 'detect_{}_compiler'.format(lang))(MachineChoice.HOST)
  File "/tmp/autopkgtest.1s2f0s/build.XFh/src/mesonbuild/environment.py", line 1411, in detect_rust_compiler
    self._handle_exceptions(popen_exceptions, compilers)
  File "/tmp/autopkgtest.1s2f0s/build.XFh/src/mesonbuild/environment.py", line 733, in _handle_exceptions
    raise EnvironmentException(errmsg)
mesonbuild.mesonlib.EnvironmentException: Unknown compiler(s): ['rustc']
The follow exceptions were encountered:
Running "rustc --version" gave "[Errno 2] No such file or directory: 'rustc'"
```

**Comment by jpakkane** [comment] 2020-02-05 19:06
This is a duplicate of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950020

It has been fixed by #6539, which will be in the next release.

**Closed by jpakkane** 2020-02-05 19:06 UTC
