### ISSUE TITLE
Un-avoidable warning 'add_languages is missing native'

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#6849] opened 2020-03-26 23:30 UTC
**Describe the bug**
systemd master build with meson 0.53.999 emits a warning:
```
../meson.build:306: WARNING: add_languages is missing native:, assuming languages are wanted for both host and build.
```
We could add `native:...` to avoid the warning. But `native` option was only added very recently, so this would not work with older mesons. Please only emit the warning when meson_version specified in project() is recent enough to support this option.

**Comment by jon-turney** [comment] 2020-03-27 13:03
assign this to me, please

**Comment by jon-turney** [comment] 2020-03-28 16:47
> We could add `native:...` to avoid the warning. But `native` option was only added very recently, so this would not work with older mesons.

With older meson, you'll get `WARNING: Passed invalid keyword argument "native".`

> Please only emit the warning when meson_version specified in project() is recent enough to support this option.

Thinking this over, I'm not sure about that solution you propose.  That would make it possible to use `meson setup --fatal-meson-warnings` with both old and new versions of meson (in this particular instance), but is that a sensible goal?

Perhaps you could elaborate on what the problem is?

**Comment by keszybz** [comment] 2020-03-29 18:51
> Perhaps you could elaborate on what the problem is?

I want to have a meson build without any warnings, for some sensible range of meson versions. We cannot require everyone to have the latest meson version, and the build should be fully functional with a recent-but-not-latest meson version. We *would* like to require more recent meson versions, to take advantage of various new features, but we look at what Debian, Ubuntu, Fedora, Suse, Arch, have in a stable release, and if that's still an older version of meson, we don't use those new features. We make the effort to support a range of mesons, and will change things to avoid warnings whenever a new meson version appears. The problem with this change is not that things changed, even in a way that requires adjustments from projects, but that there's no way to adjust to have a warning-free build with both the latest meson and what is currently in stable distributions.

FWIW, the same policy applies to the compilers (both gcc and clang), kernel headers, glibc headers, and other dependencies.

**Closed** 2020-07-30 13:39 UTC
