### ISSUE TITLE
install_headers() should also install headers into intermediate directories

### ISSUE THREAD

**Issue by CoffeeFlux** [mesonbuild/meson#7911] opened 2020-10-28 22:21 UTC
Copying from https://github.com/mesonbuild/meson/issues/2546, which was closed but AFAIK without the problem being resolved.

`install_headers()` and `configure_file()` with the `install_dir` option set should install headers into `meson-private/include-intermediates` during the meson config phase .

Many 3rd packages have header files and source files in same directory but install header files into a subdirectory after install, so this will cause an error finding the header files when using them in a subproject.

The workaround, as suggested by @nirbheek:
> Yes, there is a way around this. You can copy the headers to the build directory into the subdir that you use when installed with `configure_file()`, and then create an `include_directories()` object that points to it.

**Comment by eli-schwartz** [comment] 2021-07-15 03:05
Duplicate of #2546

**Closed by eli-schwartz** 2021-07-15 03:05 UTC
