### ISSUE TITLE
i18n: gmo files installed by ninja install are not removed with ninja uninstall

### ISSUE THREAD

**Issue by hanetzer** [mesonbuild/meson#5272] opened 2019-04-16 20:40 UTC
As the title states. Attached is a minimal test case.
[bug-hello.tar.gz](https://github.com/mesonbuild/meson/files/3086814/bug-hello.tar.gz)

**Comment by TingPing** [comment] 2019-04-19 01:52
Duplicate of https://github.com/mesonbuild/meson/issues/1601

**Closed by TingPing** 2019-04-19 01:52 UTC
