### ISSUE TITLE
meson 0.53.0 py_installation.dependency('dbusmock') leads to: ERROR: Function does not take positional arguments.

### ISSUE THREAD

**Issue by DimStar77** [mesonbuild/meson#6470] opened 2020-01-15 13:50 UTC
**Describe the bug**
The error was detected while building folks (reported there too, but presumably this is a meson issue):
https://gitlab.gnome.org/GNOME/folks/issues/119

**To Reproduce**
A minimalistic meson.build could be:

```
project('folks', [ 'vala', 'c' ],
  version: '0.13.1',
  license: 'LGPL2.1+',
  meson_version: '>= 0.49',
)

pymod = import('python')
py_installation = pymod.find_installation('python3')
python_dbusmock = py_installation.dependency('dbusmock')
```

**Expected behavior**
Like earlier meson version: pass

**system parameters**
Tested on openSUSE Tumbleweed; last version in use was meson 0.51.2, where it works. Latest to be tested is 0.53.0 - where it fails

**Comment by ailin-nemui** [comment] 2020-01-15 13:54
probable fix: delete this line https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/python.py#L351

**Comment by DimStar77** [comment] 2020-01-15 14:24
> probable fix: delete this line

fixes folks at least; I'm just building a whole gnome stack to see if something new would pop up

**Comment by xclaesse** [comment] 2020-01-15 15:20
git blame points the finger to https://github.com/mesonbuild/meson/pull/6341. The fix is indeed to remove @noPosargs, if someone wants to open a PR.

**Comment by mensinda** [comment] 2020-01-15 15:57
The thing is, that adding any positional arguments doesn't do anything here since `args` is never used inside the function. Also, the dependency name is hardcoded to `python` [here](https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/python.py#L48). So it does make semantically sense to add `@noPosargs` here unless I have fundamentally missed something.

**Comment by xclaesse** [comment] 2020-01-15 16:28
@mensinda Oops, you're right. The doc is misleading, it means that it has the same keyword arguments than dependency(), not same positional arguments. The name of the dependency is hardcoded to "python" and you cannot change that.

**Comment by mensinda** [comment] 2020-01-15 16:28
So, to further clarify, passing an argument to `py_installation.dependency()` should be an error, since this method will only ever return a `python` dependency (for embedding python itself, etc.) and **not** `dbusmock` or anything else.

That being said, I am not sure if it makes sense to just "break" existing meson projects (although they are arguably already broken). So it might make sense to print a warning like:

```dependency does not take any positional arguments.
It always returns a dependency for python itself.
This will become a hard error in the future.
```

**Comment by DimStar77** [comment] 2020-01-15 16:47
> So, to further clarify, passing an argument to py_installation.dependency() should be an error, since this method will only ever return a python dependency (for embedding python itself, etc.) and not dbusmock or anything else.

So that seems to be a misunderstadning by the folks-folks as to what 'depdendency' does and what it  is used for.

but the documentation is clearly also 'misleading' here then:

> python_dependency py_installation.dependency(...)
>
>This method accepts the same arguments as the standard dependency function and the following >additional keyword arguments:
…

>    dependency_object dependency(*dependency_name*, ...)
>
>Finds an external dependency (usually a library installed on your system) with the given name with pkg-config and with CMake if pkg-config fails. Additionally, frameworks (OSX only) and library-specific fallback detection logic are also supported. This function supports the following keyword arguments:

**Closed** 2020-02-16 22:38 UTC

**Comment by Apteryks** [comment] 2021-10-30 03:08
Hmm, I just stumbled on this while attempting to build accountsservice 0.6.55 on GNU Guix:

```
starting phase `configure'
The Meson build system
Version: 0.60.0
Source dir: /tmp/guix-build-accountsservice-0.6.55.drv-0/accountsservice-0.6.55
Build dir: /tmp/guix-build-accountsservice-0.6.55.drv-0/build
Build type: native build
Project name: accountsservice
Project version: 0.6.55
C compiler for the host machine: gcc (gcc 10.3.0 "gcc (GCC) 10.3.0")
C linker for the host machine: gcc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "paths.h" : YES 
Has header "shadow.h" : YES 
Has header "utmpx.h" : YES 
Checking for function "getusershell" : YES 
Checking for function "setutxdb" : NO 
Checking for function "fgetpwent" : YES 
Header <utmpx.h> has symbol "WTMPX_FILENAME" : YES 
Message: whether optimization is enabled: true
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-deprecated-declarations: YES 
Compiler for C supports arguments -Wswitch-enum: YES 
Compiler for C supports arguments -Wunsafe-loop-optimizations: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Found pkg-config: /gnu/store/wc7lqi6kgki5qzr01g3gvriwdadjiwpc-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency gio-2.0 found: YES 2.70.0
Run-time dependency gio-unix-2.0 found: YES 2.70.0
Run-time dependency glib-2.0 found: YES 2.70.0
Run-time dependency polkit-gobject-1 found: YES 0.120
Library crypt found: YES
Run-time dependency dbus-1 found: YES 1.12.20
Run-time dependency libelogind found: YES 246.10
WARNING: Project targeting '>= 0.46.0' but tried to use feature introduced in '0.50.0': install arg in configure_file.
Configuring org.freedesktop.Accounts.service using configuration

../accountsservice-0.6.55/data/meson.build:31:5: ERROR: Function does not take positional arguments.

A full log can be found at /tmp/guix-build-accountsservice-0.6.55.drv-0/build/meson-logs/meson-log.txt
error: in phase 'configure': uncaught exception:
%exception #<&invoke-error program: "meson" arguments: ("--prefix=/gnu/store/rwh7pv8lc2nddrlq1f16sp04b87c91r0-accountsservice-0.6.55" "--buildtype=debugoptimized" "-Dc_link_args=-Wl,-rpath=/gnu/store/rwh7pv8lc2nddrlq1f16sp04b87c91r0-accountsservice-0.6.55/lib" "-Dcpp_link_args=-Wl,-rpath=/gnu/store/rwh7pv8lc2nddrlq1f16sp04b87c91r0-accountsservice-0.6.55/lib" "--localstatedir=/var" "-Dsystemdsystemunitdir=/tmp/empty" "-Dsystemd=false" "-Delogind=true" "/tmp/guix-build-accountsservice-0.6.55.drv-0/accountsservice-0.6.55") exit-status: 1 term-signal: #f stop-signal: #f>
```
Is this the same bug?

**Comment by Apteryks** [comment] 2021-10-30 03:12
That's a regression from 0.59.4.

**Comment by nirbheek** [comment] 2021-10-30 05:32
@Apteryks this should've been fixed by https://github.com/mesonbuild/meson/pull/9445, can you check that pleaes?

**Comment by eli-schwartz** [comment] 2021-10-30 23:54
> Is this the same bug?

> That's a regression [...]

Meson has *many* functions, and a number of them do not take positional arguments. If you take a look at line 31 of ../accountsservice-0.6.55/data/meson.build it will tell you *exactly* what function doesn't take positional arguments this time -- and it's not a `py_installation.dependency()`.

Either way -- neither this nor #9445 was a Meson bug, but a bug in peoples' meson.build, please submit a bug report to accountsservice for them to fix their incorrect usage of Meson because it really does need to be fixed. This is independent of whether Meson relaxes its error-checking and gives people a grace period during which doing the always-incorrect thing merely warns rather than erroring.

**Comment by Apteryks** [comment] 2021-10-31 01:24
> Meson has _many_ functions, and a number of them do not take positional arguments. If you take a look at line 31 of ../accountsservice-0.6.55/data/meson.build it will tell you _exactly_ what function doesn't take positional arguments this time -- and it's not a `py_installation.dependency()`.

Ah, I understand better now; that's what I wanted to see when debugging but I had erroneously looked at the project's root directory meson.build file instead of the one nested under the data/ dir. The problematic function is:

```
i18n.merge_file(   # this is line 31 of data/meson.build
  policy,
  input: policy + '.in',
  output: policy,
  po_dir: po_dir,
  install: true,
  install_dir: policy_dir,
)
```
> Either way -- neither this nor #9445 was a Meson bug, but a bug in peoples' meson.build, please submit a bug report to accountsservice for them to fix their incorrect usage of Meson because it really does need to be fixed. This is independent of whether Meson relaxes its error-checking and gives people a grace period during which doing the always-incorrect thing merely warns rather than erroring.

Understood; I've reported it here: https://gitlab.freedesktop.org/accountsservice/accountsservice/-/issues/97.

Thanks!
