### ISSUE TITLE
meson build -Dprefix=/usr does not set prefix, have to use --prefix

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2445] opened 2017-10-07 07:08 UTC
meson build -Dprefix=/usr does not set the prefix, have to use --prefix. However, meson configure accepts -Dprefix and prefix is listed as a regular option.

**Comment by TingPing** [comment] 2017-10-07 14:28
Duplicate of #969

**Closed by TingPing** 2017-10-07 14:28 UTC
