### ISSUE TITLE
[possible regression in 0.55] New rpath must not be longer than the old one

### ISSUE THREAD

**Issue by yurivict** [mesonbuild/meson#7551] opened 2020-08-05 20:46 UTC
Several projects fail to build with meson with the error from the subject.
For example devel/gnome-builder: http://package22.nyi.freebsd.org/data/113amd64-default-PR244008/2020-07-15_21h37m37s/logs/errors/gnome-builder-3.28.4_4.log
See the list here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247935#c2

Could you please comment on this? Why did these build before and not with 0.55?

FreeBSD 12.1

Thanks,
Yuri

**Comment by dcbaker** [comment] 2020-08-05 20:51
I looked at the code, that particular error code has existed (Unchanged I think) since 2016. It's possible that we changed either the BUILD rpath code or the install RPATH code in 0.55.

**Comment by jpakkane** [comment] 2020-08-07 19:24
This is probably because earlier we reserved the exact amount of space needed by install_rpath and nuked everything else. Now we preserve rpaths coming from external sources but don't account for them when calculating how much space to reserve.

**Comment by yurivict** [comment] 2020-08-07 19:31
This bug is a show-stopper since so many ports are failing with this error.

**Comment by jpakkane** [comment] 2020-08-07 20:28
I tried to reproduce this locally but could not. I.e. eog builds and installs just fine and the rpath length calculation also works. This may be FreeBSD specific. Would it be possible for you to run one of the failing builds with the patch from #7565 applied to Meson?

**Comment by nirbheek** [comment] 2020-08-15 06:03
Note: the next stable point release will happen in the next couple of days. This open issue / merge request is marked for the point release but will not block its release.

**Comment by yurivict** [comment] 2020-08-20 16:46
With meson-0.55.1 the failure looks like this:

```
New rpath must not be longer than the old one.
 Old: b'/usr/local/lib/dpdk/pmds-20.0'
 New: b'/usr/local/lib/dpdk/pmds-20.0:/usr/local/lib/dpdk/pmds-20.0'
FAILED: meson-install 
```

See the log: http://package22.nyi.freebsd.org/data/113amd64-default-PR244008/2020-08-18_07h28m26s/logs/errors/dpdk-19.11.3.log

**Comment by nathankidd** [comment] 2020-08-27 21:26
We hit the "New rpath must not be longer" issue on sunos-sparc64 (Solaris 10) using meson-0.55.0.

With latest master @ 6fc067344d035c0c16fb33c11f5f0ace5c99c558 we still get the rpath error (though now the error message is better):
 
> New rpath must not be longer than the old one.
>  Old: b'$ORIGIN'
>  New: b'$ORIGIN:$ORIGIN'
> FAILED: meson-install
> 
> -bash-3.2$ meson --version
> 0.55.999
>

**Comment by yurivict** [comment] 2020-08-27 22:01
This holds the ```meson``` port update, and a number of other ports that depend on higher versions of ```meson```.

**Comment by jpakkane** [comment] 2020-08-27 23:07
Updated the MR. If you want to distro patch, take that. Otherwise it will be in the next point release.

**Closed** 2020-08-30 15:58 UTC
Labels: *BSD, regression
