### ISSUE TITLE
-Dbuildtype not supported in meson setup

### ISSUE THREAD

**Issue by fthiery** [mesonbuild/meson#2736] opened 2017-12-06 11:36 UTC
Took me a while to understand why -Dbuildtype=release was not taken into account, and that --buildtype=release was necessary (seen here http://mesonbuild.com/Running-Meson.html); however
- the manpage (man meson) doesn't list  --buildtype
- meson configure -Dbuildtype does work

I think that meson setup should support -Dbuildtype, and the man page should mention --buildtype

**Comment by rib** [comment] 2017-12-08 14:05
I forgot to file a similar issue but also was a bit surprised I ended up resorting to greping through the code the other week before I realised there was a --buildtype since I didn't notice anything in the manual.

**Comment by nwnk** [comment] 2018-01-04 16:17
AFAICT `-D` doesn't work at all for `meson setup`:

```
desoxy:~/git/xserver% meson setup -Dprefix=/usr build >& /dev/null 
desoxy:~/git/xserver% meson configure build | grep prefix
  prefix         /usr/local     Installation prefix.
```

**Comment by TingPing** [comment] 2018-01-04 17:28
Duplicate of #969

**Closed** 2018-01-25 19:53 UTC
