### ISSUE TITLE
don't stop at first notfound dependency

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#188] opened 2015-06-28 19:35 UTC
Now we are stopping at first notfound dependency. Would be great to check all deps and print it at the end. I don't need to run meson, get err, install dep, run meson again, get err, install dep, ...

**Comment by jpakkane** [comment] 2015-06-28 20:47
This is by design. Having to add deps one by one is slightly irritating but the alternative is even more bad. If we permit this then users can't depend on things in their build defs. For example if you do fallbacks then this happens:

    dep = dependency('foo')
    if not dep.found()
      # anything you do here is wrong
    endif

As an example CMake defaults to not halting for missing dependencies and it is a major pain in the rear. 

If you are working on an existing project you can get the build-deps installed with the equivalent of `apt-get build-dep projectname`.

**Comment by nirbheek** [comment] 2016-10-25 18:27
Ancient history bug, closing. This is doable, but requires a lot more work and would provide significant savings in parallelism, but meson is not a bottleneck for anyone right now.

**Closed by nirbheek** 2016-10-25 18:27 UTC
Labels: enhancement
