### ISSUE TITLE
Multiple producers for Ninja target "coverage-html". Please rename your targets.

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#2299] opened 2017-09-09 17:45 UTC
I'm getting this error after I tried to build an old project of mine, nothing seems out of order and the build works fine without using coverage feature.

```
The Meson build system
Version: 0.42.0
Source dir: /pipeline/source
Build dir: /pipeline/source/build
Build type: native build
Project name: net
Native C++ compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Dependency GTest found: YES (building self)
Build targets in project: 11

Meson encountered an error:
Multiple producers for Ninja target "coverage-html". Please rename your targets.
```

**Comment by jpakkane** [comment] 2017-09-09 18:12
Duplicate of #2256.

**Closed by jpakkane** 2017-09-09 18:12 UTC
