### ISSUE TITLE
AttributeError: Can't get attribute 'OptionString' on ......string' from '.../string.py'>

### ISSUE THREAD

**Issue by guxiao-tetras** [mesonbuild/meson#12073] opened 2023-08-04 09:08 UTC
**Describe the bug**
I'm trying to build raspi libcamera when I encountered this problem and it says 

> ERROR: Unhandled python exception
> This is a Meson bug and should be reported!

The whole message is

> ninja: Entering directory `build'
> [1/2] Installing files.
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
>     return options.run_func(options)
>   File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
>     installer.do_install(datafilename)
>   File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
>     d = self.check_installdata(pickle.load(ifile))
> AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>
> 

**To Reproduce**
I'm following this guide step by step, except that I didn't use sudo with pip3 install
https://www.raspberrypi.com/documentation/computers/camera_software.html#building-libcamera-and-libcamera-apps

I noticed meson is installed twice(apt and pip3), and in similar issue remove all meson and reinstall solved it but the solution  doesn't work here.

**Expected behavior**
install success

**system parameters**
I'm using WSL2(ubuntu 22.04) on win10
Not sure with python version. Perhaps Python 3.10.12. The command python is not redirected.
meson --version
0.61.2
ninja --version
1.10.1

**Comment by eli-schwartz** [comment] 2023-08-04 11:45
Duplicate of #8425

**Closed by eli-schwartz** 2023-08-04 11:45 UTC

**Comment by eli-schwartz** [comment] 2023-08-04 11:48
Duplicate of:
#8425
#8695
#8887
#10448 
#11009 
#11650 
#11651

**Comment by guxiao-tetras** [comment] 2023-08-05 09:14
> 

Hi,
I've read the thread you mentioned, in which meson is installed with pip3. But in my case, meson is installed both with sudo apt and pip3. The meson that is actually under use is /usr/bin/meson(which meson). I tried pip3 uninstalling meson. It made no difference.
So I don't think It's pip3 install previllage issue.

**Comment by eli-schwartz** [comment] 2023-08-06 02:09
The problem is that you created a build directory with the pip version and that is incompatible with the apt version.


- When uninstalling the pip version, only the apt version is available.
- When running with `sudo ninja install`, only the apt version is available to sudo.

In both cases, when running the apt version it errors out with the referenced AttributeError.

Later versions of meson fixed this issue and instead print a clear error message saying that you're running with a different version of meson and suggesting that you delete your build directory and recreate it.

However, the version of meson distributed by apt on Ubuntu 22.04 is slightly too old to have that enhanced error message -- instead it crashes illegibly. We can't fix the error message in Ubuntu because we don't control which version Ubuntu includes.

**Comment by guxiao-tetras** [comment] 2023-08-07 08:13
> The problem is that you created a build directory with the pip version and that is incompatible with the apt version.
> 
> * When uninstalling the pip version, only the apt version is available.
> * When running with `sudo ninja install`, only the apt version is available to sudo.
> 
> In both cases, when running the apt version it errors out with the referenced AttributeError.
> 
> Later versions of meson fixed this issue and instead print a clear error message saying that you're running with a different version of meson and suggesting that you delete your build directory and recreate it.
> 
> However, the version of meson distributed by apt on Ubuntu 22.04 is slightly too old to have that enhanced error message -- instead it crashes illegibly. We can't fix the error message in Ubuntu because we don't control which version Ubuntu includes.

Thanks a lot. I have downloaded the latest release and almost fixed the problem.
Now the lib can be built successfully.
But at the end of building, I got

> [204/205] Installing files.
> Installation failed due to insufficient permissions.
> Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n] y
> [sudo] password for guxiao:
> Traceback (most recent call last):
>   File "/home/guxiao/.local/bin/meson", line 5, in <module>
>     from mesonbuild.mesonmain import main
> ModuleNotFoundError: No module named 'mesonbuild'
> FAILED: meson-internal__install
> /home/guxiao/.local/bin/meson install --no-rebuild
> ninja: build stopped: subcommand failed.
This is probably another permission issue.
I bypassed it by -Dprefix=~/.local/lib/
I wonder what is the official way to install meson built binaries.
Thanks.
