### ISSUE TITLE
meson dist --include-subprojects ignores patch_directory

### ISSUE THREAD

**Issue by gerddie** [mesonbuild/meson#8190] opened 2021-01-12 18:25 UTC
With the wrap file

```
[wrap-git]
url = https://github.com/741g/vperfetto.git
revision = head
patch_directory = vperfetto_min
```

I can build the project including the subproject, but when I run `meson dist --include-subprojects` I get the error 
```
ERROR: Subproject exists but has no meson.build file
```

Other than in #8127 the patch is already located within the project, it is just not copied over to the subproject, so that the test build doesn't work, and a tarball created with `--no-tests` would not work. Since I have no control over the subproject, I can't add the meson.build  file there, and forking the project to just add the meson.build file is quite inconvenient, since it would mean one would have to synchronize the fork instead of just pulling from the main repo. 

Thanks, 
Gert

**Comment by eli-schwartz** [comment] 2021-09-03 03:54
Duplicate of #8127

**Closed by eli-schwartz** 2021-09-03 03:54 UTC
