### ISSUE TITLE
meson vs2015 backend on Appveyor with msbuild project fails on linker

### ISSUE THREAD

**Issue by mikkelfj** [mesonbuild/meson#800] opened 2016-09-20 14:25 UTC
This is on experimental meson branch of the flatcc project.

Apparently meson thinks it is working with clang.

The following is a 1 to 1 port of a cmake build, only Debug has become debug and meson installed instead of CMake. No ninja, no clang.

https://ci.appveyor.com/project/dvidelabs/flatcc/build/win%23152/job/ybrpgvo97arf6w6t
https://github.com/dvidelabs/flatcc/blob/meson/appveyor.yml

The travis build of the meson branch works, but uses a somewhat different setup, though same meson.build file.

The cmake on master branch works - available from frontpage:
https://github.com/dvidelabs/flatcc

**Comment by nirbheek** [comment] 2016-09-26 21:05
It looks like you don't set the environment that causes `cl.exe` to become available in `PATH`. You need to call:

'"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86' to set the environment building with for Win32 and `/amd64` for x64.

The reason why `clang` is detected is probably because it is already installed on the image and available in `PATH`.

**Comment by nirbheek** [comment] 2016-09-26 21:24
Sorry, I misspoke. You need to run:

```
'"C:\Program Files\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" /x86'
```

The previous command will give you a Visual Studio 2010 environment.

**Comment by mikkelfj** [comment] 2016-09-27 09:44
Thanks for looking into this.
I was hoping meson could figure this out - as it truly is a pain to get this configured correctly.
The path gave me problems, so I followed: https://github.com/ignacio/lua-appveyor-example/issues/10

I got the following x64 setup sort of working but the build still fails.
https://ci.appveyor.com/project/dvidelabs/flatcc/build/job/7xuju37g127ooq0a

while the x86 fails earlier
https://ci.appveyor.com/project/dvidelabs/flatcc/build/job/h29cihqglbbvhs8j

Full build here: https://ci.appveyor.com/project/dvidelabs/flatcc/build/win%23159

**Comment by nirbheek** [comment] 2016-10-05 14:53
The actual error seems to be:

```
c:\projects\flatcc\include\flatcc\support\elapsed.h(8): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [c:\projects\flatcc\build\MSVC\test\benchmark\benchraw\benchraw@exe.vcxproj]
```

There's no `sys/time.h` on Windows. The problem is that this line:

https://github.com/dvidelabs/flatcc/blob/6e31131a0b8bf659b5df577f34b3fe409796426e/include/flatcc/support/elapsed.h#L7

Should be `#if !defined(_WIN32)`. See: https://msdn.microsoft.com/en-in/library/b0084kay.aspx

This is not a Meson bug, so far. :)

**Comment by mikkelfj** [comment] 2016-10-05 15:02
That is correct! The build works with CMake, but I forget that I couldn't easily get the benchmarks running with CMake, so this particalar part is new code being tested on Windows.

It still doesn't explain why the x64 breaks earlier, but it may be something trivial - given that CMake configures the environment and meson doesn't.

**Comment by mikkelfj** [comment] 2016-10-05 15:16
The x64 build now fails on locating the library:
https://ci.appveyor.com/project/dvidelabs/flatcc/build/win%23160/job/1bg6m0ls4dr9gu6h

394        LINK : fatal error LNK1104: cannot open file '..\..\flatcc.lib' [c:\projects\flatcc\build\MSVC\test\cgen_test\cgen_test@exe.vcxproj]

This is core test that has passed many times in CMake with Windows unless I missed something critical.

**Comment by nirbheek** [comment] 2016-10-07 03:42
I'm not sure what cmake does, but looking at the code you're missing something: you need to export symbols with `__declspec(dllexport)` for any symbols to be exported into a DLL with an MSVC compiler. While linking to the library, your headers must declare the prototype with `__declspec(dllimport)`. See: https://msdn.microsoft.com/en-us/library/aa271769(v=vs.60).aspx

For examples, see:
https://cgit.freedesktop.org/gstreamer/gstreamer/tree/gst/gstconfig.h.in#n115
https://github.com/centricular/bzip2/blob/master/bzlib.h#L78
https://git.gnome.org/browse/glib/tree/glib/gtypes.h#n515

Alternatively, you can use a `.DEF` file that lists all the symbols you will be using, and add it to the shared library target with the `vs_module_defs` kwarg. See: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/gst/meson.build#n223

If there are no symbols exported, no `.lib` import library is created by MSVC.

Note that you don't need to do this with MinGW/GCC because it has its own auto-export/import mechanism.

**Comment by mikkelfj** [comment] 2016-10-07 04:25
Thanks - the CMake build doesn't use shared libraries by default and there really isn't any need for it, I just tried to accomodate as many meson build options as possible. I have worked with .DEF files many years ago ...

I'll probably disable shared libraries for Windows.

**Comment by nirbheek** [comment] 2016-10-07 04:43
Closing then. Cheers.

**Closed by nirbheek** 2016-10-07 04:43 UTC
