### ISSUE TITLE
[Feature request] Ability to set target executable or output name

### ISSUE THREAD

**Issue by rilian-la-te** [mesonbuild/meson#2907] opened 2018-01-10 20:58 UTC
We cannot set executable name for target output. For now, it always equals target name. But there are use cases, when we need 2 targets with same name, but different installed names. For now, it is not possible without much trouble like install_script.

**Comment by rilian-la-te** [comment] 2018-01-10 21:07
For example, how to translate [this](https://raw.githubusercontent.com/rilian-la-te/vala-panel-appmenu/master/appmenu-gtk-module/src/CMakeLists.txt) to Meson.

2 libraries is required to have same name.

**Comment by nirbheek** [comment] 2018-02-09 14:00
Could you explain what your use-case is for having two targets with the same name but different installed names? That link you just gave is broken, and the build file would not explain the reasoning anyway.

**Comment by rilian-la-te** [comment] 2018-02-09 14:31
I want to build one library twice with different dependencies  (GTK2 and GTK3 module) and install it into appropriate location with same name (so, GTK program will correctly select required version, if such name is set in GTK_MODULES)

**Comment by nirbheek** [comment] 2018-02-11 14:17
Duplicate of https://github.com/mesonbuild/meson/issues/2861.

**Closed by nirbheek** 2018-02-11 14:17 UTC
Labels: support
