### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by shi-yang-1983** [mesonbuild/meson#7878] opened 2020-10-21 07:57 UTC
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 245, in run
    app.generate()
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 159, in generate
    self._generate(env)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/msetup.py", line 192, in _generate
    intr.run()
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreter.py", line 4560, in run
    super().run()
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 493, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 534, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 615, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 526, in evaluate_statement
    self.assignment(cur)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 1177, in assignment
    value = self.evaluate_statement(node.value)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 524, in evaluate_statement
    return self.function_call(cur)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 879, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 194, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreter.py", line 3585, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/interpreter.py", line 3659, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/dependencies/base.py", line 2365, in find_external_dependency
    d = c()
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/dependencies/dev.py", line 234, in __init__
    self._set_new_link_args(environment)
  File "/usr/local/lib/python3.7/dist-packages/mesonbuild/dependencies/dev.py", line 284, in _set_new_link_args
    mode = self.get_config_value(['--shared-mode'], 'link_args')[0]
IndexError: list index out of range

meson --version
0.55.3

**Comment by mensinda** [comment] 2020-10-21 09:30
Could you please provide an example project/more information to reproduce this bug?

**Comment by dcbaker** [comment] 2020-10-21 18:13
Pretty sure this is a duplicate of https://github.com/mesonbuild/meson/issues/7371

**Closed** 2020-10-22 14:21 UTC
