### ISSUE TITLE
Custom target object has no way to refer to individual output files

### ISSUE THREAD

**Issue by manueljacob** [mesonbuild/meson#2250] opened 2017-08-27 11:51 UTC
I have a custom target that outputs one header file and one C file. Now I want to produce a shared library from the C file and a dependency so that users of this dependency can include the header file and link to the shared library.

There doesn't seem to be a way to do this. Notably, the custom target object doesn't have a way to refer to individual outputs. Maybe it would make sense to port some of the methods of build target objects to custom target objects, although I'm not sure this would be sufficient for my use case.

**Comment by nirbheek** [comment] 2017-08-31 09:20
Duplicate of https://github.com/mesonbuild/meson/issues/1470

**Closed by nirbheek** 2017-08-31 09:20 UTC
