### ISSUE TITLE
install_man() could allow custom_target() argument

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#5935] opened 2019-09-18 18:16 UTC
Giving a custom_target() as install_man() argument will raise an exception.
```py
ct1 = custom_target('ct.1',
                    output: 'ct.1',
                    capture: true,
                    command: 'echo')

install_man(ct1)
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 122, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 246, in run
    app.generate()
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 163, in generate
    self._generate(env)
  File "/usr/lib/python3.7/site-packages/mesonbuild/msetup.py", line 193, in _generate
    intr.run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3817, in run
    super().run()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 407, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 431, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 425, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 436, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 762, in function_call
    return func(node, posargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 285, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreterbase.py", line 174, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 3312, in func_install_man
    m = Man(fargs, kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 666, in __init__
    self.validate_sources()
  File "/usr/lib/python3.7/site-packages/mesonbuild/interpreter.py", line 675, in validate_sources
    num = int(s.split('.')[-1])
AttributeError: 'CustomTargetHolder' object has no attribute 'split'
```

(Giving full_path() isn't working as a workaround, as the file doesn't exist)

**Comment by xavierclaessens** [comment] 2019-09-18 18:26
If you use configure_file() instead of custom_target() it should work, right?

**Comment by Salamandar** [comment] 2019-11-01 11:45
> If you use configure_file() instead of custom_target() it should work, right?

Yeah, but that's not the same thing. I personally need some executables to be build before generating the man.1 files, so it cannot be done at configure time.

**Comment by bonzini** [comment] 2020-01-28 11:55
> If you use configure_file() instead of custom_target() it should work, right?

That won't work for e.g. building man pages with Sphinx. I'm taking a look at this.

**Comment by bonzini** [comment] 2020-01-29 00:12
See #4778, this should probably be closed. That said, for Sphinx specifically it may be worth working on a module...

**Comment by eli-schwartz** [comment] 2020-05-05 02:25
Duplicate of #1550

**Closed** 2020-06-04 08:23 UTC
