### ISSUE TITLE
AttributeError: 'SubprojectHolder' object has no attribute 'd_features'

### ISSUE THREAD

**Issue by ChristianJacobsen** [mesonbuild/meson#10468] opened 2022-06-07 19:17 UTC
**Describe the bug**
Attempting to use `libjpeg-turbo` from `wrapdb` as a dependency for my project. During compilation, I get told that the above-mentioned error should be reported. As a law-abiding developer, I humbly oblige.

**To Reproduce**
```meson
project(
  'meson_wrap_reproduct',
  'c',
  version: '0.1',
  default_options: [
    'c_std=18',
    'warning_level=3',
    'werror=true'
  ],
)

libjpeg = subproject('libjpeg-turbo')

executable(
  'meson_wrap_reproduct',
  'meson_wrap_reproduct.c',
  dependencies: [
    libjpeg,
  ]
)
```

with `libjpeg-turbo` as a subprojects dependency.

**Expected behavior**
Using the dependency from `wrapdb` should work.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Plain
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Arch Linux @ 5.17.9
* what Python version are you using e.g. 3.8.0
  * 3.10.4
* what `meson --version`
  * 0.62.2
* what `ninja --version` if it's a Ninja build
  * 1.10.2

This seems to be the case for `libpng` as well, so I'm assuming this is a wider problem.

**Comment by eli-schwartz** [comment] 2022-06-07 19:27
```meson
libjpeg = subproject('libjpeg-turbo')

executable(
     ....
  dependencies: [
    libjpeg,
  ]
```

This is a sanity checking bug, because Meson should not error out with a 46-line traceback which users don't understand, but should instead emit a very simple error that clearly tells users what the problem is, of the form:

```
meson.build:14:0: ERROR: executable keyword argument 'dependencies' was of type array[SubprojectHolder] but should have been array[actually | permitted | types]
```



In the long term this will be fixed by #9950 which will give us a sensible way to generically constrain this.

In the short term we can add a specific type validation here, which we already do for lots of other things for the executable() function.

**Comment by xclaesse** [comment] 2022-06-07 19:46
> ```meson
> libjpeg = subproject('libjpeg-turbo')
> ```

Try instead `dependency('libjpeg')`, it will check if libjpeg is found on system first, then fallback to use libjpeg-turbo from wrapdb assuming you have `subprojects/libjpeg-turbo.wrap`.

**Comment by ChristianJacobsen** [comment] 2022-06-07 20:24
That sounds amazing @xclaesse! 😍

I currently have to specify `'werror=false'` in my `default_options` for both `libjpeg-turbo` and `libpng`, since I am using it in my own project `default_options`. How do I ensure that continues (as they won't build without) if I use `dependency(...)` instead?

**Comment by eli-schwartz** [comment] 2022-06-07 20:46
Both `subproject()` and `dependency()` accept a `default_options: ` kwarg, and in both cases its usage is that it will be passed to a subproject -- in the former case, explicitly so; in the latter case, whenever the dependency lookup triggers a subproject fallback.

**Comment by eli-schwartz** [comment] 2022-06-07 20:52
If you really, really feel you must use the subproject explicitly and not leave any option to first find a prebuilt system copy, that works too, but you need to use the returned subproject object `libjpeg` like this:

```
libjpeg_dep = libjpeg.get_variable('jpeg_dep')

executable(..., dependencies: libjpeg_dep)
```

get_variable() is how you manually retrieve e.g. a "dependency" object (assigned in the libjpeg-turbo subproject as `jpeg_dep = declare_dependency(...)`) from a subproject object container.

The dependency fallback is a lot more elegant if we assume that the project doesn't care how it gets libjpeg.

**Comment by ChristianJacobsen** [comment] 2022-06-07 20:58
@eli-schwartz, thanks for the insight! I should probably read the Meson Manual again 😄

Have an excellent evening both of you!

**Closed** 2022-06-17 03:57 UTC
Labels: parser/interpreter
