### ISSUE TITLE
All files report 0% coverage

### ISSUE THREAD

**Issue by vedranmiletic** [mesonbuild/meson#6726] opened 2020-03-02 21:03 UTC
**Describe the bug**
All files have 0% coverage after running `ninja coverage`.

**To Reproduce**
Take spdlog for example.

```
git clone https://github.com/gabime/spdlog.git
cd spdlog
meson -Dlibrary_type=shared -Denable_benchmarks=true -Denable_tests_ho=true -Db_coverage=true builddir
cd builddir
ninja
ninja coverage
```

**Expected behavior**
Nonzero percents since some tests exist.

**system parameters**
* plain native build
* Manjaro stable
* Python version 3.8.1
* meson 0.53.1
* ninja 1.10.0

Note: If I'm doing something wrong and this causes percents to remain at zero, please correct me and I'll update the relevant documentation to clarify how it should be done.

**Comment by jpakkane** [comment] 2020-03-02 23:32
Are you running the tests with `ninja test` before generating the coverage report?

**Comment by vedranmiletic** [comment] 2020-03-03 00:39
> Are you running the tests with `ninja test` before generating the coverage report?

See, that's why I put the note at the end. Thanks, I'll submit a pull request with the documentation update soonish.

**Comment by michaelbadcrumble** [comment] 2020-03-09 18:18
Hey @vedranmiletic as a result of this issue I just wrote a tip to help other users from making the same mistake, adding this to my notebook, thanks.

## [***Meson Tip***] Proper usage of `ninja coverage`

Have you ever had all coverage results return with 0% after
running `ninja coverage`?

Why?  Will if you just run coverage without running test there will
not be any data for coverage reports, like the example below first
run tests then generate coverage results.

```console
meson setup -Db_coverage=true builddir
meson compile -C builddir
meson test -C builddir
ninja coverage -C builddir
```

--------

Hopefully, you have coverage and let me know if this helped,
thanks.

**Comment by vedranmiletic** [comment] 2020-03-09 19:23
> Hey @vedranmiletic as a result of this issue I just wrote a tip to help other users from making the same mistake, adding this to my notebook, thanks.
> ## [_**Meson Tip**_] Proper usage of `ninja coverage`
> 
> Have you ever had all coverage results return with 0% after
> running `ninja coverage`?
> 
> Why? Will if you just run coverage without running test there will
> not be any data for coverage reports, like the example below first
> run tests then generate coverage results.
> 
> ```
> meson setup -Db_coverage=true builddir
> meson compile -C builddir
> ninja test -C builddir
> ninja coverage -C builddir
> ```
> 
> Hopefully, you have coverage and let me know if this helped,
> thanks.

Glad to hear. I prepared a patch for the official documentation in similar tone in #6763.

**Comment by dcbaker** [comment] 2020-03-24 15:29
Since the PR landed I'm going to close this. Reopen if that is incorrect.

**Closed by dcbaker** 2020-03-24 15:29 UTC

**Comment by vedranmiletic** [comment] 2020-03-24 15:52
@dcbaker The PR landed landed, but I don't see it on mesonbuild.com yet.

**Comment by Astro36** [comment] 2021-08-07 06:43
I tried the above method but it still comes out as 0% coverage.

Can I get some help?

To Reproduce: https://github.com/int-i/cpp-sort/blob/main/.github/workflows/cpp.yml
