### ISSUE TITLE
MESONINTROSPECT not correctly passed to python script

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#6755] opened 2020-03-07 18:21 UTC
**Describe the bug**

Meson introspect is not correctly split to be consumed by a python script

**To Reproduce**

1. create a run_target
2. In your python script do:

```
meson_introspect = os.environ['MESONINTROSPECT']
print(meson_introspect)
``` 

**Expected behavior**
3. Observe that the output is not split correctly. It is

'meson ' introspect

but should be

'meson introspect'

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native build
* what operating system -> Windows 10
* what Python version are you using e.g. 3.8.0
* what `meson --version` -- 0.54
* what `ninja --version` if it's a Ninja build

**Comment by mensinda** [comment] 2020-03-21 09:36
I am unable to reproduce this. I get `/usr/bin/meson introspect` for `'MESONINTROSPECT'` with:

```meson
run_target('inspector', command: [find_program('check_env.py'), '0'])
```

```py
#!/usr/bin/env python3

import os
import sys
import shlex

if 'MESONINTROSPECT' not in os.environ:
    raise RuntimeError('MESONINTROSPECT not found')

mesonintrospect = os.environ['MESONINTROSPECT']

introspect_arr = shlex.split(mesonintrospect)

if sys.argv[1] == '0':
    print(mesonintrospect)
    print(introspect_arr)
```

This works with both `0.53.2` and the current master.

**Comment by germandiagogomez** [comment] 2020-05-27 09:40
> I am unable to reproduce this. I get `/usr/bin/meson introspect` for `'MESONINTROSPECT'` with:
> 
> ```meson
> run_target('inspector', command: [find_program('check_env.py'), '0'])
> ```
> 
> ```python
> #!/usr/bin/env python3
> 
> import os
> import sys
> import shlex
> 
> if 'MESONINTROSPECT' not in os.environ:
>     raise RuntimeError('MESONINTROSPECT not found')
> 
> mesonintrospect = os.environ['MESONINTROSPECT']
> 
> introspect_arr = shlex.split(mesonintrospect)
> 
> if sys.argv[1] == '0':
>     print(mesonintrospect)
>     print(introspect_arr)
> ```
> 
> This works with both `0.53.2` and the current master.

Try to do this in a python script with the setup you had (in Windows only, in Linux it works fine):

```
meson_introspect = os.environ['MESONINTROSPECT]

subprocess.run(meson_introspect.split(' '))
```

that will fail in Windows but not in Linux when there is a path with spaces I think it was, if I recall well (no access to the computer for this now).

**Comment by mensinda** [comment] 2020-05-31 18:26
I have just checked my code from above on Windows and this is the result I get: `['S:\\\\Python\\\\Python38\\\\python.exe', 'S:\\\\data\\\\projects\\\\meson\\\\meson.py', 'introspect']`

This looks pretty OK to me, so closing (the escaped `\` are apparently also not an issue).

**Closed by mensinda** 2020-05-31 18:26 UTC
Labels: introspection
