### ISSUE TITLE
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

### ISSUE THREAD

**Issue by thiell** [mesonbuild/meson#5337] opened 2019-04-30 17:52 UTC
Hello,

Did something break on master? Should we use another stable branch for testing? 
Thanks!!
```
  File "./setup.py", line 24, in <module>
    from mesonbuild.coredata import version
  File "/home/travis/build/stanford-rc/fuse-migratefs/meson/mesonbuild/coredata.py", line 21, in <module>
    from .mesonlib import (
  File "/home/travis/build/stanford-rc/fuse-migratefs/meson/mesonbuild/mesonlib.py", line 925, in <module>
    def typeslistify(item: typing.Union[_T, typing.List[_T]], types: typing.Union[typing.Type[_T], typing.Tuple[typing.Type[_T]]]) -> typing.List[_T]:
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

**Comment by dcbaker** [comment] 2019-04-30 19:44
Duplicate of #5326.

This should work fine with 3.6 or 3.7 if you have that option in the mean time.

**Closed by dcbaker** 2019-04-30 19:44 UTC
