### ISSUE TITLE
Feature request, subprojects with names other than subprojects 

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#9912] opened 2022-01-31 08:36 UTC
I am not 100% sure if the following is doable with meson.

I have a project that consists of many small libraries. Each library has its own suite of tests and dependencies and they are mean to be used together based on use case, for example sometimes you need libraries A and B sometimes B and C, sometimes A and C.

Currently the way I build things is, I have a single meson file at the root of the project, this meson file exposes each library as an individual target and the consumer project can thus cherry pick which to link against.

The issue is, the meson file keeps growing and growing, since all files for tests, library, dependencies... are in the same file it just makes it grow and grow as the project becomes larger. In my case it doesn't make sense to make subprojects because some of these libraries depend on others, which doesn't lead to a straightforward hierarchy that fits nicely into the design.

bazel solves this kind of problem by having a bazel file on each directory which specifies the tests, source files and external dependencies. I would like to be able to do something similar. That is, I would like to be able to specify arbitrary directories as subproject directories so that I  can make a multiplicity of meson.build files, one for each mini-project, but still be able to keep everything together in the same repo without shoehorning libraries into a single directory with a predefined name.

It seems other people have made this request before and I think it has value:
https://github.com/mesonbuild/meson/issues/1378

**Comment by eli-schwartz** [comment] 2022-01-31 13:59
> In my case it doesn't make sense to make subprojects because some of these libraries depend on others, which doesn't lead to a straightforward hierarchy that fits nicely into the design.

Then regardless of all other considerations, you are saying that your entire use case only has one `project()` function.

> I would like to be able to specify arbitrary directories as subproject directories so that I can make a multiplicity of meson.build files, one for each mini-project, but still be able to keep everything together in the same repo without shoehorning libraries into a single directory with a predefined name.

This sounds like you want to add a subproject which does not have a `project()` function, but is itself only one small portion of a larger project. This will then define library B for use by the superproject, but library B declares that it needs to `link_with` library A (meson variable `lib_a`) only to fail with an undefined variable error because lib_a doesn't exist (it comes from a different portion of the larger project which isn't part of your current subproject).

> It seems other people have made this request before and I think it has value: #1378

That other ticket was asking for the ability to consume whole subprojects, not partial ones.

If all you wanted was to use whole subprojects then this bug would be a duplicate of the one you linked.

Since it seems you want to use partial subprojects, it is instead invalid -- meson will not let you footgun yourself into undefined variable errors by using a not-subproject as if it was a subproject.

**Closed by eli-schwartz** 2022-01-31 13:59 UTC

**Comment by eli-schwartz** [comment] 2022-01-31 14:05
Also, the expected use of subprojects is one of two ways:
- invoke `mysubproject = subproject('foo')` to add the subproject into the build, then depend on individual libraries using `mysubproject.get_variable('lib_a')`
- using a wrap file with a provide section, and depending on individual libraries using `dependency()` to acquire a wrap provide name; this does `subproject()` under the hood

So it does not matter what name or path you use to add a `subproject()` to the build, the consumer project always adds everything into the build and then cherry-picks what to link against using `get_variable()`.

What's the actual problem that  you are encountering? There may be a better solution than reinventing how subprojects work.

**Comment by mensinda** [comment] 2022-01-31 14:27
> Currently the way I build things is, I have a single meson file at the root of the project

Not sure if you already know this, but you don't have to use a single `meson.build` file for your entire project. You can `subdir('liba')` into different directories (with a new `meson.build` and without a `project()` call) in the same project without relying on subprojects. There is no variable scope in Meson, so you will have access to all your variables from everywhere once they are defined (which can be a blessing and a curse).

**Comment by Makogan** [comment] 2022-01-31 21:35
@mensinda The problem is meson demands the use of relative paths but changes the active directory. So if library A is built on subdir 1 and then you call subdir 2 on library B, all paths in the meson for subdir B are specified relative to it, but the paths exported by A are relative to that file. The consequence is, it;s not possible to include the headers of one in the other without non negligible tinkering of the path,

**Comment by mensinda** [comment] 2022-01-31 22:04
That shouldn't be a problem if you use the `files()` and `include_directories()`. These objects will remember their relative paths.

https://mesonbuild.com/Reference-manual_functions.html#files
https://mesonbuild.com/Reference-manual_functions.html#include_directories


On 31 January 2022 22:35:57 CET, Camilo Talero ***@***.***> wrote:
***@***.*** The problem is meson demands the use of relative paths but changes the active directory. So if library A is built on subdir 1 and then you call subdir 2 on library B, all paths in the meson for subdir B are specified relative to it, but the paths exported by A are relative to that file. The consequence is, it;s not possible to include the headers of one in the other without non negligible tinkering of the path,
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mesonbuild/meson/issues/9912#issuecomment-1026235117
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Makogan** [comment] 2022-01-31 22:30
I am a little confused, I am talking about the include path associated with a  library object.

For example:
```
core_sources = [
    'Core/Core.cpp',
    'Core/Log.cpp'
]
core_lib = library('ne_core', sources : core_sources)
```

This generates a library object, the following works when done in the same build file:

```
# ===| Core |===
core_sources = [
    'Core/Core.cpp',
    'Core/Log.cpp'
]
core_lib = library('ne_core', sources : core_sources)

# ===| Renderer |===
# subdir('Renderer')
renderer_sources = [
    'Renderer/Renderer.cpp',
    'Renderer/HardwareInterface.cpp',
    'Renderer/Utils.cpp',
    'Renderer/VkExtensionsStubs.cpp',
    'Renderer/VulkanDebugging.cpp'
]

renderer_lib = shared_library(
    'ne_renderer',
    sources : renderer_sources,
    link_with : [core_lib],
    include_directories : [],
    dependencies : [
        vulkan,
        glfw
        ])
```

But if you move the second binary rules to a different meson. build and try to do the same you would get:
`fatal error: Core/Log.hpp: No such file or directory`

This is because meson is using the core_lib object's include path, which is specified relative to the caller and it is not modified for the child.

The 'Core/' directory inclusion is never explicitly specified.

You could also send this information through a vairable I assume, but then your include rules are implicitly including ghost directories coming from the lib.

**Comment by eli-schwartz** [comment] 2022-01-31 22:33
> I am a little confused, I am talking about the include path associated with a library object.

There isn't one. Library objects only have libraries.

`declare_dependency()` objects can add a library object and an `include_directories()` object and expose them together. Most often, this will be a limited and restricted subset of the include directories that the library itself was compiled with.

**Comment by Makogan** [comment] 2022-01-31 22:59
Oh I see, thank you!
