### ISSUE TITLE
pot command can't find generated file

### ISSUE THREAD

**Issue by jbicha** [mesonbuild/meson#4353] opened 2018-10-08 23:13 UTC
The [GNoME Recipes app](https://gitlab.gnome.org/GNOME/recipes) uses a generated file in its `po/POTFILES.in` Although unusual, it ought to still work.

Test Case
------------
```
git clone https://gitlab.gnome.org/GNOME/recipes
meson builddir
ninja -C builddir
ninja -C builddir gnome-recipes-pot
```

What Happens
-------------------
```
ninja: Entering directory `builddir'
[0/1] Running external command gnome-recipes-pot.
xgettext: warning: file 'src/ingredients.inc' extension 'inc' is unknown; will try C
xgettext: error while opening "src/ingredients.inc" for reading: No such file or directory
FAILED: meson-gnome-recipes-pot 
/usr/bin/meson --internal commandrunner /home/jeremy/devel/pkg-gnome/gnome-recipes 
/home/jeremy/devel/pkg-gnome/gnome-recipes/builddir po /usr/bin/meson /usr/bin/meson
 --internal gettext pot --pkgname=gnome-recipes
 --extra-args=--flag=g_error_new:3:c-format@@--keyword=C_:1c,2
@@--keyword=NC_:1c,2@@--from-code=UTF-8@@--keyword=N_
@@--flag=g_set_error:4:c-format@@--keyword=_@@--keyword=g_dpgettext2:2c,3
@@--flag=C_:2:pass-c-format@@--add-comments@@--flag=NC_:2:pass-c-format
@@--flag=g_string_append_printf:2:c-format@@--flag=g_dngettext:2:pass-c-format
@@--keyword=g_dngettext:2,3@@--flag=g_strdup_printf:1:c-format
@@--flag=g_string_printf:2:c-format@@--keyword=g_dcgettext:2
@@--flag=N_:1:pass-c-format
ninja: build stopped: subcommand failed.
```

The important error is
```
xgettext: error while opening "src/ingredients.inc" for reading: No such file or directory
```
`builddir/src/ingredients.inc` does exist after the first ninja command.

System Info
--------------
* meson 0.47.2
* Ubuntu 18.10

Other Info
------------
Possibly related to #4352

**Comment by eli-schwartz** [comment] 2020-11-22 23:09
I don't think this can be reasonably done; xgettext is at fault here, it sees `xgettext --files-from=po/POTFILES.in` and treats the file as a list of files to (in turn) read from. There's no logic in xgettext to add an additional directory root in which to try finding referenced files... I guess you could try asking the xgettext developers to add such an option?

Possible (untested) workaround might be to add generated files as `i18n.gettext(args: ...)` to be passed as additional input files to xgettext... seems kind of gross, but not sure how else to handle multiple source roots.

Is there no way to get the translation strings from an in-source file?

**Comment by eli-schwartz** [comment] 2020-11-23 02:57
Duplicate of #1733

**Closed by eli-schwartz** 2020-11-23 02:57 UTC
