### ISSUE TITLE
[RFE] command to list all dependencies

### ISSUE THREAD

**Issue by solomoncyj** [mesonbuild/meson#14000] opened 2024-12-11 12:57 UTC
**Describe the bug**
ommand to list all dependencies

**To Reproduce**

**Expected behavior**
the command will list all dependencies and version constrains, if applicable

**Comment by eli-schwartz** [comment] 2024-12-11 14:20
#9541 
#985

In the first linked bug, this is discussed:
```
meson introspect --dependencies meson.build
```

**Comment by eli-schwartz** [comment] 2024-12-11 14:20
Duplicate of #9541

**Closed by eli-schwartz** 2024-12-11 14:20 UTC
