### ISSUE TITLE
Missing values after running introspection on a build script. 

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6338] opened 2019-12-13 08:31 UTC
**Describe the bug**
Running introspection on build files and getting results like the following.
```js
[{"name": "exe", "id": "613ec74@@exe@exe", "type": "executable", "defined_in": "prog/src/meson.build", "filename": ["prog/src/exe"], "build_by_default": true, "target_sources": [{"language": "unknown", "compiler": [], "parameters": [], "sources": ["/Users/mike/Desktop/GitHub/meson-ui/test-cases/intro/15-intro-scan/prog/src/main.c"], "generated_sources": []}], "subproject": null, "installed": false}]
```
Here you see some values are missing like the programming language.

**To Reproduce**
```meson
project('prog', 'cpp', meson_version: '>=0.52.1')

exe = executable('exe', 'main.cc', install: true)

test('Run test exe', exe)
```

**Expected behavior**
As the user, I expected to not have missing values so Meson-UI does not crash due to missing values or empty arrays and maps.

**system parameters**
* Plain native build (for the same computer)?
* MacOS Catalina
* Python 3.8.0
* Meson `0.52.1`
* Ninja `1.9.0.git.kitware.dyndep-1.jobserver-1`

**Comment by mensinda** [comment] 2019-12-13 12:10
As far as I can tell, there are no actual fields missing in the dicts. If I missed something please specify which keys are missing in the dict / JSON object. Some parameters beeing empty lists is intentional because the necessary information is not available without a build directory.

It is also important to know that the `meson.build` API will likely differ from an actually configured build directory (missing sources, possibly even missing some targets).

If Meson-UI crashes because some values are empty lists, then this is a Meson-UI issue and more checks should be implemented there.

**Comment by michaelbadcrumble** [comment] 2019-12-13 15:19
I thought that at first then I ran the command on my own after running the test just for sanity check and got the following, so currently, not sure what to do.

This would be fantastic to fix before the release of version 0.3.0.

**Comment by michaelbadcrumble** [comment] 2019-12-13 15:25
No missing fields only missing values. The C++ project should return `cpp` from the project command, the compiler should be what Meson finds nativity on the system.

**Comment by mensinda** [comment] 2019-12-13 15:30
The `meson.build` API is very limited (by design) so this can't be easily fixed. This is because the main meson interpreter is not run (and never will be run for the introspection API). Instead, a minimal introspection interpreter is used to gather some basic information as best as possible without actually doing any work (checking the compiler, finding packages, ...).

It does not even "correctly" handle conditions and loops. All lines are processed once and thats it.

An example of what will definitely not happen is finding the compiler that will be used in a normal meson run. This is out of the scope of the introspection interpreter (`== meson.build` API).

**Comment by michaelbadcrumble** [comment] 2019-12-13 15:31
I had jumped back and forth from the API and the introspection scanner to get introspection data from, the scanner for Meson-UI is compatible with or should be compatible with Meson 0.50.0 and up.

**Comment by mensinda** [comment] 2019-12-13 15:39
I am not sure what you are trying to say here.

If you want compatibility with Meson 0.50.0, you should only use the introspection API with a build directory and only offer introspection data for an unconfigured directory within the limits of the file API (specifying the `meson.build` instead of a build directory).

**Comment by michaelbadcrumble** [comment] 2019-12-13 16:10
Currently, the app gives predefined default values and was hoping to change that to dynamically finding with Meson build intro commands.  So not to long ago I added this new intelligence feature.

Link to scanner in fix branch https://github.com/michaelbadcrumble/meson-ui/blob/fix_intro_error/app/src/main/repo/mesonscan.py

**Comment by mensinda** [comment] 2019-12-13 18:08
In that case, I have to say no. As far as I can remember, filling the remaining `--targets` fields with actual data (language, compiler, parameters, etc.) is not in the scope of the file introspection API. It is only meant to give a rough estimate of the project structure with no guarantee for correctness. I basically only added it because 95% of the functionality was already present with the [meson rewriter](https://mesonbuild.com/Rewriter.html).

So, this is more or less a won't fix. I also don't see a reason to add dummy values into the lists. First of all, this would basically be breaking API change, because there might be projects that depend on the lists being empty (explicitly or implicitly). Secondly, all client code should be able to handle that **any** lists in the introspection output may be empty.

**Closed by mensinda** 2019-12-13 18:08 UTC
Labels: introspection
