### ISSUE TITLE
compile_commands.json is not supported by clangd

### ISSUE THREAD

**Issue by mqudsi** [mesonbuild/meson#5597] opened 2019-07-03 16:01 UTC
Running meson 0.51 and clangd-9, the generated `compile_commands.json` generated for a simple project causes an error when clangd attempts to load the compilation database:

> Could not build CompilerInvocation for file 

Sample `meson.build`:

```
project('test', ['cpp'], default_options: ['cpp_std=c++17'])

main = executable('main', ['src.cpp'])
```

which generates the following after `meson build` in `build/compile_commands.json`:

```json
[
  {
    "directory": "/tmp/tmp.0KIa9cgBGZ/build",
    "command": "clang++-9 -Imain@exe -I. -I.. -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -g -march=native -msse4a -mavx2 -mfma -msha -march=native -msse4a -mavx2 -mfma -msha -MD -MQ 'main@exe/src.cpp.o' -MF 'main@exe/src.cpp.o.d' -o 'main@exe/src.cpp.o' -c ../src.cpp",
    "file": "../src.cpp",
    "output": "main@exe/src.cpp.o"
  }
]
```

When `clangd` is run with the correct `--compile-commands-dir` via a text editor plugin, it reports the following:

```
I[11:00:31.911] <-- initialize(1)
I[11:00:31.912] --> reply:initialize(1) 0 ms
I[11:00:31.914] <-- initialized
I[11:00:31.914] unhandled notification initialized
I[11:00:31.915] <-- textDocument/didOpen
I[11:00:31.917] Updating file /tmp/tmp.0KIa9cgBGZ/src.cpp with command 
[/tmp/tmp.0KIa9cgBGZ/build]
clang++-9 --driver-mode=g++ -Imain@exe -I. -I.. -Xclang -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -g -march=native -msse4a -mavx2 -mfma -msha -march=native -msse4a -mavx2 -mfma -msha -o main@exe/src.cpp.o -c ../src.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-9/lib/clang/9.0.0
E[11:00:31.937] Could not build CompilerInvocation for file /tmp/tmp.0KIa9cgBGZ/src.cpp
```

Updating the `compile_commands.json` file and simply deleting all instances of `-Xclang ` (so `:%s/-Xclang //g` and saving, then attempting to call `clangd` again results in it magically working.

It doesn't seem like `-Xclang` is unsupported, but it doesn't work with it. 
Also observed in another project where the output is `-XClang -fcolor-diagnostics`, with same resolution.

**Comment by jpakkane** [comment] 2019-07-03 17:46
If you run the command line manually, does it work? If yes then this is not a bug in Meson, but in Clangd. It should be able to use all the same command lines as clang itself does. That needs to be fixed properly in Clang upstream rather than every downstream project adding hacky workarounds.

**Comment by wbthomason** [comment] 2020-01-05 06:30
This is still an issue I run into. Was it determined that this is a `clangd` bug, not a `meson` bug?

**Comment by eli-schwartz** [comment] 2021-11-24 02:42
This was reported upstream in https://github.com/clangd/clangd/issues/279 and is now fixed.

Meson also stopped emitting -Xclang either way, in #8365

**Closed by eli-schwartz** 2021-11-24 02:42 UTC
