### ISSUE TITLE
[Feature Request] const variables

### ISSUE THREAD

**Issue by Volker-Weissmann** [mesonbuild/meson#8234] opened 2021-01-21 16:56 UTC
Hello,
it would be nice if there would be a `const` keyword so that both
```
const var = 123
var = 124
```
and
```
const var = 123
const var = 124
```
would error out.
This would make reading meson.build files easier, because if you read
```
const var = 123
...
func(var)
```
you know that this calls `func(123)`, without reading the code in between.
(If everything would be const unless specified otherwise, this would be even better, but we can't do that without breaking a lot of code.)

**Comment by eli-schwartz** [comment] 2021-09-26 20:07
Duplicate of #5270

**Closed by eli-schwartz** 2021-09-26 20:07 UTC
Labels: enhancement, parser/interpreter
