### ISSUE TITLE
Cmake subproject target names - filenames

### ISSUE THREAD

**Issue by gizahNL** [mesonbuild/meson#8955] opened 2021-07-03 09:30 UTC
**Describe the bug**
When using a Cmake subproject target names are prefixed with cm_ for namespacing. This in itself is fine, however the target names are then also used as the executable and library sonames, which results in mangled names that are not installable. These also do not match with pkg-config files generated by the Cmake build.

**To Reproduce**
Subproject a Cmake project, compile it and see that it's executable and library filenamea/sonames are overriden

**Expected behavior**
Filenames and sonames as they would've been when using Cmake directly.

**system parameters**
Meson 0.58.1, Ubuntu 21.04

A workable workaround (for me) could also be to be able to override the file/soname on a specific Cmake target.

**Comment by mensinda** [comment] 2021-07-03 09:57
> which results in mangled names that are not installable

Do you have an example project for this? The libraries should still install and be usable by your Meson project. What exactly is your use-case here?

Also, if you want to install a CMake project system-wide, so that it can be used/found by other projects, you really should install the CMake project directly. There are additional issues with installing CMake subprojects, since we do not really track the `install()` function (just some stuff CMake tells us in their introspection data) so the install *will* be incomplete.

So, I would classify this as not a bug but working as intended if your project works after an install with the CMake subproject.

**Comment by gizahNL** [comment] 2021-07-03 11:12
The project I'm trying to build as a subproject is haivision/srt, it has an srt_static target that I'd expect to be output as libsrt.a but instead becomes cm_srt_static.a.

My usecase is building a golang application via a custom target that links against it. Unfortunately the golang linking target is declared in the .go files via cgo directives, so it needs to preserve the name for linking correctly.

Since I build a static library I have a hacked workaround that uses CP as a custom target to produce the expected filename.
But it would be nice if there would be a better solution.

I'm fully aware that my usecase is not supported btw ;)

**Comment by mensinda** [comment] 2021-07-03 11:21
That seems like a somewhat valid use case I guess... Specifying a (possibly empty) prefix shouldn't hurt.

**Comment by mensinda** [comment] 2021-07-04 15:47
Should be fixed by #8964.

**Closed** 2021-07-05 00:04 UTC
Labels: cmake, subprojects/wraps
