### ISSUE TITLE
AttributeError: 'CustomTargetHolder' object has no attribute 'split'

### ISSUE THREAD

**Issue by elmarco** [mesonbuild/meson#4981] opened 2019-02-25 16:41 UTC
I may be trying something wrong, but meson throws an exception at:

```
project('test')

asciidoc = find_program('asciidoc', required : false)
xmlto = find_program('xmlto', required : false)

if asciidoc.found() and xmlto.found()
  xml = custom_target(
    'chezdav XML',
    input : [ 'chezdav.txt' ],
    output : [ 'chezdav.xml' ],
    command : [
      asciidoc,
      '-o',
      '@OUTPUT@',
      '--backend=docbook',
      '--doctype=manpage',
      '@INPUT@',
    ]
  )
  man = custom_target(
    'chezdav MAN',
    input : xml,
    output : [ 'chezdav.1' ],
    command : [
      xmlto,
      'man',
      '@INPUT@',
    ]
  )
  install_man(man)
endif

```

And how should I do it instead? :) thanks

**Comment by nirbheek** [comment] 2019-02-25 16:45
`install_*` functions are only for source files. For installing `custom_target()`, use the `install_dir:` and `install:` keyword arguments.

**Comment by Akaricchi** [comment] 2019-02-26 22:52
>`install_*` functions are only for source files. For installing `custom_target()`, use the `install_dir:` and `install:` keyword arguments.

In this case, Meson should display a proper error message instead of throwing an exception, perhaps?

**Comment by nirbheek** [comment] 2019-02-27 12:15
> In this case, Meson should display a proper error message instead of throwing an exception, perhaps?

Yes, it should. We also need to be more defensive when validating input from Meson API in general.

**Comment by eli-schwartz** [comment] 2020-05-05 02:26
Duplicate of #1550

**Closed** 2020-11-22 21:31 UTC
Labels: support/RFC
