### ISSUE TITLE
meson dist doesn't use uncommitted content

### ISSUE THREAD

**Issue by robert-ancell** [mesonbuild/meson#4277] opened 2018-09-27 23:23 UTC
If you have a project at version 4, make a local change to meson.build to set version 5 then run `meson dist` you get:

`projectname-5.tar.xz` with a `meson.build` that contains version 4.

In general, any uncommitted changes will not be in the tarball (since `meson dist` does a git clone) but local changes will be used from the meson.build.

I'd expect either:
 * The dist to stop until you have committed changes
 * Uncommitted changes to be included
 * Uncommitted changes to not be included, but the version to be taken from the committed changes.

**Comment by nirbheek** [comment] 2018-09-28 02:41
Duplicate of https://github.com/mesonbuild/meson/issues/1977

**Closed by nirbheek** 2018-09-28 02:41 UTC
