### ISSUE TITLE
RFE: add support for iwyu

### ISSUE THREAD

**Issue by kloczek** [mesonbuild/meson#13179] opened 2024-05-03 09:22 UTC
**Describe the RFE**
I think that it would be good to add support for possibility to build project with iwyu (https://github.com/include-what-you-use/include-what-you-use/) as same as `.clang-tidy` target is provided when `clang-tidy` is installed.

**Comment by eli-schwartz** [comment] 2024-05-03 11:19
Duplicate of #2637

**Closed by eli-schwartz** 2024-05-03 11:19 UTC
