### ISSUE TITLE
meson install -C build: ModuleNotFoundError: No module named 'mesonbuild.utils'

### ISSUE THREAD

**Issue by r9-pena** [mesonbuild/meson#13496] opened 2024-07-31 16:23 UTC
**Describe the bug**
I was trying to build the rpicams-apps per the instructions in the raspberry pi site. After executing 
```
$ meson setup build -Denable_libav=disabled -Denable_drm=enabled -Denable_egl=disabled -Denable_qt=disabled -Denable_opencv=disabled -Denable_tflite=disabled
$ meson compile -C build
$ sudo meson install -C build
```
The following error appeared.
```text
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 797, in run
    b = build.load(opts.wd)
  File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2868, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.utils'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```
Everything prior to this error seemed to be working just fine.

**system parameters**
OS: Ubuntu 22.04
python: 3.10.12
meson: 0.61.2-1
ninja: 1.10.1

**Comment by eli-schwartz** [comment] 2024-07-31 16:51
This indicates that you have a different version of meson installed as non-root, which is much newer than the one installed as root.

When you ran `sudo meson install` it ran the different and incompatible meson version. Newer versions of meson know how to detect this and report a coredata version mismatch. Added in https://github.com/mesonbuild/meson/commit/2e3ac3eec00f32dabcfc470cd4c1090303d08e58 / meson 0.63.0 / https://github.com/mesonbuild/meson/pull/9507

Unfortunately, making sure the error message is visible requires the distro-packaged version of meson be the one that gets upgraded to at least 0.63.0 -- at least once Ubuntu 24.04 (noble) becomes the default installed userbase, we will hopefully stop getting these error reports... :)

**Comment by eli-schwartz** [comment] 2024-07-31 16:52
Duplicate of #9507

**Closed by eli-schwartz** 2024-07-31 16:52 UTC

**Comment by eli-schwartz** [comment] 2024-07-31 16:53
Note the mitigation instructions at https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip
