### ISSUE TITLE
AttributeError: 'CustomTarget' object has no attribute 'd_features'

### ISSUE THREAD

**Issue by ling0322** [mesonbuild/meson#10511] opened 2022-06-19 04:56 UTC
**Describe the bug**
AttributeError: 'CustomTarget' object has no attribute 'd_features'

Traceback (most recent call last):
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\msetup.py", line 301, in run
    app.generate()
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\msetup.py", line 185, in generate
    self._generate(env)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\msetup.py", line 229, in _generate
    intr.run()
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2724, in run
    super().run()
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 149, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 574, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2218, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_statement
    self.assignment(cur)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 567, in assignment
    value = self.evaluate_statement(node.value)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 455, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1674, in func_executable
    return self.build_target(node, args, kwargs, build.Executable)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 2986, in build_target
    target = targetclass(name, self.subdir, self.subproject, for_machine, srcs, struct, objs, self.environment, kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\build.py", line 1842, in __init__
    super().__init__(name, subdir, subproject, for_machine, sources, structured_sources, objects, environment, kwargs)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\build.py", line 765, in __init__
    self.process_kwargs(kwargs, environment)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\build.py", line 1183, in process_kwargs
    self.add_deps(deplist)
  File "C:\Users\user001\AppData\Local\Programs\Python\Python39\lib\site-packages\mesonbuild\build.py", line 1356, in add_deps
    dep_d_features = dep.d_features
AttributeError: 'CustomTarget' object has no attribute 'd_features'

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

cmd:
meson -backend vs builddir

meson.build:
    xxx_dll = custom_target(
        'xxx_dll',
        input: meson.source_root() / 'path/to/xxx.dll',
        output: 'xxx.dll',
        command: ['powershell', '-command', 'Copy-Item', '@INPUT@', '@OUTPUT@'])
    executable(
        'xxxcmd',
        sources,
        dependencies: [xxx_dll])

**Expected behavior**
Success

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build
Python: 3.9.9
OS: Windows
meson: 0.62.2

**Comment by eli-schwartz** [comment] 2022-06-19 05:38
Duplicate of #10468

**Closed by eli-schwartz** 2022-06-19 05:38 UTC

**Comment by eli-schwartz** [comment] 2022-06-19 05:40
By the way -- this is not supposed to work, because custom_target isn't valid for the dependencies kwarg.

But it *is* supposed to give you a meaningful error message, not screenfuls of python tracebacks. A fix is already merged to git master which restores the same error message.
