### ISSUE TITLE
problem with setting environment variables

### ISSUE THREAD

**Issue by harikumar6264** [mesonbuild/meson#4224] opened 2018-09-20 06:01 UTC
How can we export environment variables from meson build. I tried with env.set() but its not working.

**Comment by jpakkane** [comment] 2018-09-20 16:01
What exactly are you trying to achieve by setting the environment variables?

**Comment by harikumar6264** [comment] 2018-09-23 06:50
One of driver having dependancy on external library. so I need to export external lib path to driver while compilation

**Comment by harikumar6264** [comment] 2018-09-23 11:17
It is taking in make compilation so, same I need to do in meson.
Currently trying to change compilation from make to meson.
Is there any possibility?

**Comment by jpakkane** [comment] 2018-09-24 16:56
What is the exact environment variable you are setting, what value are you setting it to and what does this achieve, specifically?

**Comment by marc-h38** [comment] 2020-01-15 22:28
It's possible for test, run_command and maybe others:
https://mesonbuild.com/Release-notes-for-0-50-0.html#run_command-accepts-env-kwarg
https://mesonbuild.com/Unit-tests.html#test-parameters

This is likely a duplicate of #266 or #541 or #2723,...
@harikumar6264  can you close as either fixed or duplicate?

BTW https://mesonbuild.com/Contributing.html#environment-variables
> Environment variables are like global variables, except that they are also hidden by default. Envvars should be avoided whenever possible, all functionality should be exposed in better ways such as command line switches.

**Comment by eli-schwartz** [comment] 2021-08-31 20:40
As stated above, meson lets you set environment variables in the definition of various kinds of targets.

On the other hand, if you want your project to define environment variables  which can be used by an external non-meson project, you want [`meson devenv`](https://mesonbuild.com/Commands.html#devenv) instead, and `meson.add_devenv(...)`

**Closed by eli-schwartz** 2021-08-31 20:40 UTC
