### ISSUE TITLE
Meson WRAP Tool Not Functional >0.59: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by magnusmarc** [mesonbuild/meson#10158] opened 2022-03-21 19:41 UTC
Any Meson Wrap commands will fail. GTest also fails to download during a build with the same error when trying to fetch the patch file. This behavior is noticed on meson version >.59 and is consistent across our builds and systems.

Wrap will download legacy wrap files, but some newer wrap files (like gtest) will fail to download.

Only workaround is to use legacy meson versions for any wrap based commands or builds. Have tried several other methods for refereshing the keys, but none seem to work.

The version of meson this reproduced on was 0.61.2 & 0.61.3

```
root@cc757c7f7ccf:/sysapp# meson wrap list
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1446, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/wrap/wraptool.py", line 223, in run
    options.wrap_func(options)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/wrap/wraptool.py", line 66, in list_projects
    releases = get_releases()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/wrap/wraptool.py", line 62, in get_releases
    url = urlopen('https://wrapdb.mesonbuild.com/v2/releases.json')
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!



```

**Comment by eli-schwartz** [comment] 2022-03-21 19:45
Duplicate of #10135

**Closed by eli-schwartz** 2022-03-21 19:45 UTC

**Comment by eli-schwartz** [comment] 2022-03-21 19:52
Note that the error message itself is wrong, and I have a pending PR to fix it (which will in addition print the url itself).

The url in question is https://wrapdb.mesonbuild.com/ and should be accessible in a browser, but if your python installation shares a certificate store with your browser (as is typical on linux) I'd expect both to be broken...

It does work here, so if it doesn't work for you in a browser then that does mean your system certificate store is out of date or lacks the letsencrypt trust root.

**Comment by magnusmarc** [comment] 2022-03-21 20:00
@eli-schwartz , this is on a brand new installation of Ubuntu (2 days old). The URL is accessible in the browser. Why would the base ubuntu lack the trust root for letsencrypt? I don't see the behavior on .59 and this only started happening recently.

Are there more outstanding requirements to install meson beyond the initial pip3 install? The issue was also on all of our existing systems as well.

**Comment by eli-schwartz** [comment] 2022-03-21 20:06
The code doing this is:

https://github.com/mesonbuild/meson/blob/adc509ed98694d3c7a7b0c578c94cb3a886c21eb/mesonbuild/wrap/wraptool.py#L61-L68

It is just:
```python
from urllib.request import urlopen
urlopen('https://wrapdb.mesonbuild.com/v2/releases.json')
```

Apparently this code is failing on your system when run internally by Meson. Does it also fail if you interactively run `python3.6` and run this code from there?

**Comment by magnusmarc** [comment] 2022-03-21 20:55
@eli-schwartz , you are right. I did some further digging and it looks like an intermediary certificate issuer was the problem that occurred recently. Thanks for your help! 👍 I think the changes to have more descriptive errors that you have done will be very useful. Firefox gave a more detailed error message on where it failed and I could inspect the certificate as well--leading to the issue.

The URL you posted above was the one that caused the issue internally, but not the previous one (without the v2).

```
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> urlopen('https://wrapdb.mesonbuild.com/v2/releases.json')
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1446, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> urlopen('https://wrapdb.mesonbuild.com/v2/releases.json')
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)
```

**Comment by eli-schwartz** [comment] 2022-03-21 21:18
Right. The v2 API is needed for current versions of available wraps, as the v1 API is deprecated and only contains a snapshotted archive of the wrapdb state at the time we switched over.

And that was indeed introduced in 0.59.0 via commit 62c53b834dbee366104dc8a32927f1b7da028922.
The new version redirects to GitHub releases which I guess might be the issue.
