### ISSUE TITLE
Please be clear about `warning_level`

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#11469] opened 2023-02-27 15:25 UTC
### Discussed in https://github.com/mesonbuild/meson/discussions/11468

<div type='discussions-op-text'>

<sup>Originally posted by **mobin-2008** February 27, 2023</sup>
Hi. 
`warning_level` option is documented in https://mesonbuild.com/Builtin-options.html#core-options but this page doesn't give much information about `warning_level`s.
I mean why it's not give me information about every level enable which flags? there is any platform/compiler specific flag? or some older/newer versions of meson enable/disable some additional flags?
I think these things need to be documented.

Regards</div>

**Comment by eli-schwartz** [comment] 2023-02-27 20:58
Duplicate of #7748

**Closed** 2023-02-28 19:01 UTC
