### ISSUE TITLE
0.50.1: meson redirects stderr to stdout

### ISSUE THREAD

**Issue by kloczek** [mesonbuild/meson#5316] opened 2019-04-24 09:29 UTC
Looks like meson redirects stderr to stdout.

Building gnome-contacts I found that new released version emits a lot ow warnings so usual way on building rpm package to have only warnings is add use --quiet rpmbuild option which redirects stdout to /dev/null.
So I made:

<pre>[tkloczko@domek SPECS]$ rpmbuild -ba --clean --rmsource --rmspec gnome-contacts.spec --quiet
cpio: x86_64-redhat-linux-gnu/contacts-accounts-list.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-app.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-avatar-selector.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-avatar.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact-editor.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact-form.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact-list.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact-pane.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact-sheet.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-contact.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-crop-cheese-dialog.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-esd-setup.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-fake-persona-store.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-in-app-notification.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-link-suggestion-grid.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-linked-personas-dialog.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-linking.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-list-pane.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-max-width-bin.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-settings.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-setup-window.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-shell-search-provider.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-store.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-type-combo.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-type-descriptor.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-typeset.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-ui-state.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-utils.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-vcard-type-mapping.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/contacts-window.c: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/glib-2.0.vapi: Cannot stat: No such file or directory
cpio: x86_64-redhat-linux-gnu/main.c: Cannot stat: No such file or directory
5499 blocks
[</pre>
And as you see there is no even single line about compile time warnings printed in above output.
looks like stderr is redirected to the /dev/null.
rpmbuild --quiet works OK when I'm building autoconf/automake based package so it is kind of indirect prove that meson (or ninja because I'm using ninja with meson on building gnome-contacts) does this.

**Comment by QuLogic** [comment] 2019-04-24 09:42
What does the `--quiet` option to `rpmbuild` have to do with Meson? You'll need to be more specific about what you think is wrong here.

**Comment by kloczek** [comment] 2019-04-24 10:38
rpmbuild --quiet option has nothing to do with meson. It is only example.
Look on title of this ticket. This ticket is about fact that meson generates ninja files which redirects stderr to stdout.

**Comment by eli-schwartz** [comment] 2019-04-24 16:41
meson doesn't generate ninja files which anything. Ninja itself, *by design*, redirects stderr to stdout. It doesn't matter where you get the ninja files from, or whether they are generated by meson or any other generator vs. written by hand -- ninja is the thing which redirects stderr.

Please close this issue and open a new one in the ninja project. Actually, don't open one for ninja either -- just join existing discussions like https://github.com/ninja-build/ninja/issues/1537

**Comment by kloczek** [comment] 2019-04-24 16:49
OK. Thanks for explanation :)

**Closed** 2019-04-24 16:48 UTC
