### ISSUE TITLE
cpp_std not portable across compilers

### ISSUE THREAD

**Issue by Apache-HB** [mesonbuild/meson#8246] opened 2021-01-24 02:01 UTC
**Describe the bug**
no single `cpp_std` value for c++20 works across clang, gcc, and msvc

**To Reproduce**
```py
project('example', 'cpp', default_options : [ 'cpp_std=c++20' ])
# should work according to https://mesonbuild.com/Builtin-options.html#compiler-options
# but doesnt on any compiler
```

```py
project('example', 'cpp', default_options : [ 'cpp_std=c++1z' ])
# shouldnt work at all but works on linux gcc/clang++
```

```py
project('example', 'cpp', default_options : [ 'cpp_std=c++latest' ])
# shouldnt work at all but works on cl.exe
```

**Expected behavior**
* setting `cpp_std=c++20` should attempt to use c++20 across all compilers
* setting `cpp_std=c++latest` should always use the latest standard supported by the compiler

**system parameters**

## windows 
* meson 0.56.1
* windows 10

## linux
* meson 0.56.2
* ubuntu 20.04 (WSL1)

**Comment by eli-schwartz** [comment] 2021-01-24 02:31
I'm pretty sure these are just directly passed to the compiler as `-std=<value>` (or `/std:<value>`), after some autodetection to see if it is supported and some handpicked fallbacks.

Speaking of `c++1z`, why shouldn't it work? It's in my GCC manpage, admittedly as "deprecated". For the record, this means c++17, so not sure why it's in your comparison.

Which compiler supports `-std=c++latest`? Just MSVC I'm pretty sure?

Why doesn't c++20 work for you? It's in my manpage as supported! Could it be... that you're using ubuntu 20.04 with GCC 9, and this was only added to GCC 10? Unsurprisingly, older compilers often don't support the very latest std, though admittedly it's disappointing that Ubuntu LTS included the version from March without c++20 rather than the version from May *with* it.

**Comment by Apache-HB** [comment] 2021-01-25 16:53
> Speaking of c++1z, why shouldn't it work?

`c++1z` is not a listed option in <https://mesonbuild.com/Builtin-options.html#compiler-options> which i why i stated that it shouldnt work.

> Why doesn't c++20 work for you? It's in my manpage as supported! Could it be... that you're using ubuntu 20.04 with GCC 9, and this was only added to GCC 10? 

Yes, i am using gcc 9 and clang++ 10. neither support `-std=c++20`, expected behaviour would probably be to fallback to `-std=c++1z` if `-std=c++20` isnt supported.

**Comment by eli-schwartz** [comment] 2021-01-25 17:08
meson doesn't document any sort of fallbacks to "most recently supported std", and if your project requires c++20 then it would be completely wrong to silently modify the build config to use something insufficient, just because your compiler doesn't support it.

So I would call that extremely unexpected behavior.

What you actually want is for a new, never-before seen meson feature to be ADDED.

Note: that cannot and will not be `c++latest`, because it is already used by MSVC to mean something very different, that does not do fallback.

**Comment by jmoguillansky-gpsw** [comment] 2021-01-25 22:40
I submitted the same issue:

https://github.com/mesonbuild/meson/issues/8140

**Comment by jmoguillansky-gpsw** [comment] 2021-01-25 22:41
Meson should support setting cpp_std using conditional logic.

**Comment by eli-schwartz** [comment] 2021-01-25 22:51
Duplicate of #8140

**Closed by eli-schwartz** 2021-01-25 22:51 UTC
