### ISSUE TITLE
Question: Where are c_std and cpp_std flags logged?

### ISSUE THREAD

**Issue by stefanos82** [mesonbuild/meson#3734] opened 2018-06-11 23:48 UTC
I run `ninja -v -C builddir` command and didn't see any `-std=c89` or `std=c++14` flags in output of two separate projects.

Aren't those commands supposed to be logged as well?

By the way, this is what is inside `compile_commands.json` file of my C project; I'm beautifying it for reading purposes:
```json
[
  {
    "directory": "/home/stefanos/tmp/c_projects/dokimi/builddir",
    "command": "ccache cc -Idemo@exe -I. -I.. -I../include 
    -fdiagnostics-color=always -pipe 
    -D_FILE_OFFSET_BITS=64 
    -Wall -Winvalid-pch -Wextra -Wpedantic 
    -O0 -g  -MD -MQ 'demo@exe/src_main.c.o' 
    -MF 'demo@exe/src_main.c.o.d' -o 'demo@exe/src_main.c.o' -c ../src/main.c",
    "file": "../src/main.c"
  }
]
```
Is this the expected behavior?

**Comment by NickeZ** [comment] 2018-06-12 07:14
Did you change the default options? And in that case did you wipe the build directory after changing it?

**Comment by stefanos82** [comment] 2018-06-12 11:40
@NickeZ Here's what I have in my meson.build:

```python
project(
    'demo',
    'c',
    version: '0.1',
    default_options: [
        'c_std=c89',
        'warning_level=3'
    ]
)

sources = ['src/main.c']
inc = include_directories('include')

executable(
    'demo', 
    sources,
    include_directories : inc,
    install: true
)
```

**Comment by NickeZ** [comment] 2018-06-12 12:22
If you first generated with

```
project(
    'demo',
    'c',
    version: '0.1',
)
```

and then modified the file to:

```
project(
    'demo',
    'c',
    version: '0.1',
    default_options: [
        'c_std=c89',
        'warning_level=3'
    ]
)
```

You have to wipe the build directory. This is a "feature" not a bug according to @jpakkane .

**Comment by stefanos82** [comment] 2018-06-12 12:41
This is a very strange behavior. As I said, I typed the aforementioned `meson.build` first and then generated the `builddir`.

Now that I have removed it and regenerated it, it works as expected.

Is this normal or just happens from time to time?

**Comment by NickeZ** [comment] 2018-06-12 15:32
> Is this normal or just happens from time to time?

That should not happen. If you can find a way to reproduce it you should file a bug.

However, the fact that `default_options` never are applied to existing projects is a feature.

**Comment by NickeZ** [comment] 2018-06-12 15:34
See #2193

**Comment by stefanos82** [comment] 2018-06-12 15:50
Ah I see. So it's a common issue, not just my case.

**Comment by nirbheek** [comment] 2018-06-20 05:08
This will be fixed by https://github.com/mesonbuild/meson/pull/3739.

**Closed** 2018-06-20 21:56 UTC
Labels: support
