### ISSUE TITLE
Dlang linker to be determined issue on Mac OSX

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6249] opened 2019-11-27 16:58 UTC
**Describe the bug**
I ran into some issues with the D projects not being built by Meson and did the experimental work.  The problem seems to be on Mac because my D projects work on Windows and Linux without complaining about what linker to use even with a basic executable like hello world.

**To Reproduce**
```meson
project('prog', 'd', default_options: ['warning_level=3', 'werror=true'])
lang = 'd'
dc = meson.get_compiler(lang)

add_project_arguments(dc.get_supported_arguments(['-de', '-w', '-wi']), language: lang)

exe = executable(meson.project_name(), 'main.d')

benchmark('run benchmark on prog exe:', exe)
test('run test case on prog exe:', exe)
```

```d
module main;
import std.stdio;


/**
 * This source code demonstrates a simple hello world program where the message
 * printed is "Hello, D Developer" displayed to the standard output console.
 */
void main()
{
    writeLn("Hello, D Developer.");
}/* end of function main */

```

**Expected behavior**
I expect that the D support would build my project and not have the following error message:
```console
Build started at 2019-10-18T15:18:42.928969
Main binary: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
Build Options: 
Python system: Darwin
The Meson build system
Version: 0.52.0
Source dir: /Users/shnitzel/Developer/templates/dlang/d-program
Build dir: /Users/shnitzel/Developer/templates/dlang/d-program/builddir
Build type: native build
Project name: d-exe
Project version: 0.1.0

meson.build:15:0: ERROR: Unable to determine dynamic linker.
```

**system parameters**
Not a cross build 
MacOS Catalina
Python 3.8.0
Meson 0.52.0
Ninja 1.9.0

**Comment by michaelbadcrumble** [comment] 2019-11-30 21:41
It continues to be an issue throughout Meson beta 0.52.1 https://travis-ci.org/michaelbadcrumble/d-project

**Comment by dcbaker** [comment] 2019-12-03 00:41
I believe this is a duplicate of #6075

**Closed by dcbaker** 2019-12-03 00:41 UTC
Labels: D language
