### ISSUE TITLE
Have a friendlier error message when -C option is missing

### ISSUE THREAD

**Issue by federicomenaquintero** [mesonbuild/meson#9875] opened 2022-01-25 19:09 UTC
**Describe the bug**
I frequently do this by mistake:
```
meson setup _build
meson compile _build
```
The error message from the second command is a Python traceback instead of telling me something like `please use the -C _build` option.

**To Reproduce**

```
$ meson setup _build
... success ...

$ meson compile _build
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 138, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mcompile.py", line 324, in run
    cdata = coredata.load(options.wd)
  File "/usr/lib/python3.8/site-packages/mesonbuild/coredata.py", line 1030, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/federico/src/librsvg/mesonify/meson-private/coredata.dat'
```

**Expected behavior**
It would be useful if instead of a Python exception traceback, meson would tell me that I forgot the `-C` option for `compile`.  Maybe it can see that `_build` already exists as created by `meson setup _build`?

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? - Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) - openSUSE Tumbleweed
* what Python version are you using - 3.8.12
* what `meson --version` - 0.60.3

**Comment by eli-schwartz** [comment] 2022-01-25 20:31
Duplicate of #9584

**Closed by eli-schwartz** 2022-01-25 20:31 UTC

**Comment by eli-schwartz** [comment] 2022-01-25 20:36
```
meson compile _build
```

Meson compile is a straight alias for ninja. This equates to 

```
ninja _build
```

But meson checks to see if it is a build directory before ninja then does a similar check. Meson crashes, even though it's not supposed to and actually regressed from a previous version of meson.

The command should error out if the current working directory is not a build directory. If it is a build directory, it should try to build the ninja target named `_build` (it is doubtful you have a custom_target of that name, but theoretically possible).

So while meson already has (non-functional, fixed by the PR linked in the ticket this is a duplicate of) code to print an error recommending you specify the build directory using the -C option, I don't believe it is in scope to detect that the first positional argument is a build directory and suggest that by name.
