### ISSUE TITLE
Cached results is used after .pc file is updated

### ISSUE THREAD

**Issue by yshui** [mesonbuild/meson#4599] opened 2018-12-07 16:09 UTC
After a pkg-config file is updated, meson did not immediately pick up the updated include path, lib path, etc. Instead, when forced to reconfigure, meson will say:

```
Dependency xxx found: YES (cached)
```

Otherwise, meson won't even try to reconfigure.

**Comment by nirbheek** [comment] 2018-12-07 16:21
Duplicate of https://github.com/mesonbuild/meson/issues/382

**Closed by nirbheek** 2018-12-07 16:21 UTC
