### ISSUE TITLE
pkgconfig.generate(): accept dependency() and find_library() objects 

### ISSUE THREAD

**Issue by Nikratio** [mesonbuild/meson#1298] opened 2017-01-12 18:31 UTC
pkgconfig.generate() should accept dependency() and find_library() objects for the *libraries* and *private_libraries* arguments. See https://groups.google.com/forum/#!topic/mesonbuild/Wq9Aa5z_-rA.

**Comment by ignatenkobrain** [comment] 2017-01-12 18:32
Dupe of #1206

**Closed by ignatenkobrain** 2017-01-12 18:32 UTC
