### ISSUE TITLE
Button "Edit on github" for documentation gives 404 status code

### ISSUE THREAD

**Issue by radioactiveman** [mesonbuild/meson#8149] opened 2021-01-04 01:37 UTC
**Describe the bug**
The base URL for the "Edit on github" button in the Meson documentation is wrong, hence the links are not working.

**To Reproduce**
Click the button on any page of the [Meson documentation](https://mesonbuild.com/).

**Expected behavior**
- Link works
- github should also be written as GitHub

**Comment by eli-schwartz** [comment] 2021-01-04 01:51
Duplicate of #8061

**Closed by eli-schwartz** 2021-01-04 01:51 UTC

**Comment by eli-schwartz** [comment] 2021-01-05 02:29
Incidentally, despite this being a duplicate, it *did* prod me into pinging for a status update on the original issue... and I got enough info to try to fix this, which I believe I've successfully done (PR awaiting reviewer that isn't me before merging, so it's not live yet).

Not sure if I should thank you for filing this, or refrain from encouraging duplicates... :thinking:

:p

**Comment by radioactiveman** [comment] 2021-01-05 02:55
Sounds great. :+1:
If you know now where the button label is created, you may also fix the wrong capitalization of GitHub.
> github should also be written as GitHub

In any case, thanks for your efforts.

**Comment by eli-schwartz** [comment] 2021-01-05 03:13
> fix the wrong capitalization of GitHub.

https://github.com/hotdoc/hotdoc/blob/83d0c70ecb9e0224ec67dcf7c6c5cfee8d049288/hotdoc/extensions/edit_on_github/edit_on_github_extension.py#L99-L103

This is not done by us, no can do. Please open a hotdoc bug report for this. :)

**Comment by radioactiveman** [comment] 2021-01-05 03:49
> Please open a hotdoc bug report for this. :)

Done, see https://github.com/hotdoc/hotdoc/issues/215.
