### ISSUE TITLE
Create build targets named as directories

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#5934] opened 2019-09-18 12:21 UTC
When you have a well structured source tree, with `app/`, `libgimp/`, `plug-ins/` and such, it is common to want to build only a specific subtree. For instance: just rebuild everything under `app/` not bothering about other pieces of the source.
Unfortunately meson does not create such directory-named targets:

```
$ ninja app
ninja: error: unknown target 'app', did you mean 'all'?
```

It only creates much more specific targets for instance I could run successfully `ninja app/gimp-2.99` to build the main binary.

**Feature request**: create a target for every `subdir()`

**Comment by QuLogic** [comment] 2019-09-18 23:36
Duplicate of #4977.

**Comment by eli-schwartz** [comment] 2021-11-24 01:24
Duplicate of #4977

**Closed by eli-schwartz** 2021-11-24 01:24 UTC
