### ISSUE TITLE
Non-existent keyword arguments don't give error

### ISSUE THREAD

**Issue by Timmmm** [mesonbuild/meson#1869] opened 2017-05-30 10:09 UTC
This:

    project('foo', versionn: '1.2.3')
    message(meson.project_version())

Will print:

    message: undefined

It should print an error about `versionn` not being a valid keyword argument.

**Comment by QuLogic** [comment] 2017-05-30 10:15
Dupe of #789.

**Closed** 2017-05-31 04:53 UTC
