### ISSUE TITLE
Cannot pass compiler to first argument of custom_target(command:)

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#10169] opened 2022-03-23 14:38 UTC
**Describe the bug**
```
ERROR: custom_target keyword argument 'command' was of type array[CythonCompiler | str] but should have been array[str | BuildTarget | CustomTarget | CustomTargetIndex | ExternalProgram | File] that cannot be empty
```

Cannot pass compiler to first argument of `custom_target(command:)`

**To Reproduce**
```
project('test', 'cython')

cython = meson.get_compiler('cython')

custom_target(
  'test',
  command: [
    cython,
    # ...
  ],
  # ...
)
```

**Expected behavior**
Be able to pass a compiler to `custom_target(command:)`

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Fedora 35
* what Python version are you using e.g. 3.8.0 3.10
* what `meson --version` 0.62
* what `ninja --version` if it's a Ninja build 1.10

**Comment by xclaesse** [comment] 2022-03-23 14:46
You can do `cython.cmd_array()` but I agree it could be made to just work.

**Comment by tristan957** [comment] 2022-03-23 14:47
Oh good point. I think I have done that in the past. Just slipped my mind. Let me look into this.

**Comment by bruchar1** [comment] 2023-02-26 03:13
Duplicates #8373.

**Comment by eli-schwartz** [comment] 2023-02-26 03:47
Duplicate of #8373

**Closed by eli-schwartz** 2023-02-26 03:47 UTC
