### ISSUE TITLE
In dependencies requires gobject-introspection but meson dont can find it

### ISSUE THREAD

**Issue by friktor** [mesonbuild/meson#2273] opened 2017-09-02 17:41 UTC
Im getting this error line:
_gobject-introspection dependency was not found, gir cannot be generated._
But i have gobject-introspection in my pkg-config list.
```
pkg-config --libs gobject-introspection-1.0
-L/usr/local/Cellar/gobject-introspection/1.52.1_1/lib -L/usr/local/Cellar/glib/2.52.3/lib -L/usr/local/opt/gettext/lib -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
```
Target OS build - Mac OS Sierra

**Comment by TingPing** [comment] 2017-09-02 23:18
It needs the g-i tools not the library, and i imagine the tools are not in PATH.

**Comment by nirbheek** [comment] 2017-09-04 11:40
The error message should be fixed to specifically say which tool is missing.

**Comment by TingPing** [comment] 2017-09-04 12:49
We might even be able to do better in this case. the `gobject-introspection-1.0` pkg-config file contains absolute paths to its tools.

**Comment by TingPing** [comment] 2017-09-04 13:21
Ok so I was wrong about this error being because of missing tools and it is indeed failing to look up the `'gobject-introspection-1.0'` pkgconfig.

**Comment by friktor** [comment] 2017-09-04 16:48
@TingPing this bug reproduce only on Mac OS? How i can fix this problem? Or this bug into meson?

**Comment by TingPing** [comment] 2017-09-04 17:04
Meson just calls `pkg-config` directly so for some reason it is failing to find it and I would say that is unique to your environment.

**Comment by friktor** [comment] 2017-09-04 21:45
@TingPing but if PkgConfig just call from my env - why meson dont find gobject? Mac it is like Linux... but Mac

**Comment by niedzielski** [comment] 2018-01-13 18:01
This issue does not appeared to be limited to macOS. I'm seeing it on Ubuntu v17.10 with Meson v0.42.1:

```
$ dpkg -l gobject-introspection
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version      Architecture Description
+++-=====================-============-============-===========================================================
ii  gobject-introspection 1.54.1-1     amd64        Generate interface introspection data for GObject libraries

$ which g-ir-compiler g-ir-scanner
/usr/bin/g-ir-compiler
/usr/bin/g-ir-scanner

$ dpkg -s gobject-introspection
Package: gobject-introspection
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 1430
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 1.54.1-1
Depends: libc6 (>= 2.14), libffi6 (>= 3.0.4), libgirepository-1.0-1 (= 1.54.1-1), libglib2.0-0 (>= 2.54.0), python3:any, build-essential, python3-mako
...
```

**Comment by tcitworld** [comment] 2018-01-28 21:03
@niedzielski Debian Sid needed `libgirepository1.0-dev`.

**Comment by axis78** [comment] 2018-05-01 11:03
sudo dnf install gobject-introspection-devel on Fedora 27

**Comment by davibe** [comment] 2018-09-11 06:29
same here, is there a osx workaround

**Comment by ljmf00** [comment] 2018-09-11 22:28
@davibe macOS is not my operation system, I just use it to test releases and code to work on cross platform, so I just figured it out because of  #4132 . I can test it on High Sierra too, but whats your macOS version? Because your problem was not that, at all. The thing is `pkg-config` can find it but `meson` dont.

**Comment by davibe** [comment] 2018-09-12 05:57
@ljmf00 in my case pkg-config `--libs` was able to find gobject-introspection-1.0 just fine but `--cflags` failed with that error, which is the same as not finding it
Infact i got the very same error you have with meson. It could be a different case but i think its worth doublechecking 

I am using high sierra 10.13.6

**Comment by prometheansacrifice** [comment] 2018-11-25 17:57
@davibe 's [suggestion](https://github.com/mesonbuild/meson/issues/2273#issuecomment-420412230) worked for me. Thank you.

**Comment by claucece** [comment] 2019-03-28 15:19
This might help here:

In my case I did the `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"` as well; but I noticed that it was not finding it when using as a dependency of glib. When I switched the current version of glib (2.60) to an older one (2.56), everything worked correctly in my project (OTRv4 in pidgin).

**Comment by nefuddos** [comment] 2019-04-26 07:24
this is the same error with my situation in os: ubuntu 16.04.5
`gobject-introspection dependency was not found, gir cannot be generated.`

and when i check meson-logs/meson-log.txt. it shows:
`Determining dependency 'gobject-introspection-1.0' with pkg-config executable '/usr/bin/pkg-config'

Meson encountered an error in file atk/meson.build, line 143, column 8:
gobject-introspection dependency was not found, gir cannot be generated`

i try to install libgirepository1.0-dev: 
`sudo apt-get install libgirepository1.0-dev`

it works.

**Comment by yuzaipiaofei** [comment] 2019-05-21 15:14
Program(s) ['g-ir-scanner'] not found  in Ubuntu 18.04
i try to install libgirepository1.0-dev:
sudo apt-get install libgirepository1.0-dev

it works.

**Comment by flyingpimonster** [comment] 2019-06-27 21:36
I tried @davibe's solution of putting libffi in the PKG_CONFIG_PATH on macOS, but it's still not working. It looks like #2400 might be why.

**Comment by grimmy** [comment] 2019-07-15 20:52
> I tried @davibe's solution of putting libffi in the PKG_CONFIG_PATH on macOS, but it's still not working. It looks like #2400 might be why.

I've added some findings to #2400, I'm still looking for a solution, but I found why it's not working, I just don't understand why that value is missing.

**Comment by JeyP4** [comment] 2019-12-02 17:05
> Program(s) ['g-ir-scanner'] not found in Ubuntu 18.04
> i try to install libgirepository1.0-dev:
> sudo apt-get install libgirepository1.0-dev
> 
> it works.

Instead better
sudo apt-get install gobject-introspection

**Comment by eli-schwartz** [comment] 2021-12-19 16:02
Current versions of meson do get the tools from pkg-config. There's nothing we can do about missing development dependencies such as libffi.

I'm assuming this is either fixed or not a meson bug, but please feel free to re-open it if you can still reproduce the problem.

**Closed by eli-schwartz** 2021-12-19 16:02 UTC
Labels: bug, gnome, OS:macos, dependencies

**Comment by barracuda156** [comment] 2024-01-16 05:46
@eli-schwartz There are still issues with meson being unable to find installed dependencies which pkgconfig does find, and even losing dependencies on the way: specifically, I cannot build `libnotify` now whatever I try, since even though `meson` sees Glib2 at configure, it all of a sudden cannot find it when generating gtk docs.

**Comment by ernstki** [comment] 2024-12-24 13:21
Here's another example from the wild, attempting to build PyGObject, a dependency of [mat2](https://0xacab.org/jvoisin/mat2):

```console
$ pipx install mat2
Fatal error from pip prevented installation. Full pip output in file: 
    /users/me/.local/pipx/logs/cmd_2024-12-24_07.22.25_pip_errors.log
                                                                                                                                                                                
pip failed to build package:        
    PyGObject                                                                                                                                                                   
                                        
Some possibly relevant errors from pip install:                                                                                                                                 
    ../meson.build:29:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.
                                                                                                                                                                                
Error installing mat2.

$ tail /users/me/.local/pipx/logs/cmd_2024-12-24_07.22.25_pip_errors.log
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-cpython-38/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-cpython-38/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-cpython-38/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-cpython-38/gi/overrides
  running build_ext
  Requested 'glib-2.0 >= 2.64.0' but version of GLib is 2.56.1
  Command '('pkg-config', '--print-errors', '--exists', 'glib-2.0 >= 2.64.0')' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects
```

The _real_ error is the unsatisfied requirement for `glib-2.0 >= 2.64.0`, nothing at all to do with gobject-introspection, or its pkg-config configuration, which was totally fine in my case:

```console
$ pkg-config --libs gobject-introspection-1.0
-lgirepository-1.0 -lgobject-2.0 -lglib-2.0
```

I have meson 1.6.1, which is the latest tagged release as of this writing.

**Comment by eli-schwartz** [comment] 2024-12-24 14:07
> The *real* error is the unsatisfied requirement for `glib-2.0 >= 2.64.0`, nothing at all to do with gobject-introspection

Can you explain the connection to this ticket, then?

Preferably with full logs, not small extracts which contain no useful information for analysis.

**Comment by ernstki** [comment] 2025-01-19 14:55
@eli-schwartz Adding more context to help others who find themselves in these circumstances, and land here, having done a web search for the error message.

What bits of logs I included were only the relevant parts. I apologize if I haven't done the right thing, as I'm just approaching this from the perspective of an end user building software that happens to use meson, not as a developer myself.

**Comment by eli-schwartz** [comment] 2025-01-19 16:49
> What bits of logs I included were only the relevant parts. I apologize if I haven't done the right thing, as I'm just approaching this from the perspective of an end user building software that happens to use meson, not as a developer myself.

I'm sorry, but the reason I said to include the full logs, not "only the relevant parts" is because this is the number one mistake made by end users building software who aren't developers themselves.

Incorrectly analyzing developer-oriented functionality and making the mistake of thinking they know what the relevant parts are.

I've seen it described once as such:
> If you're asking for help, you inherently acknowledge you lack an understanding of the problem you're trying to solve. It's therefore a bit arrogant, in a sense, to claim you *do* know what is relevant and what is not. Just post the full logs and allow the experts you are asking to share their expertise, to use that expertise and decide what is relevant. You'll never be reprimanded for posting too much, and the developers who know what is relevant will simply skip over whatever they know isn't relevant.

Anyways you appear to be mixing error messages from two different versions of PyGObject, one which doesn't even use Meson at all (that is the one that seems to be failing due to `glib-2.0 >= 2.64.0`, since its error message format is not the error message format used by Meson).

**Comment by ernstki** [comment] 2025-01-19 18:49
@eli-schwartz Good points. I will bear this in mind next time. Thanks for your patience and feedback.
