### ISSUE TITLE
meson 0.47.2 test failure with glib 2.58

### ISSUE THREAD

**Issue by jbicha** [mesonbuild/meson#4115] opened 2018-09-02 17:10 UTC
When meson 0.47.2 is built with glib 2.58, I get this test failure:

```
======================================================================
FAIL: test_introspect_dependencies (__main__.LinuxlikeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run_unittests.py", line 3444, in test_introspect_dependencies
    self.assertEqual(t['filename'], 'gdbus/generated-gdbus-doc-' + ifile)
AssertionError: 'gdbus/generated-gdbus-doc-com.example.Sample.xml'
 != 'gdbus/generated-gdbus-doc-gdbus/data/com.example.Sample.xml'
- gdbus/generated-gdbus-doc-com.example.Sample.xml
+ gdbus/generated-gdbus-doc-gdbus/data/com.example.Sample.xml
?                           +++++++++++
```

Full build log
---------------
https://launchpad.net/ubuntu/+source/meson/0.47.2-1ubuntu1/+build/15323231

Other info
-------------
glib 2.58 has just been uploaded to Debian today.

**Comment by nirbheek** [comment] 2018-09-02 17:14
Duplicate of https://github.com/mesonbuild/meson/issues/4083

**Closed by nirbheek** 2018-09-02 17:14 UTC
