### ISSUE TITLE
Meson test times out unless -v option is passed

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#8212] opened 2021-01-16 19:22 UTC
**Describe the bug**
`meson test` times out when it shouldn't, but `meson test -v` executes correctly. It looks like the test is somehow suspended and kept in a suspended state until it times out, because my program randomly stops producing output during the test.

**To Reproduce**
This is the test I am running from the [Zrythm repository](https://git.sr.ht/~alextee/zrythm), commit 99697cc5dddfd6584d780839aec7d4c1f6850dba.
`meson test -C build actions_arranger_selections`
It times out after 240 seconds.

The same issue occurs when doing `ninja -C build test`

When running the same test with `-v`, it finishes in 132.27s
`meson test -C build -v actions_arranger_selections`

*note: When using meson 0.55.1 (guix package), I do not experience this bug, and the test finishes without issues.*

**Expected behavior**
The test is expected to finish without timing out.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Tested on GNU GuixSD and Arch Linux
* what Python version are you using: Python 3.8.2
* what `meson --version` Commit ea2f34e2860680bab82aa7c2538971ab788209ce
* what `ninja --version` if it's a Ninja build: 1.10.0

**Comment by dcbaker** [comment] 2021-01-19 19:27
@bonzini, this looks like a possible regression from the switch to asyncio.

**Comment by bonzini** [comment] 2021-01-19 20:11
A likely issue is that 755412b5261c448025d40214e3f2c0197e2e27bc awaits stdout before stderr---but the program hangs on a write to stderr, and therefore won't close stdout yet.

If so, #8200 fixes it.

**Comment by bonzini** [comment] 2021-01-20 14:19
@alex-tee Could you test the #8225 pull request, please?

**Comment by alex-tee** [comment] 2021-01-20 14:29
@bonzini looks like it passed

```
1/1 zrythm:actions / actions_arranger_selections        OK             156.17s
```

**Comment by bonzini** [comment] 2021-01-20 19:12
Fixed in master, please close.

**Closed** 2021-01-20 19:14 UTC
Labels: regression, test targets
