### ISSUE TITLE
Meson not preserving core dumps (or wrongly reporting SIGSEGV) for tests

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/meson#9069] opened 2021-08-06 14:41 UTC
**Describe the bug**

- When running ```meson test``` in my scenario, it frequently reports that tests have failed with SIGSEGV.
- There is no coredump of the failed executables.
- The reported SIGSEGV apprently occur before the test's ```main()```, because no output to stdout/stderr is captured by Meson.
    - (Also, it must occur befor static variable initialization time. I checked that.)
- I was unable to reproduce the problem without Meson.
    - Calling the tests by a shell script showed no SIGSEGVs.
    - Calling the tests by a GNU Makefile showed no SIGSEGVs.
    - (This lead me to believe that Meson might be the culprit.)
- Disabling concurrent tests apparently solved the problem, e.g. ```meson test --num-processes 1```.
    - However, the executed tests do not share resources.
      (We have been executing the tests' code in a production environment for years, with a high degree of concurrency. There never were any problems.)
- The problem only occurred on machines with a high physical CPU count (e.g. 24 cores).

**To Reproduce**

- In my scenario, 15 C++ executables are run as tests.
- Simplifying my executable reduces the probability of SIGSEGVs. (It is hard to create a minimum working example based on my code.)
- Maybe related:
    - https://gitlab.gnome.org/GNOME/gnome-color-manager/-/issues/7
    - https://github.com/flashrom/flashrom/issues/186

**Expected behavior**

- If a test generates a SIGSEGV, then the core dump shall be preserved for debugging.
- If a test does not generate a SIGSEGV, then none shall be reported.

**system parameters**
* operating system is Cygwin32
* Python version 3.8.10
* `meson --version` == 0.58.2
* `ninja --version` == 1.10.2

**Could someone take a sharp look at how Meson executes tests in parallel? Could you preserve/capture the core dumps?**

**Comment by xclaesse** [comment] 2021-08-06 19:29
Not sure how is this related to Meson? You can run `meson test --gdb` to debug the crash, or use coredumpctl as shown in the bug report you linked. Meson just spawn the process, if the process crash that's a problem in you test most probably.

**Comment by xclaesse** [comment] 2021-08-06 19:31
Note the report you linked clearly shows the issue is in GTK. Let me know if you find any indication that Meson is responsible, closing this issue in the meantime.

**Closed by xclaesse** 2021-08-06 19:31 UTC

**Comment by jpakkane** [comment] 2021-08-06 19:57
Meson does not touch ulimit at all. If you set it to some value in the shell you use to invoke `meson test` then the core dumps should be created as usual.

**Comment by ManuelAtWork** [comment] 2021-08-07 16:15
> Not sure how is this related to Meson? You can run `meson test --gdb` to debug the crash, or use coredumpctl as shown in the bug report you linked. Meson just spawn the process, if the process crash that's a problem in you test most probably.

The problem apprently correlates with Meson, because I was unable to reproduce the SIGSEGV without. For example, I wrote a makefile that spawns the tests and called it with `make -j`, but no SIGSEGVs. Same thing with a shell script.

I have tried `meson test --gdb`, but was unable to generate any SIGSEGVs that way.

**Comment by ManuelAtWork** [comment] 2021-08-07 16:25
> Meson does not touch ulimit at all. If you set it to some value in the shell you use to invoke `meson test` then the core dumps should be created as usual.

Thank's for the confirmation! My ulimit for core dumps is set to "unlimited", and core dumps are normally generated when crashes occur outside of the Meson run. 

When there is a real SIGSEGV in the code (e.g. put `int * x = nullptr; int y = *x;` in the test case), the Meson correctly reports it AND the coredump is there.

However, the coredump is missing for my "spurious" SIGSEVs ...

**Comment by xclaesse** [comment] 2021-08-07 17:37
Could it be that spawning too many parallel tests causes a OOM kill?

**Comment by ManuelAtWork** [comment] 2021-08-09 06:52
Good idea, but the problem occurs on a machine with exceptionally high memory (512 GB). (Meson runs smoothly on my local workstation with the same number of parallel tests.)

Could virtualization have an impact?
