### ISSUE TITLE
Allow excluding directories from coverage report

### ISSUE THREAD

**Issue by ptomato** [mesonbuild/meson#3287] opened 2018-03-21 21:59 UTC
`gcovr` has an `--exclude-directories` option. It would be nice to either expose this option in Meson, or make Meson automatically exclude paths outside the source and build roots. Otherwise, you get lots of entries inside `/usr/include` in your coverage report (to be precise, any `.h` file which was included in your code and defines an `inline` function.) Generally one wouldn't want to measure these external libraries' code as part of a coverage report.

**Comment by NickeZ** [comment] 2018-03-21 23:11
This is already implemented for lcov. So I guess it is simply a matter of doing a PR. I would however wait until https://github.com/mesonbuild/meson/pull/3242 is merged.

**Comment by thejk** [comment] 2018-03-25 12:00
It should already be included in #3242, I added --exclude for subprojects/ and --rootdir option should already remove references outside project root in gcovr 3.1+. Might need something else for older versions of gcovr tho.

**Comment by kjerstadius** [comment] 2018-12-19 08:55
Is anyone working on this feature? I'm willing to try to implement it if not. Before diving into the specifics of the implementation, what would be a good way to control the exclude option? I'm thinking a function like "coverage_exclude_directory('test-dir')" would perhaps be in line with how Meson works in general? I'm just mindful of the number of different functions exposed as one of the things I really like about Meson is the relatively small amount of supported functions.

**Comment by kjerstadius** [comment] 2018-12-19 09:02
So to be clear, what I would be after is to exclude parts of my own project. For the project I'm working on we publish (and potentially gate on) coverage numbers on Jenkins. However, while we're interested in coverage for the code that we ship, we're not really interested in coverage of the test code itself. So I'd like to exclude the test code from the coverage report so we can publish the XML report directly, rather than having to go through some xml filtering step. Or am I missing something here?

**Comment by kjerstadius** [comment] 2019-01-08 13:08
While I believe you're probably right, I managed to put a working solution for ninja + gcovr together. My implementation adds a new project option that accepts a string of colon separated exclude patterns that are each passed as -e arguments to gcovr, essentially identical to how the subproject root is being excluded already. There's no lcov support yet, but it should be possible to do the same thing using --remove as a post process step, again similar to how subproject root is excluded.

Though the solution works for my case, there's definitely more work needed to make a complete change (like making the list of patterns work regardless file and path separators, lcov support). Before I proceed with that though, I'd like to ask whether a pull request with a solution as described would stand any chance of getting accepted. If it goes against any fundamental design principles I'd rather know upfront :)

**Comment by perror** [comment] 2019-05-27 16:21
Is there anything new about the possibility to exclude the tests themselves from the code coverage process ?

**Comment by kjerstadius** [comment] 2019-06-01 10:08
@perror I may not be the best person to answer your question, but I don't think so. As soon as the respective next versions of of Meson and Gcovr are available (or you use dev versions from git) I think your best bet will be to use a gcovr.cfg file in your source root where you add exclude filters. It's functionality that's not part of Meson, but of Gcovr itself. See [the Gcovr docs](https://github.com/gcovr/gcovr/blob/master/doc/source/guide.rst#configuration-files).

**Comment by perror** [comment] 2019-06-01 14:58
@kjerstadius I saw the patch you wrote, for me it was the right way to go... I really think that this new flag is needed. But, it seems that this opinion is not widely shared... 
So, the best solution now is to wait for the last version of meson and gcovr and add a `.gcovr` file at the top of the project directory that contains:

```
exclude = '*/tests/*'
```

As specified in issue [#293](https://github.com/gcovr/gcovr/issues/293) from the `gcovr` project.

Is it correct ?

**Comment by kjerstadius** [comment] 2019-06-01 16:14
@perror Yes, that's correct, except that the default configuration file that gcovr looks for is `gcovr.cfg`. Also note that the filter options in gcovr are regexes, so you can do some pretty clever stuff if you need or want to.

**Comment by perror** [comment] 2019-06-01 16:59
@kjerstadius Thanks for mentioning the correct filename. I found several default names, so I couldn't choose which one was valid. About the regex, I just need this one (it is quite simple indeed). But, it is good to know that it could be much more complex if needed! :-)

Thanks again!

**Comment by krader1961** [comment] 2019-06-29 23:30
I prefer `lcov` to `gcovr`. Sadly the *~/.lcovrc* config file is per-user, not per project, and in any event does not support exclusion patterns. For the moment I'm using the `lcov` script below but that's obviously a fragile hack. It would be nice if there was a more generic solution. Whether that's something like `meson -Db_coverage_exclude='*/tests/*'` or a *meson.build* statement is open for debate.

```
#!/bin/sh
if [ "$1" = "--remove" ]
then
    /usr/local/bin/lcov "$@" '*/tests/*'
else
    /usr/local/bin/lcov "$@"
fi
```

**Comment by williamfgc** [comment] 2021-03-08 22:34
I know it's an old thread, I'm just following up on @jpakkane answer as this is outside the scope of meson. I just added the following line in my script in lieu of `ninja coverage-xml` to get the [gcovr exclusion for C++ branches](--exclude-unreachable-branches --exclude-throw-branches --root=../ --xml-pretty -o meson-logs/coverage.xm) mentioned by @ptomato original post:

```
$ meson -Dbuildtype=release -Db_coverage=true ../project
$ ninja
$ ninja test
$ gcovr --exclude-unreachable-branches --exclude-throw-branches --root=../project --xml-pretty -o meson-logs/coverage.xml
```

Thanks for the great work on meson, cuts so much boilerplate.

**Comment by Makogan** [comment] 2021-07-15 03:37
I would find this feature useful as well.

**Comment by MichaelJeiShen** [comment] 2021-09-30 02:08
A quick question, for some reasons I have opposite needs which is I hope the coverage process can also include `./subprojects`.
Is there any options I can use to avoid excluding `./subprojects` during coverage process?

**Comment by perror** [comment] 2021-12-15 20:53
I have submitted some code change to add this feature. I await for some feedback from some developers.

**Comment by eli-schwartz** [comment] 2022-04-28 02:44
I just submitted a PR that does two things:
- if a project config file for lcov exists, pass that to lcov
- if a project config file for gcovr exists, don't exclude subprojects/


This means that if you use gcovr, you can trivially re-enable doing coverage of subprojects, by the simple expedient of creating a gcovr.cfg for your project, at which point Meson will now assume that you're in charge of fine-tuning the details.

The issue is of course lcov, which doesn't have a setting for this. Sad. :( I think, though, that the ideal solution is getting lcov to implement such a thing.

Currently this looks a bit weird from Meson's end, because we repeatedly run lcov in order to edit the captured coverage data and extract or remove sections until we eventually end up with only the coverage we want.

**Comment by perror** [comment] 2022-04-28 07:47
@eli-schwartz I looked at your PR and I think this is the way to go (I removed my PR which was just a draft, I did not find the time to finish it... unfortunately). And, yes, lcov should definitely implement a way to exclude paths from their `.locvrc` file. So, I vote for your PR to be included ! ;-)

**Closed** 2022-05-06 19:55 UTC
