### ISSUE TITLE
declare_dependency does not work with compiler object?

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/meson#4513] opened 2018-11-14 14:58 UTC
Hi,
this `meson.build` does not work
```
project('compiles', 'cpp')

my_dep = declare_dependency(include_directories:
                            include_directories('/'),
                            link_args: ['-L/','-lm'])

_code = '''int main(){}'''

compiler = meson.get_compiler('cpp')

_compiles = compiler.compiles(_code, name: 'compile flags check',
                              dependencies: my_dep)  # <------------- it does not like this
```
and says
```
The Meson build system
Version: 0.48.1
Source dir: /tmp
Build dir: /tmp/build
Build type: native build
Project name: compiles
Project version: undefined
Native C++ compiler: c++ (gcc 6.4.0 "c++ (Gentoo 6.4.0-r1 p1.3) 6.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64

meson.build:11:0: ERROR:  Dependencies must be external dependencies

A full log can be found at /tmp/build/meson-logs/meson-log.txt
```

**Comment by asartori86** [comment] 2018-11-20 09:47
@nirbheek, @jpakkane ?

**Comment by asartori86** [comment] 2018-11-21 10:32
thanks @jpakkane, the example was just a toy one to trigger the behavior. What is unexpected to me is that `my_dep` returned by `declare_dependency` is seen as an **internal** dependency for the compiler object, while is seen as **external** for other functions (e.g., `executable`). And the documentation actually reports that `declare_dependency` returns a `dependency_object` which is the same returned by `dependency`, which is used for **external** deps.

The real example would be to use an external library installed in a custom directory
```
_dir = get_option('library-dir')
_includedir = include_directories(_dir+'/include')

cxx = meson.get_compiler('cpp')

_lib = cxx.find_library('library', dirs:_dir + '/lib', required: true)

# check if I can compile and links

_code = ''' some code '''

# I would like to not repeat the include_directories and I hoped I could use declare_dependency

cxx.compiles(_code, include_directories:_includedir)
cxx.links(_code, include_directories: _includedir, dependencies: _lib)

library_dep = declare_dependency(include_directories: _includedir, dependencies: _lib)
```

**Comment by asartori86** [comment] 2018-11-21 11:45
@jpakkane,
I noticed another difference when I use `find_library` and when I declare the dependencies with `link_args`: if I use the `find_library` function, the libraries are not reported in the generated `.pc` file.

In both cases, the include directories are not reported

**Comment by pwnorbitals** [comment] 2020-11-12 13:49
Is this still a problem on latest releases @asartori86 ?

**Comment by eli-schwartz** [comment] 2021-09-03 01:46
Duplicate of #1430

**Closed by eli-schwartz** 2021-09-03 01:46 UTC
