### ISSUE TITLE
Meson doesn't handle 'link_args' correctly for non-gnu D compilers

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson#3568] opened 2018-05-14 21:24 UTC
Sample config
```
project('test-project', 'd')

libabc_dep = dependency('libabc')

test_exe = executable('test', 'app.d',
                        #d_args: ['-I/usr/include', '-L/usr/lib'],
                        dependencies: libabc_dep
)
```
When compiling the `test_exe` target, the compiler fails to add the arguments specified in the pkgconfig (usually, `-I/usr/include` and `-L/usr/lib`). If I add the right arguments to `d_args`, as shown in the commented code, it works.

I have only tried to link dependencies provided by pkgconfig. I also tried compiling with both LDC and DMD, same result.

**Comment by nirbheek** [comment] 2018-05-15 10:31
The issue is probably that pkg-config drops the system prefixes when outputting compile args and link args because most compilers search there by default.

This breaks for LCD and DMD because they don't search there, but I suspect that GDC will work fine.

**Comment by jpakkane** [comment] 2018-05-15 19:27
I verified this. If you create a D target with a dependency on `glib-2.0` because it has both compiler and linker flags that are non-standard.

The flags get properly passed to the command line. Here is GDC:

    gdc -Idsimpleapp@exe -I. -I../abc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -Wall -Wdeprecated -g -O0  -MD -MQ 'dsimpleapp@exe/app.d.o' -MF 'dsimpleapp@exe/app.d.o.deps' -o 'dsimpleapp@exe/app.d.o' -c ../abc/app.d

And ldc:

    ldc2 -Idsimpleapp@exe -I. -I../abc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -enable-color -wi -g -O0   -of 'dsimpleapp@exe/app.d.o' -c ../abc/app.d

So this seems to be a case of LDC and DMD missing internal search directories?

**Comment by nirbheek** [comment] 2018-08-19 22:56
This should've been fixed by:

```
commit 9da031c04c9905949c896a8fdc5b608acd6dde47
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Mon Nov 6 15:42:09 2017 +0530

    dependencies: Force pkg-config to output -L args

    Sometimes pkg-config can decide that the libdir is a system library dir
    and must not be included in the output because that would mess up the
    library search order for pkg-config libraries that must be sourced from
    a non-system prefix.

    However, when we're doing manual searching, we always want to see the
    library directory even if it's the system path, otherwise we can't do
    manual searching at all.
```

Please test and reopen if the bug still exists.

**Comment by FFY00** [comment] 2018-08-20 00:11
The issue was that meson would add `-L-Lpath` instead of `-Lpath` resulting in the lib not being detected by the compiler.

**Comment by nirbheek** [comment] 2018-08-20 00:32
@GoaLitiuM what should we do here? I remember that in the past `-L-L` was required for some D compilers, has that changed?

**Comment by FFY00** [comment] 2018-08-22 17:57
@ljmf00 is experiencing the same issue.

**Comment by ljmf00** [comment] 2018-08-22 18:40
> @ljmf00 is experiencing the same issue.

https://github.com/aurorafossorg/framework/blob/master/src/meson.build#L87

**Comment by ximion** [comment] 2018-08-25 22:35
@GoaLitiuM 
> I'm not sure, I don't know enough pkg-config or D outside Windows, but I did notice the translate_args_to_nongnu function is called for both compile and linking arguments, so at least for the user added linker arguments, the extra -L should not be needed here. The translation of -L arguments should only be applied for linker arguments because in D compilers the -L argument is always the "pass to linker" argument.

No, because that would break GDC builds. The basic idea here is to have your Meson definition not care about what D compiler runs behind the scenes. Pkg-config files and other 3rd-party libraries use the GCC syntax, in which `-L` is "set linker search path", and so does the GDC compiler. So since we need to translate those arguments anyway, the GCC/Clang syntax is default for arguments to the compiler in Meson for all D compilers.
Behind the scenes, the flags are translated to something the currently selected D compiler can actually understand.

The issue here potentially is a misconfiguration of the respective D compiler, although I am not exactly sure what the issue actually still is.
FWIW, Debian and Ubuntu extend LDC's search path: https://salsa.debian.org/d-team/ldc/blob/master/debian/patches/03_ldc_include_path.diff

**Closed** 2018-09-03 16:30 UTC
Labels: D language, bug, compilers
