### ISSUE TITLE
0.50.0 regression: Multiple projects fails on linking (seems related to GResource)

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#5049] opened 2019-03-11 07:05 UTC
## tracker

```
/usr/bin/ld: /builddir/build/BUILD/tracker-2.2.1/x86_64-redhat-linux-gnu/src/libtracker-data/libtracker-data.so: undefined reference to `builtin_ontology_resource_data'
```

## nautilus

```
/usr/bin/ld: src/libnautilus.a(meson-generated_.._nautilus-resources.c.o):/builddir/build/BUILD/nautilus-3.31.90/x86_64-redhat-linux-gnu/src/nautilus-resources.c:11: undefined reference to `nautilus_resource_data'
```

## gedit

```
/usr/bin/ld: gedit/68eed65@@gedit-3.14@sha/meson-generated_.._resources_gedit-resources.c.o:/builddir/build/BUILD/gedit-3.31.92/x86_64-redhat-linux-gnu/gedit/resources/gedit-resources.c:11: undefined reference to `gedit_resource_data'
```

**Comment by QuLogic** [comment] 2019-03-11 07:14
#5046-ish?

**Comment by ignatenkobrain** [comment] 2019-03-11 07:16
@QuLogic probably-ish. I just saw that one was about installing gresource files, but this one seems a bit different issue.

**Comment by Ninja-Koala** [comment] 2019-03-13 14:14
The problem is that these projects assume that gnome.compile_resources() returns an array containing exactly two targets: the c source file and the header file.

But with https://github.com/mesonbuild/meson/pull/4222 sometimes a third target,
an object file is returned which needs to be linked in.

It's not a problem for most projects as they just use the whole array.

The tracker build for example could be fixed by replacing
```
tracker_gresources[0],
tracker_gresources[1],
```
with
```
tracker_gresources,
```
in https://gitlab.gnome.org/GNOME/tracker/blob/master/src/libtracker-data/meson.build#L67

**Comment by nirbheek** [comment] 2019-03-13 15:33
It's still a breaking API change which should not have happened in the first place. We need to fix this somehow.

**Comment by jpakkane** [comment] 2019-03-25 18:56
@ignatenkobrain can you test if the linked MR that reverts the original commit fixes the issue?

**Comment by jpakkane** [comment] 2019-04-01 16:30
The commit was reverted so this should be fixed. Can you test with latest master?

**Comment by jpakkane** [comment] 2019-04-08 17:22
No comments -> assumed fixed.

**Closed by jpakkane** 2019-04-08 17:22 UTC
