### ISSUE TITLE
Python error on setup library containing package from wrap db

### ISSUE THREAD

**Issue by iverks** [mesonbuild/meson#10486] opened 2022-06-13 12:33 UTC
**Describe the bug**
Unhandled python exception

```
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 153, in run
  File "mesonbuild\msetup.py", line 301, in run
  File "mesonbuild\msetup.py", line 185, in generate
  File "mesonbuild\msetup.py", line 229, in _generate
  File "mesonbuild\interpreter\interpreter.py", line 2700, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 149, in run
  File "mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
  File "mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 567, in assignment
  File "mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
  File "mesonbuild\interpreterbase\interpreterbase.py", line 455, in function_call
  File "mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
  File "mesonbuild\interpreter\interpreter.py", line 1660, in func_static_lib
  File "mesonbuild\interpreter\interpreter.py", line 2942, in build_target
  File "mesonbuild\build.py", line 1966, in __init__
  File "mesonbuild\build.py", line 765, in __init__
  File "mesonbuild\build.py", line 2011, in process_kwargs
  File "mesonbuild\build.py", line 1183, in process_kwargs
  File "mesonbuild\build.py", line 1356, in add_deps
AttributeError: 'SubprojectHolder' object has no attribute 'd_features'

meson.build:9:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**
I have in the subprojects folder the .wrap files from https://mesonbuild.com/Wrapdb-projects.html for the subprojects I use and their dependencies again.
```
project('AnimationWindow', 'cpp', default_options: ['cpp_std=c++17'])

imgui_sfml_dep = subproject('imgui-sfml')
sfml_dep = subproject('sfml')


build_files = ['src/AnimationWindow.cpp', 'src/Button.cpp', 'src/Color.cpp', 'src/Image.cpp', 'src/Widget.cpp']
incdir = include_directories('include')
animationwindow = static_library('animationwindow', build_files, include_directories: incdir, dependencies: [sfml_dep, imgui_sfml_dep])
```

**Expected behavior**
Expected no python error

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?: Native build
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Windows 10
* what Python version are you using e.g. 3.8.0: python 3.10.4
* what `meson --version`: meson 0.62.1 from the msi installer

**Comment by eli-schwartz** [comment] 2022-06-13 12:41
Duplicate of #10468

**Closed by eli-schwartz** 2022-06-13 12:41 UTC
