### ISSUE TITLE
`meson dist` should trigger a configure/build

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#10650] opened 2022-08-01 13:29 UTC
**Describe the bug**

Currently the `meson dist` (or `ninja dist`) just makes the distribution from existing contents of the repository. This is wrong because it happens very often that projects want to integrate built data into their tarballs.

We have the case in GIMP. We generate a `git-version.h` header containing environment data, such as the commit hash and git tags if any. Obviously this can only be built on the git repository. So our tarball needs to work from the already generated header file (in the tarball, there is no git repo anymore), so we have an additional dist script simply copying the generated dist file into the tarball.

So far so good, except that we realized that `dist` does not trigger a build. So the worst-case scenario is if we pull from the repo, then run `meson dist` without rebuilding. In such a case, the packaged commit information will be wrong (outdated).

Note that this process of embarking data which can only be made in the git repo (e.g. git info) is common.

Other than this, it is historically common to embark other types of time-consuming generated data which doesn't have any platform-dependence. For instance, many library project would embark the html generated docs for an API in their tarball (it's the same API and docs whatever the platform and sometimes, generation can take long; also it removes build dependencies to simplify packaging). Actually we are also doing this in GIMP 2.10 too and are considering if we should do it again for GIMP 3.0.
With the current meson bug, you could package outdated docs in your tarball.

**To Reproduce**

On a repo with a similar process such as GIMP:

* Build an older version with `ninja`.
* Pull the repository to get new commits.
* Run `ninja dist` without rebuilding first.

**Expected behavior**

You should get a tarball with the re-generated data (`git-version.h` in our case).

Currently your tarball contains the older git information. And this error is totally silent, which is even worse and means we cannot fully trust the result of the `meson dist` as being what is expected.

**Solution**

`meson dist` should simply trigger a configure and a build. In most cases, it will be very fast, if not quasi-instant anyway (if you just built).

Also it's not like people run `meson dist` all the time so here any optimization consideration should really not being taken into consideration. Accuracy of the tarball content (what is released to millions!) is far more important than saving a few secs.

This is what @xclaesse said on `#mesonbuild` apparently on the matter (as reported by a contributor):

```
<xclaesse> nielsdg: What would be the expected behaviour here? meson dist shoud check that vcs_tag() target is up to date and error out if it's not?
<xclaesse> Actually, I thoughts "meson dist" would already rebuild first like "meson test", but seems it's not
<xclaesse> maybe we should rebuild first by default and add --no-rebuild to be consistent with "meson test", that would make sense to me.
```

So yeah, this is similar as `meson test`, it implies a rebuild. And I don't mind if there is an option to bypass this as long as the **default** is that `meson dist` implies the reconfiguration/rebuild which would avoid forgetful errors.

Thanks all! 🤗

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Any.
* what Python version are you using e.g. 3.8.0 - Python 3.9.2 (but doesn't matter)
* what `meson --version` - meson 0.63.99
* what `ninja --version` if it's a Ninja build - ninja 1.10.1

**Comment by bruchar1** [comment] 2023-02-26 02:51
@eli-schwartz I think this duplicates #9563.

**Comment by eli-schwartz** [comment] 2023-02-26 06:17
No, the other ticket is discussing the fact that `meson dist` will not reconfigure the build.dat and register new dist scripts or update the project name/version for the tarball name.

This ticket is asking for a dist script that can dist a build output, and is I think confusing a couple different points.

> Currently your tarball contains the older git information. And this error is totally silent, which is even worse and means we cannot fully trust the result of the `meson dist` as being what is expected.

No, currently your tarball is an error because it cannot find the built files at all. :)

What happens if you run `meson setup builddir && ninja -C builddir dist`? No built files are created, at all, period -- which means they cannot be disted by a dist script.

One way to handle this would be to have your dist script execute `ninja` for at least the outputs you want to dist. This guarantees both initial building, and keeping it up to date.

**Comment by eli-schwartz** [comment] 2023-02-26 06:17
Duplicate of #10118

**Closed by eli-schwartz** 2023-02-26 06:17 UTC

**Comment by eli-schwartz** [comment] 2023-02-26 06:20
(Yes, there was already an issue opened by a GIMP developer asking for the same thing.)
