### ISSUE TITLE
Is there a way we can create a soft link with in the install directory?

### ISSUE THREAD

**Issue by lkammath** [mesonbuild/meson#6028] opened 2019-10-11 10:16 UTC
I am creating some executable. I wanted to create a soft link using meson for this executable in the same directory, how this is possible in meson. I am not getting clear answer anywhere

**Comment by scivision** [comment] 2019-10-11 11:01
the way to do things like this in general (including with other build systems) is to create a custom target

https://mesonbuild.com/Custom-build-targets.html#custom-build-targets

**Comment by scivision** [comment] 2019-10-11 11:03
Thanks for reaching out. For support with specific Meson applications, please reach out to the Meson community Google Group or IRC:

https://mesonbuild.com/index.html#community

**Comment by lkammath** [comment] 2019-10-11 15:25
Thanks , This resolved the stuff. Why can't we have straight forward  create_symlink() call to do that? Is it in plan for future? Can it be taken as feature request?

**Comment by scivision** [comment] 2019-10-13 01:47
I don't know how much of this has been discussed before by Meson devs.
So I understand you are wanting to make a soft link in the build directory to an executable also under the build directory. 

I don't immediately think there would be an objection to that, but there may be some reason I'm unaware of.

**Comment by lkammath** [comment] 2019-10-13 07:28
Yes, It makes sense. A new feature like would be really helpful

**Comment by jpakkane** [comment] 2019-10-13 22:25
Symlinks are not portable because they don't work on Windows. We'd need to specify fallbacks and all that.

The real question is why do you need to have the symlink in the first place? What problem are you solving by doing that?

**Comment by lkammath** [comment] 2019-10-14 04:10
I will have to create different soft links to some executable thats the current use case here

**Comment by galgalesh** [comment] 2019-10-28 19:11
As an example, the Yaru theme for Ubuntu used to be called `Communitheme`. In order to keep backwards compatibility, we have an option to also create a `Communitheme` folder which has a number of symlinks to the `Yaru` folder.

This is currently done using [a script](https://github.com/ubuntu/yaru/blob/master/communitheme-compat/install-compat.sh). It would be nice if we could do this in meson instead.

**Comment by eli-schwartz** [comment] 2020-11-23 03:07
Duplicate of #1602

**Closed by eli-schwartz** 2020-11-23 03:07 UTC
