### ISSUE TITLE
gnome.gdbus_codegen() should allow generating docs

### ISSUE THREAD

**Issue by zeenix** [mesonbuild/meson#2101] opened 2017-07-21 15:15 UTC
gdbus-codegen has a --generate-docbook and gnome.gdbus_codegen() should allow making use of that feature.

**Comment by nirbheek** [comment] 2017-07-22 18:40
Duplicate of https://github.com/mesonbuild/meson/issues/2066

**Closed by nirbheek** 2017-07-22 18:40 UTC
