### ISSUE TITLE
i18n module does not report executed commands with ninja -v

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#3087] opened 2018-02-18 09:54 UTC
It's important to see what commands are actually executed to be able to run them independently. We use `i18n` in systemd, and
```console
$  ninja -C build systemd-pot -v
ninja: Entering directory `build'
[0/1] /usr/bin/python3 /usr/bin/meson --internal commandrunner /home/zbyszek/src/systemd-work /home/zbyszek/src/systemd-work/build po /usr/bin/python3 /usr/bin/meson /usr/bin/python3 /usr/bin/meson --internal gettext pot --pkgname=systemd --extra-args=--flag=g_dngettext:2:pass-c-format@@--flag=g_error_new:3:c-format@@--keyword=g_dngettext:2,3@@--keyword=g_dpgettext2:2c,3@@--flag=g_set_error:4:c-format@@--flag=NC_:2:pass-c-format@@--flag=C_:2:pass-c-format@@--keyword=N_@@--flag=g_string_printf:2:c-format@@--flag=N_:1:pass-c-format@@--keyword=NC_:1c,2@@--keyword=_@@--flag=g_string_append_printf:2:c-format@@--keyword=g_dcgettext:2@@--keyword=C_:1c,2@@--add-comments@@--flag=g_strdup_printf:1:c-format@@--from-code=UTF-8
xgettext: warning: file 'src/core/org.freedesktop.systemd1.policy.in' extension 'policy' is unknown; will try C
xgettext: warning: file 'src/hostname/org.freedesktop.hostname1.policy' extension 'policy' is unknown; will try C
...
```
It would be nice to see the actual command being invoked.

**Comment by nirbheek** [comment] 2018-02-18 13:46
Duplicate of https://github.com/mesonbuild/meson/issues/2900

**Closed by nirbheek** 2018-02-18 13:46 UTC
