### ISSUE TITLE
generated Vala source can not be found

### ISSUE THREAD

**Issue by eyelash** [mesonbuild/meson#3029] opened 2018-02-08 12:40 UTC
meson.build:
```meson
project('vala-test', 'vala', 'c')
config = configuration_data()
config.set('MESSAGE', 'Hello')
main_vala = configure_file(configuration: config, input: 'main.vala.in', output: 'main.vala')
executable('vala-test', main_vala, dependencies: dependency('glib-2.0'))
```
main.vala.in:
```vala
void main() {
    stdout.printf("@MESSAGE@\n");
}
```
The above project builds without errors with Meson 0.39.1 but fails with Meson 0.44.0 from the GNOME SDK Flatpak with the following error:
```
[2/3] Compiling C object 'vala-test@exe/meson-generated_main.c.o'.
FAILED: vala-test@exe/meson-generated_main.c.o 
ccache cc  -Ivala-test@exe -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -O0 -g -MMD -MQ 'vala-test@exe/meson-generated_main.c.o' -MF 'vala-test@exe/meson-generated_main.c.o.d' -o 'vala-test@exe/meson-generated_main.c.o' -c 'vala-test@exe/main.c'
cc: error: vala-test@exe/main.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by nirbheek** [comment] 2018-02-11 14:04
Duplicate of https://github.com/mesonbuild/meson/issues/815.

**Closed by nirbheek** 2018-02-11 14:04 UTC
Labels: bug, vala
