### ISSUE TITLE
Meson finds dependencies on build system during cross compile

### ISSUE THREAD

**Issue by PyroAVR** [mesonbuild/meson#7799] opened 2020-09-29 16:01 UTC
**Describe the bug**
When performing a cross-compile which has dependencies found via `pkg-config`, Meson finds dependencies on the build system, regardless of the value of the `native` keyword on the dependency.

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).
`meson.build`:
```
project('example', 'c')

# ensure that msgpack is installed on the build system
dep_msgpack = dependency('msgpack', native: false)
dependencies = [dep_msgpack]
```
`cross_file.cfg`:
```
# Environment setup for Meson, points to arm-none-eabi GCC toolchain
[binaries]
c = '/usr/bin/arm-none-eabi-gcc'
cpp = '/usr/bin/arm-none-eabi-g++'
ar = '/usr/bin/arm-none-eabi-ar'
strip = '/usr/bin/arm-none-eabi-strip'
pkgconfig = '/usr/bin/pkg-config'
exe_wrapper = ''

[host_machine]
cpu_family = 'arm'
cpu = 'cortex-m4'
endian = 'little'
system = 'baremetal'
[properties]
needs_exe_wrapper = true
# If you are including Newlib from a package manager, remove the floating-point
# arguments and replace them with: -mfloat-abi=soft
c_args = ['-mcpu=cortex-m4', '-mfloat-abi=hard', '-mfpu=fpv4-sp-d16']
# True baremetal: -nostdlib
# Baremetal with crt0.S: -nodefaultlibs
# If using Newlib, add --specs=nano.specs --specs=nosys.specs
#c_link_args = ['-T', 'k64.ld', '-nostdlib', '-mcpu=cortex-m4', '-mfpu=fpv4-sp-d16']
```

**Expected behavior**
Meson fails to find `msgpack` for the host system, `arm-none-eabi`, and ignores the `msgpack` installation for `x86_64-pc-linux-gnu` present on the build system.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Cross build from Linux x86_64 to arm-none for ARM Cortex M4 baremetal.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Arch Linux (kernel: 5.8.5-arch1-1 x86_64)
* what Python version are you using e.g. 3.8.0
Python 3.8.5
* what `meson --version`
0.55.1
* what `ninja --version` if it's a Ninja build
1.10.1

I discovered this bug while trying to include `msgpack-c` in a baremetal build.  I am now aware that I will have to write a wrap for it, but it seems like even with a wrap, this issue will persist.

**Comment by xclaesse** [comment] 2020-09-29 18:56
The problem is in your cross file, `/usr/bin/pkg-config` will return build machine libraries. There are 2 ways to fix that:
1) Some toolchains provide a pkg-config wrapper script, you could use it as `pkgconfig = '/usr/bin/arm-none-eabi-pkg-config'` if that exists, or if you write one. For example on my Ubuntu I have `/usr/bin/x86_64-w64-mingw32-pkg-config`. Those wrappers set PKG_CONFIG_LIBDIR and PKG_CONFIG_SYSROOT_DIR
2) Keep using `/usr/bin/pkg-config` in your cross file but add `pkg_config_libdir='/path/to/sysroot/lib/pkgconfig'` and `sys_root='/path/to/sysroot'` in `[properties]` section.

**Comment by PyroAVR** [comment] 2020-09-29 21:33
@xclaesse Wow, I did not realize that.  My apologies for the noise, in that case. I'll have to look into writing one of those since my toolchain does not appear to provide a `pkg-config` wrapper.  Thank you so much!

**Comment by dcbaker** [comment] 2020-10-01 19:38
I'm going to go ahead and close this. It might be smart for us to add a warning if pkg-config is the same for the host and build machines and pkg_config_libdir isn't set though.

**Closed by dcbaker** 2020-10-01 19:38 UTC
