### ISSUE TITLE
Python module broken on 0.62.0 for meson dist

### ISSUE THREAD

**Issue by whot** [mesonbuild/meson#10181] opened 2022-03-25 06:48 UTC
Running `meson dist` on 0.62.0 produces this error:
```
meson-private/dist-unpack/test-1/meson.build:4:0: ERROR: python.platlibdir and python.install_env are mutually exclusive
```
Required `meson.build` file:
```
project('test', 'c', version: '1')
pymod = import('python')
python = pymod.find_installation('python3', required: true)
```
And then just:
```
$ meson setup builddir/
$ meson dist -C builddir/
Testing distribution package /home/whot/tmp/2022-03-25-Fri/test/build/meson-dist/test-1.tar.xz
The Meson build system
Version: 0.62.0
Source dir: /home/whot/tmp/2022-03-25-Fri/test/build/meson-private/dist-unpack/test-1
Build dir: /home/whot/tmp/2022-03-25-Fri/test/build/meson-private/dist-build
Build type: native build
Project name: test
Project version: 1
C compiler for the host machine: ccache cc (gcc 12.0.1 "cc (GCC) 12.0.1 20220308 (Red Hat 12.0.1-0)")
C linker for the host machine: cc ld.bfd 2.37-24
Host machine cpu family: x86_64
Host machine cpu: x86_64

build/meson-private/dist-unpack/test-1/meson.build:4:0: ERROR: python.platlibdir and python.install_env are mutually exclusive

A full log can be found at /home/whot/tmp/2022-03-25-Fri/test/build/meson-private/dist-build/meson-logs/meson-log.txt
Running Meson on distribution package failed
Dist check build directory was /home/whot/tmp/2022-03-25-Fri/test/build/meson-private/dist-build
```
There isn't really anything in the suggested meson-log.txt file, it's just the standard checks up to `Target machine cpu: x86_64` and then the error message. Reproduced on a Ubuntu 20.04 podman container (Python 3.8.10) and an up-to-date Fedora 36 (Python 3.10.3).

Bisected to commit 78945fb9832e989453fbabc471d45bb71805eca8, cc @eli-schwartz.

**Comment by eli-schwartz** [comment] 2022-03-25 06:54
libnvme had this issue in a ticket I found: https://github.com/linux-nvme/libnvme/issues/303

I eventually figured out this was the root of the issue. cc @glimchb

I have a work in progress patch to fix it. I'm trying to clean up `meson dist` while I am at it to fix what feel like glaring CLI design issues.

**Comment by eli-schwartz** [comment] 2022-03-25 06:56
Thing is... As far as I can tell this should only happen if you manually define platlibdir. Its default value is `` and the error happens if it is non-empty *and* when meson dist manually overrides it to the default value when running tests.

**Comment by jpakkane** [comment] 2022-04-11 17:33
We have put a bunch of fixes on Python in master. Can you test if the issue still occurs?

**Comment by jpakkane** [comment] 2022-04-11 17:40
Actually scratch that, can reproduce.

**Comment by jpakkane** [comment] 2022-04-11 17:44
Git bisect says the broken commit is e54e9f58e5dce61573a96bdbef2bc3528566589e.

**Comment by eli-schwartz** [comment] 2022-04-11 17:48
There's a linked PR which will fix this when merged.

**Closed** 2022-04-11 18:12 UTC

**Comment by eli-schwartz** [comment] 2022-04-11 19:22
I did some investigation BTW. It turns out that if you manually set the option, then when saving the coredata ever since 00f5dadd5b7d71c30bd7393d165a87f554eb92e5, setting a `*dir` option to an empty string causes it to be set to `.` instead.
