### ISSUE TITLE
[Feature Request] Add functionality to read enviroment variables

### ISSUE THREAD

**Issue by snsmac** [mesonbuild/meson#2782] opened 2017-12-14 11:01 UTC
Hello,
first thank you for this great project!

Something that i would like to see is an function to read enviroment variables.
It should be able to tell me if a variable is set and if it is set its value as string.
My use for this would be to access things like build-id from a CI system.

Thank you

**Comment by nirbheek** [comment] 2017-12-14 11:04
Duplicate of https://github.com/mesonbuild/meson/issues/9.

**Closed by nirbheek** 2017-12-14 11:04 UTC
