### ISSUE TITLE
Unhandled python exception in i18n.py

### ISSUE THREAD

**Issue by zonia3000** [mesonbuild/meson#10364] opened 2022-05-07 23:34 UTC
**Describe the bug**
I'm receiving an `Unhandled python exception` while trying to compile [Phosh](https://gitlab.gnome.org/World/Phosh/phosh):
```
  File "/usr/local/lib/python3.9/dist-packages/mesonbuild/modules/i18n.py", line 181, in merge_file
    '--msgfmt=' + self.tools['msgfmt'].get_path(),
TypeError: can only concatenate str (not "NoneType") to str
```
See attached [output.txt](https://github.com/mesonbuild/meson/files/8646083/output.txt) for full log

**To Reproduce**
I created a [Dockerfile](https://github.com/mesonbuild/meson/files/8646085/Dockerfile.txt) where the issue can be reproduced. I've also uploaded a [ready to use image on my DockerHub](https://hub.docker.com/layers/meson-bug-reproducer/zonia3000/meson-bug-reproducer/latest/images/sha256-40f83ff155b297264ad8286bda38d3e43100bd44f105adc9a3b859daaf45de90?context=repo).

You can run this to reproduce it:
```
docker run -it zonia3000/meson-bug-reproducer bash
meson . _build
```
Error happens in [phosh meson.build at line 40](https://gitlab.gnome.org/World/Phosh/phosh/-/blob/e00bc02990f22ea8b668eee2550ea87bfbd6d592/data/meson.build#L40).

**Expected behavior**
I should be able to build the project.

**System parameters**
* plain native build
* Debian 11.3
* Python 3.9.2
* `meson --version`: 0.62.1
* `ninja --version`: 1.10.2.git.kitware.jobserver-1

**Comment by zonia3000** [comment] 2022-05-08 00:02
Solved this executing `sudo apt install gettext`

Also this is the same: https://github.com/mesonbuild/meson/issues/10320

**Comment by eli-schwartz** [comment] 2022-05-08 02:22
Duplicate of #10320

**Closed by eli-schwartz** 2022-05-08 02:22 UTC
