### ISSUE TITLE
build.ninja file generation error - directory doubled 0.44.0 (0.42.1 ok)

### ISSUE THREAD

**Issue by ranger324** [mesonbuild/meson#2820] opened 2017-12-22 14:26 UTC
error compiling appstream-glib
0.44.0
-subdirectory dir1
build dir/file: CUSTOM_COMMAND ../dir1/dir1/file1
-should be:
build dir/file: CUSTOM_COMMAND ../dir1/file1
0.42.1 is ok

**Comment by jibsen** [comment] 2017-12-23 15:23
I am probably missing something, but I can't get it to build with either version. It is failing to run the introspection stuff.

Btw, regarding the build instruction in the readme, on Fedora 27 I had to install `libgcab1-devel` instead of `libgcab-devel`, and also `json-glib-devel`.

**Comment by nirbheek** [comment] 2018-01-02 07:31
Duplicate of https://github.com/mesonbuild/meson/issues/2860

(marking as dupe of newer bug because it has more info)

**Closed by nirbheek** 2018-01-02 07:31 UTC
Labels: bug, generators, regression
