### ISSUE TITLE
regression 0.57.0 build.pkg_config_path broken

### ISSUE THREAD

**Issue by asavah** [mesonbuild/meson#8354] opened 2021-02-15 19:27 UTC
**Describe the bug**
build.pkg_config_path is broken in 0.57.0 when crosscompiling.

**To Reproduce**
Using toolchain.meson hint file with following lines worked flawlessly in 0.56.x
```
[built-in options]
pkg_config_path = '/home/asavah/kross/build/asusb450eg/ovr/pkgconfig/:/home/asavah/kross/build/asusb450eg/rootfs/usr/lib/pkgconfig:/home/asavah/kross/build/asusb450eg/rootfs/usr/share/pkgconfig'
build.pkg_config_path = '/home/asavah/kross/host/lib/pkgconfig:/home/asavah/kross/host/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig'
```

As per documentation build.pkg_config_path was used to specify locations of native .pc stuff

0.57.0 does some wierd appending of both build and host pkg_config_path

```
Library acl found: YES
Pkg-config binary for MachineChoice.HOST is cached.
Determining dependency 'blkid' with pkg-config executable '/home/asavah/kross/host/asusb450eg/bin/x86_64-asusb450eg-linux-gnu-pkg-config'
PKG_CONFIG_PATH: /home/asavah/kross/host/lib/pkgconfig:/home/asavah/kross/host/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
Called `/home/asavah/kross/host/asusb450eg/bin/x86_64-asusb450eg-linux-gnu-pkg-config --modversion blkid` -> 0
2.36.597
PKG_CONFIG_PATH: /home/asavah/kross/host/lib/pkgconfig:/home/asavah/kross/host/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
Called `/home/asavah/kross/host/asusb450eg/bin/x86_64-asusb450eg-linux-gnu-pkg-config --cflags blkid` -> 0
-I/home/asavah/kross/build/asusb450eg/rootfs/home/asavah/kross/host/include/blkid
PKG_CONFIG_PATH: /home/asavah/kross/host/lib/pkgconfig:/home/asavah/kross/host/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
Called `/home/asavah/kross/host/asusb450eg/bin/x86_64-asusb450eg-linux-gnu-pkg-config --libs blkid` -> 0
-L/home/asavah/kross/build/asusb450eg/rootfs/home/asavah/kross/host/lib -lblkid
PKG_CONFIG_PATH: /home/asavah/kross/host/lib/pkgconfig:/home/asavah/kross/host/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
Called `/home/asavah/kross/host/asusb450eg/bin/x86_64-asusb450eg-linux-gnu-pkg-config --libs blkid` -> 0
-L/home/asavah/kross/build/asusb450eg/rootfs/home/asavah/kross/host/lib -lblkid
Run-time dependency blkid found: YES 2.36.597
```

Note `-I/home/asavah/kross/build/asusb450eg/rootfs/home/asavah/kross/host/include/blkid` which is total nonsense.

**Expected behavior**
A clean build is produced.

Possibly related to https://github.com/mesonbuild/meson/issues/8348 , feel free to close if this is a dupe (same root cause).

**Comment by dcbaker** [comment] 2021-02-16 02:03
This may be a duplicate of #8351

**Comment by jpakkane** [comment] 2021-02-16 17:02
It's weird that you have a `build.foo` option in the cross file. It should not be there, but in the native file instead. Does it work if you move all `build.` options to the native file (without the `build.` prefix  obviously)?

**Comment by asavah** [comment] 2021-02-16 19:44
Hmm maybe I misinterpreted the documentation.

```
Specifying options per machine
Since 0.51.0, some options are specified per machine rather than globally for all machine configurations. Prefixing the option with build. just affects the build machine configuration, while unprefixed just affects the host machine configuration, respectively. For example:

build.pkg_config_path controls the paths pkg-config will search for just native: true dependencies (build machine).

pkg_config_path controls the paths pkg-config will search for just native: false dependencies (host machine).

This is useful for cross builds. In the native builds, build = host, and the unprefixed option alone will suffice.
```

I don't have a native file at all.
I didn't know it --native-file existed at all.
Will try that once I add a native-file generator for meson to my homegrown buildsystem.
However in 0.56.0 having both build.pkg_config_path and pkg_config_path worked fine. 

I invoke meson like this `meson --cross-file=tmpdir/toolchain.meson`

**Comment by dcbaker** [comment] 2021-02-16 20:11
@jpakkane, we never documented this as working, I'll check and see if it works. Since we never documented it (or intended it to work) and there is a correct solution that works right now, how would you feel about deprecating it and marking it for removal in 0.58 or 0.59?

**Comment by asavah** [comment] 2021-02-16 20:30
Thanks for the --native-file hint.
When using it to specify the build machine options/binaries so far worked great.
Tested by building a few heavy weights eg systemd, mesa, etc.

Maybe documentation could use a bit of love 😉 .

**Closed** 2021-02-18 18:57 UTC
Labels: regression
