### ISSUE TITLE
Unkown configuration options should cause an error or a warning

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#2059] opened 2017-07-13 15:52 UTC
When an unknown option is specified (`-Dno-such-option=11`) meson gives no feedback whatsover. If the user makes a typo, it'd be best for them if meson threw an error. If the user tries to configure with an option that was removed, it'd probably be better for them to just get a warning. If they try to use an option which was renamed, an error would be more useful. So I don't know if an error or a warning is more appropriate, but IMHO it should at least print a big warning in red.

FTR, autotools says:
```console
$ ../configure --enable-foobar=false
configure: WARNING: unrecognized options: --enable-foobar
...
```

**Comment by TingPing** [comment] 2017-07-13 16:36
Duplicate of #932

**Closed by TingPing** 2017-07-13 16:36 UTC

**Comment by keszybz** [comment] 2017-07-13 16:37
Damn, I looked through the list of open issues, but there's too many ;)
