### ISSUE TITLE
python.extension_module() writes the absolute destination path in `meson-info/intro-install_plan.json`

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#10777] opened 2022-09-04 19:47 UTC
The documentation says that the `destination` paths in `meson-info/intro-install_plan.json` should use placeholders for the base directories. `meson-python` relies upon this for detecting whether a project installs python extensions modules, checking for any of destinations including any of `{bindir}`, `{libdir_shared}`, `{libdir_static}`, `{py_platlib}`, `{moduledir_shared}`.

Entries for `python.extension_module()` targets however do not contain any placeholder. IIUC,`meson-python` expects them to contain `{py_platlib}`.

Is this a bug on how `intro-install_plan.json` is put together or is `meson-python` expectation wrong?

I tested this with Meson 0.60 to  0.62 and the behavior is the same.

See https://github.com/FFY00/meson-python/issues/124

**Comment by eli-schwartz** [comment] 2022-09-04 20:00
Please double check on both:
- the latest release
- meson git master

This is tracked in meson-python as https://github.com/FFY00/meson-python/pull/104

**Comment by eli-schwartz** [comment] 2022-09-04 20:02
Duplicate of #10601

**Closed by eli-schwartz** 2022-09-04 20:02 UTC

**Comment by dnicolodi** [comment] 2022-09-04 20:14
Thanks @eli-schwartz However, judging form the discussion in #10601 the solution proposed in https://github.com/FFY00/meson-python/pull/104 is the wrong one and what is currently done in meson-python is correct. What is needed is a fix for #10601.

#10601 says that this is new in 0.63, however, I tested it with 0.60 and later and the behavior on my test case is the same.

I'll see if I can help with #10601. It seems that the python Meson module generates the install paths with the placeholders, but these get lost somewhere.

**Comment by eli-schwartz** [comment] 2022-09-04 20:19
It's partially fixed in 0.63.0 and fully fixed in git master.

**Comment by dnicolodi** [comment] 2022-09-04 20:20
I just tested git master and it does not work for me.

**Comment by eli-schwartz** [comment] 2022-09-04 20:25
It's confirmed to work for SciPy, so I'll need more details than that.

Please note: reproducer should use Meson directly, or otherwise ensure that a PEP 517 build backend isn't messing things up by reinstalling unfixed versions of Meson into an empty virtualenv.

**Comment by dnicolodi** [comment] 2022-09-04 20:26
Sorry @eli-schwartz, I run the wrong test. I confirm that git master works as intended.
