### ISSUE TITLE
Meson looks for native compiler when cross compiling

### ISSUE THREAD

**Issue by onkarshinde** [mesonbuild/meson#4186] opened 2018-09-15 13:30 UTC
Please refer to the cross options file here
https://github.com/GNUSim8085/GNUSim8085/blob/master/meson_cross_win32.txt
When I run command
`meson builddir --prefix=/ --cross-file meson_cross_win32.txt`
I get following output:
```
The Meson build system
Version: 0.47.2
Source dir: /home/onkar/GNUSim8085
Build dir: /home/onkar/GNUSim8085/builddir
Build type: cross build
Project name: gnusim8085
Project version: 1.4.1.20180912

meson.build:1:0: ERROR:  Unknown compiler(s): ['cc', 'gcc', 'clang']
The follow exceptions were encountered:
Running "cc --version" gave "[Errno 2] No such file or directory: 'cc': 'cc'"
Running "gcc --version" gave "[Errno 2] No such file or directory: 'gcc': 'gcc'"
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang': 'clang'"

A full log can be found at /home/onkar/GNUSim8085/builddir/meson-logs/meson-log.txt
```
It looks like even though I am cross compiling meson expects native compiler to be present. If I install gcc then the cross build works. So there is no issue with the cross file or the build process.
If this is a known limitation it should be documented.

**Comment by jon-turney** [comment] 2018-09-15 13:44
Duplicate of #2392

**Closed** 2018-09-15 14:09 UTC
