### ISSUE TITLE
Meson 5.2 fails on LeelaChessZero build ...

### ISSUE THREAD

**Issue by MichaelB7** [mesonbuild/meson#6309] opened 2019-12-06 06:30 UTC
Simple solution for now is to revert to 5.1.2 until it gets fixed.

https://github.com/LeelaChessZero/lc0/issues/1036

**Comment by borg323** [comment] 2019-12-07 23:53
This was already reported and bisected in <https://github.com/mesonbuild/meson/issues/6113>.

**Comment by mensinda** [comment] 2019-12-09 20:08
Should be fixed with #6321

**Comment by mensinda** [comment] 2019-12-12 19:18
@MichaelB7 did #6321 resolve the issue for you?

**Comment by MichaelB7** [comment] 2019-12-12 20:24
I haven’t been able to check yet.

**Comment by eli-schwartz** [comment] 2021-08-31 06:17
Duplicate of #6113

**Closed by eli-schwartz** 2021-08-31 06:17 UTC
Labels: OS:macos
