### ISSUE TITLE
Meson incorrectly identifies WSL-runnable .exe on Linux PATH as mono binary

### ISSUE THREAD

**Issue by mon** [mesonbuild/meson#8445] opened 2021-03-02 05:35 UTC
**Describe the bug**
I have a build system in WSL, but programming tools accessing USB devices have to remain as Windows exe files. These Windows binaries can be directly run in the WSL shell as if they were normal Linux binaries, and I've been using that setup in Meson for some time.

**To Reproduce**
In a fresh WSL install and Windows installed on `C:/`
```meson
project('test', 'c')

run_target('example',
    command : [find_program('/mnt/c/WINDOWS/system32/help.exe')]
)
```

`meson compile example`

**Expected behavior**
`help.exe`'s default output is printed as meson runs the command

**Actual behavior**
Meson considers the exe to be a mono binary and runs it. I do not have mono installed, so it fails:
`FileNotFoundError: [Errno 2] No such file or directory: 'mono`

**system parameters**
* Happens on both cross and native builds
* Windows 10 20H2, Ubuntu 20.04.1 installed in WSL 1
* Python 3.8.5
* `meson --version` = 0.57.1

**Comment by xclaesse** [comment] 2021-03-02 17:54
This is indeed a regression in your case, but was previously inconsistent. Meson has always added mono for `.exe` on Linux in `custom_target()` command and only when the command needs to be wrapped by meson (which itself is a regression from ed348b7da81dd05aaa7ac398ae9acc4b15bc2733 that got fixed in 0.57.0 by a155935d2).

Since 0.57.0 run_target() uses the same code path as custom_target(), so more consistency, but thus sadly share the same bugs. The good news is fixing it for run_target() will now also fix it for custom_target() at the same time.

Now... how can I know if meson is running on Linux vs WSL?

**Comment by xclaesse** [comment] 2021-03-02 17:58
> Now... how can I know if meson is running on Linux vs WSL?

Found this trick on reddit: `on_wsl = "microsoft" in platform.uname()[3].lower()`, did not try yet.

**Comment by xclaesse** [comment] 2021-03-02 18:34
@mon Could you check if that PR fixes your problem please? https://github.com/mesonbuild/meson/pull/8453

**Comment by mon** [comment] 2021-03-02 23:33
Just tested myself, works perfectly! Thanks for the lightning fast turnaround.

**Closed** 2021-03-03 13:05 UTC
