### ISSUE TITLE
UnboundLocalError: local variable 'plat' referenced before assignment

### ISSUE THREAD

**Issue by tim77** [mesonbuild/meson#5617] opened 2019-07-08 11:30 UTC
Got this error during build process:

`UnboundLocalError: local variable 'plat' referenced before assignment`

Full [build log](https://copr-be.cloud.fedoraproject.org/results/atim/chamferwm/fedora-30-x86_64/00961421-chamferwm/builder-live.log) on Fedora 30.

Meson version 0.50.1.

**Comment by scivision** [comment] 2019-07-10 02:27
This was fixed by #5430 in Meson 0.51. @jpakkane would/should this be backported?

**Comment by nirbheek** [comment] 2019-07-10 03:35
0.51.1 is out, so Fedora 30 should be able to update to it now. @ignatenkobrain ?

**Comment by ignatenkobrain** [comment] 2019-07-10 07:41
Yes. Updates are in bodhi. For last few releases I usually wait for point release to appear since we still make some regressions and usually people do not ask for latest version on stable distros so it can lag.

**Comment by tim77** [comment] 2019-07-10 07:58
Thank you. If someone wish to help with QA
https://bodhi.fedoraproject.org/updates/FEDORA-2019-482e5c0e78

**Comment by scivision** [comment] 2019-07-14 01:57
It looks like this is in bodhi stable and so can be closed. Thank you.

**Closed by scivision** 2019-07-14 01:57 UTC
