### ISSUE TITLE
meson instrospect without configured directory broken by b72b5365afe319e576e254f12437aeff899eb03e

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#5884] opened 2019-09-04 17:31 UTC
Before said commit `meson introspect --buildoptions meson.build` would return something, now it returns nothing.

**Comment by dcbaker** [comment] 2019-09-04 18:21
This seems to be related to having a `build_by_default : array.contains('foo')`. Still haven't figured it all out yet.

**Comment by mensinda** [comment] 2019-09-04 18:30
I am unable to reproduce this bug on the current master?

What project are you using?

**Comment by dcbaker** [comment] 2019-09-04 18:33
Mesa in this case. I've pushed https://github.com/dcbaker/meson/tree/reproduce-5884, which has a patch to the introspect test that reproduces the problem

**Comment by mensinda** [comment] 2019-09-04 20:33
Should be fixed with #5885.

**Closed** 2019-09-04 22:05 UTC
Labels: bug, regression
