### ISSUE TITLE
Building Progress was interrupted by a bug when building the GTK4.

### ISSUE THREAD

**Issue by shipherd** [mesonbuild/meson#13470] opened 2024-07-25 05:33 UTC
**Describe the bug**

```
TypeError: 'NoneType' object does not support item assignment
subprojects\harfbuzz\meson.build:217:15: ERROR: Unhandled python exception
This is a Meson bug and should be reported!
```

**To Reproduce**
I was trying to follow this article https://www.collabora.com/news-and-blog/blog/2021/03/18/build-and-run-gtk-4-applications-with-visual-studio/ to build the GTK4 on Windows.

This was my [meson.build](https://github.com/user-attachments/files/16370819/meson.zip).

With all the prerequisite tools, here are my brief steps:
1. Enter the x64 Native Tools Command Prompt
2. `git clone https://gitlab.gnome.org/GNOME/gtk.git`
3. `cd gtk`
4. `meson setup build --prefix C:/GTK`

The bug was triggered when `meson setup build --prefix C:/GTK`

**Expected behavior**
The building progress gets stopped when meson was 'Executing subproject pango:harfbuzz', and here is the log.

```
Executing subproject pango:harfbuzz

harfbuzz| Project name: harfbuzz
harfbuzz| Project version: 4.0.0
harfbuzz| DEPRECATION: None of the values ['gnu99'] are supported by the c compiler.
harfbuzz| However, the deprecated gnu99 std currently falls back to c99.
harfbuzz| This will be an error in the future.
harfbuzz| If the project supports both GNU and MSVC compilers, a value such as
harfbuzz| "c_std=gnu11,c11" specifies that GNU is preferred but it can safely fallback to plain c11.
harfbuzz| DEPRECATION: None of the values ['gnu99'] are supported by the c compiler.
harfbuzz| However, the deprecated gnu99 std currently falls back to c99.
harfbuzz| This will be an error in the future.
harfbuzz| If the project supports both GNU and MSVC compilers, a value such as
harfbuzz| "c_std=gnu11,c11" specifies that GNU is preferred but it can safely fallback to plain c11.
harfbuzz| C compiler for the host machine: cl (msvc 19.40.33812 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.40.33812 ��")
harfbuzz| C linker for the host machine: link link 14.40.33812.0
harfbuzz| C++ compiler for the host machine: cl (msvc 19.40.33812 "���� x64 �� Microsoft (R) C/C++ �Ż������� 19.40.33812 ��")
harfbuzz| C++ linker for the host machine: link link 14.40.33812.0
harfbuzz| Compiler for C++ supports arguments /utf-8: YES
harfbuzz| Compiler for C++ supports link arguments -Bsymbolic-functions: NO
harfbuzz| Compiler for C++ supports arguments -fno-exceptions: NO
harfbuzz| Compiler for C++ supports arguments -fno-rtti: NO
harfbuzz| Compiler for C++ supports arguments -fno-threadsafe-statics: NO
harfbuzz| Compiler for C++ supports arguments -fvisibility-inlines-hidden: NO
harfbuzz| Compiler for C++ supports arguments -Wa,-mbig-obj: NO
harfbuzz| Library m found: NO
harfbuzz| Run-time dependency freetype found: NO (tried pkgconfig and cmake)
harfbuzz| Dependency glib-2.0 found: YES 2.76.0 (overridden)
harfbuzz| Dependency gobject-2.0 found: YES 2.76.0 (overridden)
harfbuzz| Dependency graphite2 skipped: feature graphite2 disabled
harfbuzz| Dependency graphite2 skipped: feature graphite disabled
harfbuzz| Run-time dependency icu found: NO (tried cmake)
harfbuzz| Dependency cairo found: YES 1.18.0 (overridden)
harfbuzz| WARNING: Subproject 'cairo' did not override 'cairo-ft' dependency and no variable name specified
harfbuzz| Dependency cairo-ft from subproject subprojects/cairo found: NO
harfbuzz| Run-time dependency chafa found: NO (tried pkgconfig and cmake)
harfbuzz| Compiler for C++ supports arguments -Wno-non-virtual-dtor: NO
harfbuzz| WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14
Traceback (most recent call last):
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\msetup.py", line 364, in run
    app.generate()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\msetup.py", line 226, in _generate
    intr.run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 3032, in run
    super().run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 205, in evaluate_statement
    self.assignment(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 642, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 98, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 116, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1809, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\dependencyfallbacks.py", line 354, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\dependencyfallbacks.py", line 130, in _do_subproject
    self.interpreter.do_subproject(subp_name, func_kwargs)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 948, in do_subproject
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 936, in do_subproject
    return methods_map[method](subp_name, subdir, default_options, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 987, in _do_subproject_meson
    subi.run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 3032, in run
    super().run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 205, in evaluate_statement
    self.assignment(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 642, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 799, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 98, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 116, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1809, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\dependencyfallbacks.py", line 354, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\dependencyfallbacks.py", line 130, in _do_subproject
    self.interpreter.do_subproject(subp_name, func_kwargs)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 948, in do_subproject
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 936, in do_subproject
    return methods_map[method](subp_name, subdir, default_options, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 987, in _do_subproject_meson
    subi.run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\interpreter.py", line 3032, in run
    super().run()
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 219, in evaluate_statement
    return self.evaluate_if(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 309, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 219, in evaluate_statement
    return self.evaluate_if(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 294, in evaluate_if
    result = self.evaluate_statement(i.condition)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 251, in evaluate_statement
    return self.evaluate_statement(cur.inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 231, in evaluate_statement
    return self.evaluate_andstatement(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 367, in evaluate_andstatement
    r = self.evaluate_statement(cur.right)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 235, in evaluate_statement
    return self.evaluate_notstatement(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 281, in evaluate_notstatement
    v = self.evaluate_statement(cur.value)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 251, in evaluate_statement
    return self.evaluate_statement(cur.inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 231, in evaluate_statement
    return self.evaluate_andstatement(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 359, in evaluate_andstatement
    l = self.evaluate_statement(cur.left)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 207, in evaluate_statement
    return self.method_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 557, in method_call
    res = obj.method_call(method_name, args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\baseobjects.py", line 81, in method_call
    return method(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\compiler.py", line 653, in has_header_method
    return self._has_header_impl(args[0], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\compiler.py", line 638, in _has_header_impl
    haz, cached = self.compiler.has_header(hname, kwargs['prefix'], self.environment,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 351, in has_header
    return self.compiles(code, env, extra_args=extra_args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\compilers.py", line 1310, in compiles
    with self._build_wrapper(code, env, extra_args, dependencies, mode, disable_cache=disable_cache) as p:
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\compilers.py", line 1291, in _build_wrapper
    args = self.build_wrapper_args(env, extra_args, dependencies, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 420, in build_wrapper_args
    extra_args = mesonlib.listify([e(mode.value) if callable(e) else e for e in extra_args])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\mixins\clike.py", line 420, in <listcomp>
    extra_args = mesonlib.listify([e(mode.value) if callable(e) else e for e in extra_args])
                                   ^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\interpreter\compiler.py", line 274, in _determine_args
    args += self.compiler.get_option_compile_args(opts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\cpp.py", line 857, in get_option_compile_args
    args = super().get_option_compile_args(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\compilers\cpp.py", line 816, in get_option_compile_args
    options.set_value(key,  'c++14')
  File "C:\Users\Boshe\AppData\Local\Programs\Python\Python311\Lib\site-packages\mesonbuild\coredata.py", line 940, in set_value
    self.overrides[key] = value
    ~~~~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object does not support item assignment

subprojects\harfbuzz\meson.build:217:15: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!

```
**system parameters**
* Plain native build
* Windows 11
* Python 3.11.6
* meson 1.5.0
* ninja 1.11.0, if it was used.

**Comment by dcbaker** [comment] 2024-07-25 22:23
I think this was fixed by https://github.com/mesonbuild/meson/pull/13459, can you test the master branch and see if this issue still appears?

**Comment by eli-schwartz** [comment] 2024-07-25 22:38
Duplicate of #13402

**Comment by eli-schwartz** [comment] 2024-07-25 22:38
Yes, it should certainly be fixed by that, and we're in the middle of rolling out version 1.5.1 which will include that fix.

**Closed by eli-schwartz** 2024-07-25 22:38 UTC
