### ISSUE TITLE
Building gnome packages on windows requires a python3 executable

### ISSUE THREAD

**Issue by guruDanny67** [mesonbuild/meson#1510] opened 2017-03-24 15:50 UTC
I'm trying to build the new json-glib (1.2.8) on windows in the wingtk project using meson and it uses the gnome import to do some stuff (enums, gir, ...).

The problem is that gnome looks for a python3 executable that it's not present on windows: it's something similar to #1315 but on the user side (if IU understand correctly the issue).

On windows the correct way to check for python 3 seems to run 'py -3' (or py -3.5 if you need a particular versione) or look at the output of 'python --version' because there is no executable named python3. 

If you copy, say, the 3.5.2 python.exe as python3.exe in the same directory of the original one everything is ok and the build continues but it's not always possible to change the installation stuff on the destination machine.

tested on meson 0.39.0, thanks in advance.

**Comment by nirbheek** [comment] 2017-03-24 16:09
Please paste the exact errors that you are facing. AFAIK, we do not specifically look for `python3.exe` anywhere inside Meson.

**Comment by guruDanny67** [comment] 2017-03-25 09:22
This is the output (with meson 0.39.0):
--- Start ----
(py35-gtk3) C:\gtk-build\build\Win32\release\json-glib-build>c:\dev\py35\python.exe c:\gtk-build\tools\meson-0.39.0\meson.py ..\json-glib
The Meson build system
Version: 0.39.0
Source dir: C:\gtk-build\build\Win32\release\json-glib
Build dir: C:\gtk-build\build\Win32\release\json-glib-build
Build type: native build
Project name: json-glib
Native c compiler: cl (msvc 19.00.24215.1)
Build machine cpu family: x86
Build machine cpu: x86
Found pkg-config: C:\gtk-build\gtk\win32\release\bin\pkg-config.EXE (0.29.1)
Native dependency gobject-2.0 found: YES 2.52.0
Native dependency gio-2.0 found: YES 2.52.0
Has header "unistd.h": NO
Compiler for c supports argument -we4002: YES
Compiler for c supports argument -we4003: YES
Compiler for c supports argument -w14010: YES
Compiler for c supports argument -we4013: YES
Compiler for c supports argument -w14016: YES
Compiler for c supports argument -we4020: YES
Compiler for c supports argument -we4021: YES
Compiler for c supports argument -we4027: YES
Compiler for c supports argument -we4029: YES
Compiler for c supports argument -we4033: YES
Compiler for c supports argument -we4035: YES
Compiler for c supports argument -we4045: YES
Compiler for c supports argument -we4047: YES
Compiler for c supports argument -we4049: YES
Compiler for c supports argument -we4053: YES
Compiler for c supports argument -we4071: YES
Compiler for c supports argument -we4819: YES
Program g-ir-scanner found: NO
Configuring config.h using configuration
Program glib-mkenums found: YES (@PERL_PATH@ C:\gtk-build\gtk\win32\release\bin\glib-mkenums)
Configuring json-version.h using configuration
Program python3 found: NO

Meson encountered an error in file json-glib\tests\meson.build, line 18, column 0:
Program "python3" not found.
--- End ----

The python3 executable is looked in the file mesonbuild\modules\python3.py

Thanks

**Comment by TingPing** [comment] 2017-03-25 09:31
The current way to find python within a build script is (which should work on Windows):

```meson
python3 = import('python3').find_python()
```

If the build script calls `find_program('python3')` though I believe that is just on them.

**Comment by nirbheek** [comment] 2017-03-25 09:33
This is not a Meson bug. The problem is that json-glib is looking for `python3` instead of using the python3 module. They should replace `find_program('python3')` with `import('python3').find_python()`.

Meson already knows what Python 3 is via `sys.executable` so this will always be correct.

**Comment by nirbheek** [comment] 2017-03-25 09:34
@tingping you beat me to it due to undue advantage! I'm on my phone. :p

**Comment by TingPing** [comment] 2017-03-25 09:37
btw at a glance the `python3` module isn't documented either.

**Comment by jpakkane** [comment] 2017-03-25 10:40
Added documentation to the wiki. Closing as this is not a Meson bug.

**Closed by jpakkane** 2017-03-25 10:40 UTC
Labels: support
