### ISSUE TITLE
[regression in meson-0.55.0] It doesn't see that "C" is already in the list of langiages for "vala" projects

### ISSUE THREAD

**Issue by yurivict** [mesonbuild/meson#7550] opened 2020-08-05 20:36 UTC
gradio-7.3 has this line in ```meson.build```:
```
project('gradio', ['vala', 'C'], version : '7.3')
```

but meson-0.55.0 says that "C" should be added:
```
meson.build:1:0: ERROR: Compiling Vala requires C. Add C to your project languages and rerun Meson.
```

OS: FreeBSD 12.1
The problem observed in the FreeBSD port ```audio/gradio```.
Full build log: http://package22.nyi.freebsd.org/data/113amd64-default-PR244008/2020-07-15_21h37m37s/logs/errors/gradio-7.3.log

**Comment by dcbaker** [comment] 2020-08-05 20:41
Possibly a duplicate of #7495?

**Comment by nirbheek** [comment] 2020-08-05 22:19
Duplicate of #7495

**Closed by nirbheek** 2020-08-05 22:19 UTC
Labels: regression, vala
