### ISSUE TITLE
Feature request, using JSON instead pickle unpickle for meson exec,

### ISSUE THREAD

**Issue by lygstate** [mesonbuild/meson#7647] opened 2020-08-26 12:02 UTC
**Describe the bug**
The dumped pickle file are binary data and hard to see the content for debugging

**To Reproduce**
Please include your `meson.build` files, preferably as a minimal toy example showing the issue.
You may need to create simple source code files (don't include private/proprietary code).

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
* what Python version are you using e.g. 3.8.0
* what `meson --version`
* what `ninja --version` if it's a Ninja build

**Comment by eli-schwartz** [comment] 2020-08-26 13:23
>  The dumped pickle file are binary data and hard to see the content for debugging

I assume you mean the build directory's `*.dat` files?
They're not dumped anywhere, they are internal state files stored in the "meson-private/" directory and are therefore private.

Public files are stored in JSON in meson-info/.

There is zero reason to be introspecting those files. If you need to debug meson itself, there are better ways. And JSON by definition cannot store python objects needed to resume the build, so you'd need to recompute everything...

**Comment by lygstate** [comment] 2020-08-26 13:32
> > The dumped pickle file are binary data and hard to see the content for debugging
> 
> I assume you mean the build directory's `*.dat` files?
> They're not dumped anywhere, they are internal state files stored in the "meson-private/" directory and are therefore private.
> 
> Public files are stored in JSON in meson-info/.
> 
> There is zero reason to be introspecting those files. If you need to debug meson itself, there are better ways. And JSON by definition cannot store python objects needed to resume the build, so you'd need to recompute everything...

The JSON in meson-info not complete, if I just want to test a single command, I even don't what's the 
command content are.

**Comment by eli-schwartz** [comment] 2020-08-26 13:44
Well, only the information in meson-info is stable, so I don't get what you want to do with it anyway.

What precisely do you want to test? Maybe if they better understood the problem, the meson developers could evaluate the utility of switching to JSON or suggest alternatives such as adding more info to the JSON files.

I very much doubt anything will change if you don't provide a technical rationale for why it's better that way. And at least from my perspective, based on what you've said so far, I find it very hard to imagine a rationale.

**Comment by lygstate** [comment] 2020-08-26 13:56
> Well, only the information in meson-info is stable, so I don't get what you want to do with it anyway.
> 
> What precisely do you want to test? Maybe if they better understood the problem, the meson developers could evaluate the utility of switching to JSON or suggest alternatives such as adding more info to the JSON files.
> 
> I very much doubt anything will change if you don't provide a technical rationale for why it's better that way. And at least from my perspective, based on what you've said so far, I find it very hard to imagine a rationale.

```
For example:

build qemu.syms: CUSTOM_COMMAND libqemuutil.a | E$:/CI-Cor-Ready/xemu/qemu.org/scripts/undefsym.sh C$:/CI-Tools/msys64/mingw64/bin/x86_64-w64-mingw32-nm.EXE
 COMMAND = "C:/CI-Tools/msys64/mingw64/bin/python3.exe" "E:/CI-Cor-Ready/xemu/qemu.org/meson/meson.py" "--internal" "exe" "--unpickle" "E:/CI-Cor-Ready/xemu/qemu.org-x64/meson-private/meson_exe_sh_783fab9aa10daba2c47de638e11492402e9653af.dat"
 description = Generating$ qemu.syms$ with$ a$ meson_exe.py$ custom$ command

In fact are doing
E:/CI-Cor-Ready/xemu/qemu.org/scripts/undefsym.sh C:/CI-Tools/msys64/mingw64/bin/x86_64-w64-mingw32-nm.EXE libqemuutil.a > qemu.syms

But I can not easily see that from build.ninja or other place
```

**Comment by eli-schwartz** [comment] 2020-08-26 14:51
Duplicate of #2900

`--internal exe --unpickle` is used whenever the force_serialize option is set in the backend generator. This happens:

- for the vs2010 backend in cases that are commented as "Always use a wrapper because MSBuild eats random characters when there are many arguments."

- for the ninja backend, on Windows if there are "extra compiler paths", or anywhere if there is an exe_wrapper or the command line has newline chars.

The other problem is this is `capture: true` in which case part of the logic for the command is meson saving stdout directly and writing it to a file instead of scripts/undefsym.sh accepting an output filename for this. So it would need to use `--internal exe --capture`...

Really, meson --internal should print this if ninja asks it to, but it's not clear how to tell that to ninja. The solution is *not* to dig into private implementation files, though, but fixing the linked bug.

**Comment by lygstate** [comment] 2020-08-26 16:21
> Duplicate of #2900
> 
> `--internal exe --unpickle` is used whenever the force_serialize option is set in the backend generator. This happens:
> 
> * for the vs2010 backend in cases that are commented as "Always use a wrapper because MSBuild eats random characters when there are many arguments."
> * for the ninja backend, on Windows if there are "extra compiler paths", or anywhere if there is an exe_wrapper or the command line has newline chars.
> 
> The other problem is this is `capture: true` in which case part of the logic for the command is meson saving stdout directly and writing it to a file instead of scripts/undefsym.sh accepting an output filename for this. So it would need to use `--internal exe --capture`...
> 
> Really, meson --internal should print this if ninja asks it to, but it's not clear how to tell that to ninja. The solution is _not_ to dig into private implementation files, though, but fixing the linked bug.
The problem when new one trying to do something with meson, they have digging into build.ninja to see if ninja are generated properly, and if people are seen unpickle things there, then that's would be really hard for the user
An alternative way is when genereated pickle file, also generating a text/json file for easy access.

**Comment by eli-schwartz** [comment] 2020-12-10 16:15
Duplicate of #2900

**Closed by eli-schwartz** 2020-12-10 16:15 UTC
