### ISSUE TITLE
Stop using distutils in python module

### ISSUE THREAD

**Issue by rubenrua** [mesonbuild/meson#10251] opened 2022-04-08 16:27 UTC
**Describe the bug**
The python module uses `distutils`  [inside the INTROSPECT_COMMAND](https://github.com/mesonbuild/meson/blob/0.62.0/mesonbuild/modules/python.py#L319). But [distutils](https://docs.python.org/3.10/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12. (See the [What’s New](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated) entry for more information). 

**To Reproduce**
Use the meson Python module with Python 3.12

**Expected behavior**
Keep working.

A solution could be using `sysconfig.get_paths`. But maybe keep using `distutils` for old versions of Python it is necessary.

**Comment by eli-schwartz** [comment] 2022-04-08 16:53
Duplicate of #7702

**Closed by eli-schwartz** 2022-04-08 16:53 UTC

**Comment by eli-schwartz** [comment] 2022-04-08 16:56
Note that we already use sysconfig to get path information.

As discussed in the linked ticket, distutils is only used:
- on Debian to discover information that debian goes against upstream Python with, because that information is NOT available in sysconfig despite that upstream Python would like them to add it
- discovering whether an extension module is supposed to link to libpython (dll requirement, elf DT_NEEDED) which is NOT available in sysconfig last I checked, and varies by both python version and OS

**Comment by rubenrua** [comment] 2022-04-08 17:05
Thank you for the information

FYI the 3.10 version of python in debian and ubuntu has changed its installation scheme from 'posix_prefix' to the debian-specific 'posix_local'.  I think 'sysconfig.get_paths()' can be used with that version.

More info https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1967920
