### ISSUE TITLE
Error in mesonbuild/cmake/toolchain.py in: self.toolchain_file.resolve()

### ISSUE THREAD

**Issue by brechtsanders** [mesonbuild/meson#8406] opened 2021-02-24 08:16 UTC
When building GTK4 (v4.0.3) with meson on Windows using MinGW-w64 GCC under MSYS2 shell I got the following error output when building from an ImDisk RAM disk:
```
Found CMake: D:\Prog\winlibs64-9.2.0\custombuilt\bin\cmake.EXE (3.19.5)
Traceback (most recent call last):
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\mesonmain.py", line 132, in run
    return options.run_func(options)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\msetup.py", line 275, in run
    app.generate()
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\msetup.py", line 183, in generate
    self._generate(env)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\msetup.py", line 222, in _generate
    intr.run()
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreter.py", line 4800, in run
    super().run()
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 641, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 666, in evaluate_codeblock
    raise e
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 659, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 674, in evaluate_statement
    self.assignment(cur)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 1341, in assignment
    value = self.evaluate_statement(node.value)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 672, in evaluate_statement
    return self.function_call(cur)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 1031, in function_call
    return func(node, func_args, kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 515, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 4 more times]
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 210, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreterbase.py",
line 229, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreter.py", line 3767, in func_dependency
    d = self.dependency_impl(name, display_name, kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\interpreter.py", line 3861, in dependency_impl
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\dependencies\base.py", line 2432, in find_external_dependency
    d = c()
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\dependencies\base.py", line 1122, in __init__
    CMakeDependency.class_cmakeinfo[self.for_machine] = self._get_cmake_info(cm_args)
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\dependencies\base.py", line 1160, in _get_cmake_info
    toolchain = CMakeToolchain(self.env, self.for_machine, CMakeExecScope.DEPENDENCY, self._get_build_dir())
  File "D:\Prog\winlibs64-9.2.0\custombuilt\lib\mesonbuild\cmake\toolchain.py",
line 59, in __init__
    self.toolchain_file = self.toolchain_file.resolve()
  File "D:\Prog\Python\WinPython64-3.7.4.1Zero\python-3.7.4.amd64\lib\pathlib.py", line 1151, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "D:\Prog\Python\WinPython64-3.7.4.1Zero\python-3.7.4.amd64\lib\pathlib.py", line 202, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1] Incorrect function: 'R:\\winlibs64-9.2.0\\gtk-4.0.3\\build_both\\meson-private\\cmake_cairo-script-interpreter'
```

I'm using meson 0.57.1.
When I comment out the line `self.toolchain_file = self.toolchain_file.resolve()` in `mesonbuild/cmake/toolchain.py` meson works fine and the build completes without issues.

Is that line of code necessary, or can it be omitted for Windows?
Or would it be a good idea to catch the error and continue anyway when it occurs?

**Comment by brechtsanders** [comment] 2021-03-01 16:45
See also: #7295

**Comment by mensinda** [comment] 2021-05-29 14:29
To be honest, from #7295, this seems to be a general issue with Python `pathlib` and your setup. Which python version are you using? Could you check with the following script whether this is a general Python issue by trying out some problematic paths?

```python
#!/usr/bin/env python3

from pathlib import Path
import sys

for p in sys.argv:
  print(f'Trying "{p}"  ', end='')
  try:
    Path(p).resolve()
    print('   [OK]')
  except OSError:
    print('  [ERROR]')
```

If this really is a Python/pathlib bug then the right fix would be to fix it upstream instead of working around this issue in Meson.

**Comment by brechtsanders** [comment] 2021-05-30 09:02
I'm using [WinPython](http://winpython.github.io/) 3.7.4 but I'm calling it from MSYS2 shell.
I get `[ERROR]` running your test script from RAM drive.

I also tried calling the script from a Command Prompt instead of MSYS2 shell, and also got `[ERROR]`, except this time the path being resolved used backslashed instead of slashes.

When putting the test script on a normal disk I get no error.

I build over 2000 packages from source in MSYS2 shell on RAM drive (for speed) and Meson seems to be the only one that has problems with this.

But in principle I agree if it's a Python issue they should fix it.

**Comment by mensinda** [comment] 2021-05-30 10:46
Then I am closing this issue since this is a duplicate of #7295.

**Closed by mensinda** 2021-05-30 10:46 UTC
Labels: OS:windows, cmake
