### ISSUE TITLE
unit test `test_options_with_choices_changing` fails on macOS CI

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#7847] opened 2020-10-14 13:07 UTC
```
test_options_with_choices_changing (__main__.AllPlatformTests)
Detect when options like arrays or combos have their choices change. ... FAIL
[...]
======================================================================

FAIL: test_options_with_choices_changing (__main__.AllPlatformTests)

Detect when options like arrays or combos have their choices change.

----------------------------------------------------------------------

Traceback (most recent call last):
  File "run_unittests.py", line 3347, in test_options_with_choices_changing
    self.assertEqual(item['value'], 'b')
AssertionError: 'a' != 'b'
- a
+ b

Stdout:

The Meson build system
Version: 0.55.999
Source dir: /Users/travis/build/mesonbuild/meson/test cases/unit/84 change option choices
Build dir: /Users/travis/build/mesonbuild/meson/tmpd1fn25wf
Build type: native build
Project name: change option choices
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 0
Found ninja-1.10.1 at /usr/local/bin/ninja
ninja explain: output all of phony edge with no inputs doesn't exist
ninja: no work to do.
```

**Comment by nirbheek** [comment] 2020-10-14 13:08
I can't reproduce this on my mac mini which runs macOS Big Sur with XCode Python 3. Would be good if someone could look into it.

**Comment by mensinda** [comment] 2020-10-14 13:28
Duplicate of #7835. See also for the PR that introduced this test #7736.

**Closed by mensinda** 2020-10-14 13:28 UTC
Labels: CI, macos, meson tests
