### ISSUE TITLE
Can't figure out the right syntax to declare a dependency on dl

### ISSUE THREAD

**Issue by tesseract241** [mesonbuild/meson#9487] opened 2021-10-28 20:37 UTC
I'm currently working on a project on Linux that requires dynamic loading of libraries, so I would normally give the linker the '-ldl' argument, and this was my first solution.  
In an attempt to use a more idiomatic approach, I've been trying to create a dependency, and that's where I've hit a snag:  
while `meson.get_compiler().find_library('dl')` works,  
`dependency('dl', method: system)`, which according to the docs should make the same call behind the curtain, doesn't (giving the "Dependency "dl" not found" message).  
What am I doing wrong?

**Comment by eli-schwartz** [comment] 2021-10-31 04:06
It may also be too confusing, because a dependency object is assumed to carry a lot more metadata and possibly compile flags as well. It doesn't need to implement a straight duplicate of find_library for cases where it doesn't provide added value.

**Closed** 2021-10-31 11:52 UTC
