### ISSUE TITLE
install_headers(preserve_path)

### ISSUE THREAD

**Issue by sarum9in** [mesonbuild/meson#3371] opened 2018-04-09 02:41 UTC
```meson
# proj/kola.h -> /usr/include/myproj/kola.h
install_headers('proj/kola.h', subdir : 'myproj')

# proj/kola.h -> /usr/include/myproj/proj/kola.h
install_headers('proj/kola.h', subdir : 'myproj', preserve_path : true)
```

```meson
# you can write
install_headers(
    'foo/bar.h',
    'baz/bob.h',
    subdir : 'proj',
    preserve_path : true,
)

# instead of
install_headers('foo/bar.h', subdir : 'proj/foo')
install_headers('baz/bob.h', subdir : 'proj/baz')
```

One possible alternative to consider is `preserve_path_from : directory`, but it introduces invalid uses of API and by calling `install_headers` from subdirectory the same behavior can be achieved with proposal above, so I don't think it's worth implementing.

@textshell also mentioned:
My usecase was a list of headers to install. Where the headers might not be all in one directory. Allowing that usecase is esp. important for an IDE integration that can modify file lists, but is not smart enough to actually write and auto maintain more general elements in a meson.build file.
And i belive editing file lists should be the primary write interaction of an IDE with the meson.build files. Because meson files are really not easy to auto maintain because they allow all kinds of different styles and usages.
Also i think IDEs automatically editing target definitions to add files is not what most projects expect. I think most somewhat bigger projects have lists of files instead of a list in the target definition call.

**Comment by FFY00** [comment] 2018-08-23 22:13
Is this planned to be resolved? It's been a while since it was reported.

**Comment by tristan957** [comment] 2019-07-23 07:23
This is a bug, not an enhancement. This is also a duplicate of #14 I believe.

https://github.com/mesonbuild/meson/issues/14#issuecomment-514084255

Why does Meson only support a flat directory structure?

**Comment by tristan957** [comment] 2019-07-23 07:30
I would like to submit a PR to fix this bug.

https://github.com/mesonbuild/meson/blob/1f4023fa47803458700e52352dec51f3f85fa6c1/mesonbuild/minstall.py#L390
https://github.com/mesonbuild/meson/blob/2e41d53e4d64985d58f06235604feafa7dad5059/mesonbuild/interpreter.py#L3445

These files look promising. @sarum9in do you have any advice here?

**Comment by tristan957** [comment] 2019-10-11 15:52
Going to repeat this. I would like to submit a PR, but I need guidance. Do I need to take this to the mailing list?

**Comment by textshell** [comment] 2019-10-13 11:09
I'd say the best way for implementation guidance questions is IRC and (sometimes) in the issues discussing the feature.

But you actually found some of the relevant places already. You would have to look into `self.source_strings_to_files(args)` to replace it with something that returns the relative paths in addition to the file objects. (or use source_strings_to_files and additionally safe the path in a place near to the result of source_strings_to_files)

But keep in mind, as this is a new feature it needs approval by @jpakkane before a PR can be merged. While showing clean working code in a PR often makes it easier to get attention and approval for an idea, it always carries the risk of being work that does not pan out.

(I still think meson should have this.)

**Comment by jpakkane** [comment] 2019-10-14 21:36
Note that most people keep their headers in a single directory tree and install it with [install_subdir](https://mesonbuild.com/Reference-manual.html#install_subdir). This ensures that the header layout is the same in your source tree and install prefix.

**Comment by textshell** [comment] 2019-10-14 21:46
You might still want to exclude private headers. Or the project mixes sources and headers into one directory (e.g. qtcreator only works properly with that layout).

install_headers using preserve_path from a suitable directory makes it easy to keep the layout in the install prefix the same as in the source tree.
Also if that header list is generated (could be something simple as a "find", or maybe something in the IDE) it needs a lot less manual (or "badly scripted") work when a new subdirectory with includes gets added.

**Comment by tristan957** [comment] 2019-10-14 22:14
Maybe the way I want to do things is an antipattern. Maybe what I need to be doing is grouping related header files together into arrays. and calling multiple `install_headers` with different subdir arguments. It also make sense code wise. Install headers on a module by module basis.

Say I have

* `http-client.h`
* `http-request.h`
* `http-response.h`
* `json-value.h`
* `json-object.h`
* `json-parser.h`

Then I could have Meson code that looks like

```meson
install_headers(http_headers, install_dir: 'my_proj', subdir: 'http')
install_headers(json_headers, install_dir: 'my_proj', subdir: 'json')
```

Thoughts? Maybe if people in this thread come to an agreement, we could amend the docs to specifically call out this use case.

**Closed** 2022-05-30 22:03 UTC
Labels: enhancement, install targets
