### ISSUE TITLE
Computation of PACKAGE_PREFIX_DIR in Config.cmake file on Windows uses \..\.. instead of ../../

### ISSUE THREAD

**Issue by ret2libc** [mesonbuild/meson#9702] opened 2021-12-05 18:20 UTC
**Describe the bug**
Generating a CMake Config file on Windows results in @PACKAGE_INIT@ macro generating the wrong cmake code, which prevents correct computation of the PACKAGE_PREFIX_DIR variable.

**To Reproduce**
meson.build:
```
project('test', 'c')

cmake_mod = import('cmake')

conf = configuration_data()
cmake_mod.configure_package_config_file(
  name: 'myProject',
  input: 'myProject.cmake.in',
  configuration: conf)
```
myProject.cmake.in:
```
@PACKAGE_INIT@
```
execute:
```sh
$ meson build
$ cat build\myProjectConfig.cmake

####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was C:\Users\Riccardo\source\repos\test\myProject.cmake.in ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/..\..\.." ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()
```

####################################################################################

**Expected behavior**
```
$ cat build\myProjectConfig.cmake

####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was C:\Users\Riccardo\source\repos\test\myProject.cmake.in ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()
```
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 10
* what Python version are you using e.g. 3.10.0
* what `meson --version` 0.60.2
* what `ninja --version` if it's a Ninja build 1.8.2

**Comment by Tachi107** [comment] 2022-02-04 10:37
Duplicate of https://github.com/mesonbuild/meson/issues/6955

**Closed** 2023-07-13 20:26 UTC
Labels: module:cmake
