### ISSUE TITLE
Loses flags when defining both CPPFLAGS and CFLAGS

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#8361] opened 2021-02-16 15:41 UTC
This is Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982865

The issue is that if you specify both `CFLAGS` and `CPPFLAGS`, then `CPPFLAGS` is ignored, probably because some variable is overwritten.

Bisection points to commit 4b0b44aface1cd9ed073733.

**Comment by mbiebl** [comment] 2021-02-16 15:48
duplicate of #8345 ?

**Comment by evverx** [comment] 2021-02-17 02:22
> duplicate of #8345 ?

@mbiebl thanks! Looks like it is a duplicate of that issues. I didn't notice that all the flags got lost there. I'll close that issue in favor of this one shortly.

@jpakkane Looking at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982865#34, given that it appears just building large projects like systemd (which seems to have caught all the C regressions with its CI in about five minutes) in real-life scenarios would help to catch issues like this, I think that instead of relying on people manually testing broken prereleases or trying to gate the meson package somewhere downstream it would be better to test meson much more thoroughly upstream. It's kind of being discussed in https://github.com/mesonbuild/meson/issues/8347

**Closed** 2021-02-17 12:46 UTC
Labels: regression
