### ISSUE TITLE
0.59.0 is unable to build glib with gtk_doc=true

### ISSUE THREAD

**Issue by fabiscafe** [mesonbuild/meson#9124] opened 2021-08-16 17:22 UTC
Hi. I'm trying to build glib in Arch Linux. Archlinux shipps with [meson 0.59.0](https://archlinux.org/packages/extra/any/meson/) currently. Sadly this version does have an regression. If you try to build [glib](https://gitlab.gnome.org/GNOME/glib) with following build options:
``` 
 arch-meson glib build \
    -D glib_debug=disabled \
    -D selinux=disabled \
    -D man=true \
    -D gtk_doc=true
  meson compile -C build
```

This results in following error

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 227, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 281, in run
    app.generate()
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 184, in generate
    self._generate(env)
  File "/usr/lib/python3.9/site-packages/mesonbuild/msetup.py", line 223, in _generate
    intr.run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 2479, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 132, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 554, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 643, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1992, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 163, in evaluate_statement
    return self.function_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 554, in function_call
    res = func(node, func_args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 643, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1992, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_statement
    return self.evaluate_if(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 257, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 157, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 150, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 167, in evaluate_statement
    return self.method_call(cur)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 598, in method_call
    return self._holderify(obj.method_call(method_name, args, kwargs))
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 766, in method_call
    ret = method(state, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 643, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 643, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 643, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreterbase/decorators.py", line 106, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/modules/gnome.py", line 1142, in gtkdoc
    self.interpreter.add_test(state.current_node, check_args, check_kwargs, True)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1892, in add_test
    t = self.make_test(node, args, kwargs)
  File "/usr/lib/python3.9/site-packages/mesonbuild/interpreter/interpreter.py", line 1866, in make_test
    if kwargs['timeout'] <= 0:
KeyError: 'timeout'
```
Full log: [glib2-2.69.1-1.1-x86_64-build.log](https://github.com/mesonbuild/meson/files/6994184/glib2-2.69.1-1.1-x86_64-build.log)

This problem doesn't appear with meson 0.58.1. It also will not appear at all if `gtk_doc=false`. Sadly I'm not experienced enough to track this down even more.

**Comment by eli-schwartz** [comment] 2021-08-16 17:31
Duplicate of #9081

Fixed in the 0.59.1 milestone.

**Comment by eli-schwartz** [comment] 2021-08-16 17:32
Duplicate of #9081

**Closed by eli-schwartz** 2021-08-16 17:31 UTC

**Comment by fabiscafe** [comment] 2021-08-16 17:33
Thanks :+1:

**Comment by eli-schwartz** [comment] 2021-08-16 17:34
Duplicate of #9009
