### ISSUE TITLE
One generated source depend on another generated source

### ISSUE THREAD

**Issue by NickeZ** [mesonbuild/meson#2382] opened 2017-09-28 22:38 UTC
I don't know if I'm missing something or if this is a feature request..

So I have two generators where the output from the first is used as input in the second. My first idea was something like this:

```
aslib_lex_c = flex.process('asLib_lex.l')

aslib_c = yacc.process(
    'asLib.y',
    aslib_lex_c,
)
```

But I've also tried other things like:

```
aslib_lex_c = flex.process('asLib_lex.l')
aslib_lex_c_dep = declare_dependency(sources: [aslib_lex_c])

aslib_c = yacc.process(
    'asLib.y',
    extra_depends: aslib_lex_c_dep,
)
```

I guess I can make it work by only using custom targets. But then I thought it would have been clean to encapsulate everything about the custom targets by using a generator.

**Comment by nirbheek** [comment] 2017-09-29 20:21
Duplicate of https://github.com/mesonbuild/meson/issues/1141.

**Closed by nirbheek** 2017-09-29 20:21 UTC
