### ISSUE TITLE
cc.links() with declare_dependency() unexpected error

### ISSUE THREAD

**Issue by scivision** [mesonbuild/meson#6073] opened 2019-10-18 16:51 UTC
I think that `<compiler>.links()` tests should allow declare_dependency() to be passed as an `dependencies:` argument, but I get an error instead. Here's an MWE:

```meson
project('links_deps', 'c')

cc = meson.get_compiler('c')
z_lib = cc.find_library('z')
z_dep = declare_dependency(dependencies: z_lib)

z_ok = cc.links('int main(void) { return 0; }', dependencies: z_dep)
```

This unexpectedly makes error:

```
ERROR: Dependencies must be external dependencies
```

The error is from https://github.com/mesonbuild/meson/blob/master/mesonbuild/interpreter.py#L1088

And indeed, the declare_dependency is of type `InternalDependency`

## Why I need this to work

I often "build up" external dependencies using `declare_dependency()` because I need to specify `dirs` and `include_directories` and other stuff where dependency() does not find the library due to missing/broken pkg-config and `cmake/Find<library>.cmake`

That is, my motivating use case is like the following line with a bunch of if/elif--that's why I need to use declare_dependency in `cc.links(..., dependencies: hard_to_find_dep)` as follows:

```meson

hard_dep = dependency('hard_to_find', required: false)
if not hard_dep.found()
... # bunch of nested if/elif depending on OS, etc. resulting in found `hard_to_find_lib`

hard_dep = declare_dependency(include_directories: hardinc, dependencies: hard_to_find_lib)
endif


cc.links(..., dependencies: hard_dep)   # makes error noted above
```

**Comment by eli-schwartz** [comment] 2021-09-03 01:46
Duplicate of #1430, #4513

**Comment by eli-schwartz** [comment] 2021-09-03 01:46
Duplicate of #1430

**Closed by eli-schwartz** 2021-09-03 01:46 UTC
Labels: dependencies
