### ISSUE TITLE
[Vala] can't compile files that have the same name but are on different directories

### ISSUE THREAD

**Issue by tintou** [mesonbuild/meson#2412] opened 2017-10-01 14:18 UTC
When a project has two files with the same name in multiple directories, meson claims that it has `Multiple producers for Ninja target`
Here is a branch that adds the required test case https://github.com/tintou/meson/commit/960bf0e921d59d301b29e19596d1b398628d4324
I believe that the issue is located in [`./mesonbuild/backend/ninjabackend.py` line 1136](https://github.com/mesonbuild/meson/blob/master/mesonbuild/backend/ninjabackend.py#L1136) but I have no idea how can I fix this.

Thanks in advance

**Comment by nirbheek** [comment] 2017-10-02 01:15
Duplicate of https://github.com/mesonbuild/meson/issues/633.

**Closed** 2017-10-04 18:52 UTC
Labels: bug, vala
