### ISSUE TITLE
custom module

### ISSUE THREAD

**Issue by clouds56** [mesonbuild/meson#5336] opened 2019-04-30 16:31 UTC
It is nice that meson currently support so many frameworks via modules (and keep growing).
I'm trying to use meson on windows build with WDK, and would like to get environment variable `$WindowsSdkDir`, after some search I found the issue https://github.com/mesonbuild/meson/pull/2796, which encourage writing modules for the purpose.

Is it possible to load custom module outside the meson repo, like this?
```
meson.register("modulename", "path-to-module.py")
```
So that we could easily develop/test module before it is usable/stable and goes into the meson repo.

Also I do not know where to start writing a module, hope there could be some doc for writing a module. I think cuda module https://github.com/mesonbuild/meson/commit/592af0b1afa03b10beffee481c00c60a7b7db907 is a good start and would check out that.

To the prosperity of meson.

**Comment by clouds56** [comment] 2019-04-30 16:51
I've read some code in modules and have some questions
1. is it just enough just put the `<modulename>.py` file in the `meson/modules` folder?
2. what is state in arguments?
3. could we have multiple instances of the `ExtensionModule`, for different versions (I do know qt4/qt5, but there are lots of versions of WDK, so I prefer `wdk_18362 = import("WDK", version: "10.0.18362.0")`)
4. how to get target/host arch, configuration (debug/release)?
5. is it possible or how to return an object/dictionary contains several values? like `{"flags": ["-W3"], "define": ["DEBUG"], ...}`?
6. is it possible or how to filter/change default flags of compiler, e.g. for wdk, we should not link against `user32.lib`? or in another way, how to inherit default `executable/library` target and change some properties?

**Comment by clouds56** [comment] 2019-04-30 17:05
I'm trying to answer the questions on my own understanding, correct me if I'm wrong.
1. yes, the `import("modulename")` would interpret `mesonbuild.modules.modulename.initialize` and you could use [`ExtensionModule`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/__init__.py) as helper here
```py
from . import ExtensionModule

class MyModule(ExtensionModule):
  pass

def initialize(*args, **kwargs):
  return MyModule(*args, **kwargs)
```

*Keep updating*

**Comment by clouds56** [comment] 2019-04-30 18:17
`ModuleReturnValue(return_value, new_objects: list)` takes 2 parameters
* the `return_value` is actual return value (would be wrapped with `holderify`)
https://github.com/mesonbuild/meson/blob/2e1fca02a5a59b355dd13ff8127a906b508bde18/mesonbuild/interpreter.py#L2111
  supported type: (`list`), `int`, `str`, `bool`, `NoneType`, `build.CustomTarget`, `build.Executable`, `build.GeneratedList`, `build.Data`, `dependencies.InternalDependency`, `dependencies.ExternalDependency`, `dependencies.ExternalProgram` (but not `build.RunTarget`, `build.RunScript`) and `ObjectHolder`
   if the type is `list`, it would recursively `holderify` the child
* the `new_objects` act like side effect, which add object inside holder to interp (**TODO**: relationship with subproject), you could add new target this way. (**TODO**: example)

**Comment by clouds56** [comment] 2019-05-01 03:09
#### misc helper functions
* `@noPosargs`, `@noKwargs`, `@stringArgs`, `@permittedKwargs`, `@FeatureNewKwargs`, `@FeatureDeprecatedKwargs` from `..interpretbase` could be useful when dealing with arguments of api from both `ExtensionModule` and `InterpreterObject`, and they would automatically detect parameters of python function

**Comment by franczc** [comment] 2019-05-31 07:14
Hi clouds56,
Is it possible to execute a meson function, e.g. custom_target() within the <modulename>.py?

**Comment by clouds56** [comment] 2019-06-04 04:13
I didn't find a way to do that,
for `custom_target`, you have to copy this https://github.com/mesonbuild/meson/blob/5465fc5e28e0435945e869a322a6fa66ed4cb070/mesonbuild/interpreter.py#L4029 function to your custom module.
If you return a `ExecutableHolder` or `SharedLibraryHolder` it should simply work. (So the key is to construct such a holder)

**Comment by franczc** [comment] 2019-06-06 05:53
Thanks for the tip!

**Comment by eli-schwartz** [comment] 2020-03-18 20:05
This issue should be closed as "Won't Implement", because it violates [FAQ: Why is Meson not just a Python module so I could code my build setup in Python?](https://mesonbuild.com/FAQ.html#why-is-meson-not-just-a-python-module-so-i-could-code-my-build-setup-in-python)

The suggestion from the linked issue was to write an "android.py" module and submit it as a pull request for inclusion into the meson project. NOT to have people ship "android.py" meson modules in their own project next to meson.build, and have it be loaded as turing-complete custom code in their build system.

"Registering" a custom user module, written in python, into meson, is a thing that will, by design, never be accepted as a permitted feature...

**Closed** 2020-11-22 21:34 UTC

**Comment by michaelgruner** [comment] 2021-07-06 20:27
May ask why? I used to have a bunch of M4 files (when using auto tools) that I could just ship with my projects, as opposed manually adding the code to each project. Is there a recommended way to achieve this?

**Comment by eli-schwartz** [comment] 2021-07-06 22:58
Is your interest in m4 modules, because you want to copy-paste meson.build content? Or because you want to do something turing-complete that has full access to meson's interpreter state and can generate build.ninja rules on its own?

In the former case you might be interested in #5209 and similar (not yet implemented).

I've seen lots of m4 files, and ***many*** of them did stuff that didn't really belong there.

...

In the latter case, the best option is probably to factor out what you want your custom module to do, such that it becomes generic enough to be useful to other people as well, and then as I said above:

> submit it as a pull request for inclusion into the meson project.

**Comment by michaelgruner** [comment] 2021-07-07 00:41
Thanks for your answer @eli-schwartz. My answer is definitely the former:
> Is your interest in m4 modules, because you want to copy-paste meson.build content? 

Basically replace a bunch of dependency checks, macro exports, info logging, etc... Yes #5209 seems to be exactly what I need. Thanks!

**Comment by eli-schwartz** [comment] 2021-07-07 00:48
Great, happy to help clarify. :) Hopefully someone will implement include_file() or similar one day (can I tempt you into working on it???).

This would actually be easier for users to use because it's all meson.build and you'd just move it from file to file, vs. the custom module solution that requires finicky conformance to an entire module state and using internal APIs to access public build definition calls which would be... hacky. So yeah, including files is definitely the way to go indeed.

**Comment by eirnym** [comment] 2024-11-25 13:58
@eli-schwartz 

The problem I came here with is to set additional parameters for test executables. From meson standpoint it's the same executable as main program/library, so I can't target them directly.

In my project I have 8 submodules, each of them has tests and I don't want copy-paste them all and I can't target them specifically during compile phase.

Additionally, #5209 is closed because Meson team don't want to have these includes "because of bad habits", but copy-paste is way worse than defining common places.
