### ISSUE TITLE
cannot use subproject's includes in own project's includes

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#796] opened 2016-09-18 05:08 UTC
Let's say I'm using a subproject **S** in my project **P**. My project has **`include`** directory that I use to store `.hpp` files and declare it in meson.build too. Let's say subproject **S** too uses some other directory, declares it in it's own meson.build and also declares it in `declare_dependency` so that it is available to others.

So if I try to use subproject **S**'s include files in my **P**'s `include/someFile.hpp`, it fails with something like this - 

``` bash
[6/7] Compiling cpp object 'test/testexe@exe/test.cpp.o'
FAILED: test/testexe@exe/test.cpp.o 
ccache c++  '-Itest/testexe@exe' '-fdiagnostics-color=always' '-I../test' '-Itest' '-Iinclude' '-I../include' '-pipe' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++14' '-O0' '-g' '-I/usr/src/gtest' '-pthread' '-MMD' '-MQ' 'test/testexe@exe/test.cpp.o' '-MF' 'test/testexe@exe/test.cpp.o.d' -o 'test/testexe@exe/test.cpp.o' -c ../test/test.cpp
In file included from ../include/device_LED.hpp:4:0,
                 from ../test/test.cpp:2:
../include/device.hpp:7:20: fatal error: json.hpp: No such file or directory
 #include <json.hpp>
                    ^
compilation terminated.
ninja: build stopped: subcommand failed.
```

but if I use them in my `*.cpp` files, they build succesfully.

But ofcourse I need them in my header files too....

**Comment by agauniyal** [comment] 2016-09-18 05:13
Here is the project - https://github.com/agauniyal/isaac-core/tree/develop
Here is the subproject - https://github.com/nlohmann/json
Here is subproject's meson.build - https://github.com/mesonbuild/json/blob/2.0.3/meson.build

**Comment by agauniyal** [comment] 2016-09-18 05:20
I've also tried to do -

```meson.build

# in main meson.build

json_sp = subproject('json')
json_inc = json_sp.get_variable('inc')
json_dep = json_sp.get_variable('json_dep')


# in src/meson.build

corelib = library('isaac-core', prog_sources, include_directories: [inc, json_inc],
		dependencies: [uWS_dep, json_dep])
```

But no effect on error message.

**Comment by agauniyal** [comment] 2016-09-18 05:36
Okay it only works if I add those subprojects as dependency to final executable. But I've also added them as dependency on library too, and that library links with executable at the end, so shouldn't I just have to specify only in the library because it has the main dependency not the executable.

**Comment by agauniyal** [comment] 2016-10-05 17:55
ping?

**Comment by nioncode** [comment] 2019-01-01 15:56
Is this still broken? If so, please provide a minimal project that I can clone to reproduce.

**Comment by agauniyal** [comment] 2019-02-17 13:23
Just create a subproject which declares its dependencies, try to include it in another project. Your another project won't build until you provide those dependencies explicitly in cpp files. 

This is what I recall, I don't use meson right now but if I get some time to I'd try to reproduce this behavior.

**Comment by eli-schwartz** [comment] 2021-11-22 19:47
It sounds like you have:
- a subproject dependency with include_directories
- a library that adds a dependency on the subproject dependency
- an executable that links to the library, but also has a direct dependency on the subproject include_directories.

The problem here is that the subproject is *both* an indirect and a direct dependency, and a library normally encapsulates its private dependencies so that the executables linking to them, don't need private details of the library.

This isn't really a "bug". And making every library also recursively expose its private dependencies would break other projects -- users should be able to declare that a library, once built, stands on its own merit, surely?

But you can use `declare_dependency(link_with: corelib, include_directories: json_inc)` to create a dependency object that provides both.

**Comment by eli-schwartz** [comment] 2023-02-24 16:12
Closing as by design

**Closed by eli-schwartz** 2023-02-24 16:12 UTC
Labels: dependencies
