### ISSUE TITLE
usability: meson build in same way as meson test and meson configure

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2419] opened 2017-10-03 16:08 UTC
I am sorry if this is a duplicate, but it seems to me that it would be logical with a `meson build` command in the same was as `meson test` and `meson configure`. This would then do the right thing across backends, and there would be no need to worry about different commands. Possibly just `meson`?

**Comment by TingPing** [comment] 2017-10-03 16:13
`build` might be an unfortunate word considering many use that as their build directory name.

**Comment by nirbheek** [comment] 2017-10-03 16:31
I think we can only make this change after we remove the current `meson srcdir builddir` syntax

**Comment by gauteh** [comment] 2017-10-03 16:40
Nirbheek Chauhan writes on oktober 3, 2017 18:31:
> I think we can only make this change after we remove the current `meson srcdir builddir` syntax
>

It is easy to mess up with the commands and the build-dirs (e.g. `meson
configurer`), usually it doesn't result in anything else than an error, 
but it feels a bit illogical that sometimes the first argument is a dir 
and sometimes a command.

Along the same lines:

* It would be nice to have a one-line configure and build command:
  `meson build [build-dir]`. But, if you're thinking about changing the
  syntax, then this would be dependent on that.

* Why does `meson configure` need a `-D` option, it would be
  more straightforward with e.g. `meson configure [build-dir] enable-feature=true`.

**Comment by adrianjohnson** [comment] 2017-10-03 21:21
You could use 'meson make' to avoid the 'build' clash. And also add 'meson install'. Then it would follow the autotools configure, make, make install pattern that we are all familiar with.

**Comment by astavale** [comment] 2017-10-04 11:58
> You could use 'meson make' to avoid the 'build' clash. And also add 'meson install'. Then it would follow the autotools configure, make, make install pattern that we are all familiar with.

Meson is really more a configuration tool for your build system. So the equivalent of `make` is `ninja` when using the Ninja backend. For `make install` it is `ninja install`. I presume there was a design choice not to add a mapping of `meson install` to the equivalent backend install rule.

This makes me think `meson configure builddir` would be a good equivalent to `meson buildir`. Although at present this gives an error `Directory builddir does not seem to be a Meson build directory.` With the addition of a bash autocompletion script it wouldn't be too much typing. It would be `meson c[TAB]` to get `meson configure `.

**Comment by gauteh** [comment] 2017-10-04 12:00
Al Thomas writes on oktober 4, 2017 13:59:
>> You could use 'meson make' to avoid the 'build' clash. And also add 'meson install'. Then it would follow the autotools configure, make, make install pattern that we are all familiar with.
> 
> Meson is really more a configuration tool for your build system. So the equivalent of `make` is `ninja` when using the Ninja backend. For `make install` it is `ninja install`. I presume there was a design choice not to add a mapping of `meson install` to the equivalent backend install rule.
> 
> This makes me think `meson configure builddir` would be a good equivalent to `meson buildir`. Although at present this gives an error `Directory builddir does not seem to be a Meson build directory.` With the addition of a bash autocompletion script it wouldn't be too much typing. It would be `meson c[TAB]` to get `meson configure `.

That makes sense. I'd still argue that a backend-agnostic `build`/`make` command would be very convenient.

**Comment by nirbheek** [comment] 2017-10-04 12:42
> I'd still argue that a backend-agnostic `build`/`make` command would be very convenient.

I want this to happen too, for a bunch of reasons:

1. User won't have to worry about knowing `msbuild` syntax on windows (which is quite arcane, especially for cleaning)
2. You would be able to do `meson build src/foo/` to only build targets defined inside that source directory, which covers an important workflow for people currently using recursive autotools

**Comment by TheQwertiest** [comment] 2020-05-28 16:08
Duplicate of https://github.com/mesonbuild/meson/issues/6670
Fixed by https://github.com/mesonbuild/meson/pull/6690

**Closed** 2020-05-29 12:07 UTC
Labels: enhancement
