### ISSUE TITLE
run_target failure post 0.57.0

### ISSUE THREAD

**Issue by tolnaisz** [mesonbuild/meson#8927] opened 2021-06-23 16:52 UTC
With release version 0.57.0 and later the previous functionality of run_target has changed without a release note mention and causes setup issues.

In our setup we have a few run_target:s which execute additional checks/packaging steps. Not all are necessary to be executed when building (like packaging) the sources. The extra steps are executing some command-line tool like CppCheck.

Pre-0.57.0 we were able to have a run_target in our meson.build files even on machines where the command-line tool wasn't present (some developer machines). Of course it wasn't possible to "build" those targets on those machines but that wasn't even a problem as those were not meant to be done anyway and are not built by default.

Post-0.57.0 this isn't possible anymore. The setup fails on machines without all the tools with an error saying that the tool isn't found. This check isn't necessary and the previous functionality was correct. The target should be only created and it should fail only when "built".

The issue was introduced by the be86199 commit (Fix run_targets running scripts from different subdirs.).

**Comment by eli-schwartz** [comment] 2021-06-23 16:55
Duplicate of #8641

**Closed by eli-schwartz** 2021-06-23 16:55 UTC
