### ISSUE TITLE
Meson should look for gtk3-update-icon-cache as well as gtk4-update-icon-cache

### ISSUE THREAD

**Issue by Miezhiko** [mesonbuild/meson#10175] opened 2022-03-24 06:54 UTC
affects meson 0.62.0

reproducable on gtk3 https://gitlab.gnome.org/GNOME/gtk/-/issues/4778

and on gnome-system-monitor
and more...

(if this is duplicate please point to me actual bug)

**Comment by eli-schwartz** [comment] 2022-03-24 06:58
Duplicate of #10174

**Comment by eli-schwartz** [comment] 2022-03-24 06:58
Fixed in git master, will be released in 0.62.1

Sorry for the typo. :(

**Closed by eli-schwartz** 2022-03-24 06:58 UTC
