### ISSUE TITLE
Unity builds don't work for Vala projects

### ISSUE THREAD

**Issue by AnsgarKlein** [mesonbuild/meson#8055] opened 2020-11-30 14:25 UTC
**Describe the bug**
Unity projects as described [here](https://mesonbuild.com/Unity-builds.html) don't work for Vala projects. Meson first generates C code from every vala file then creates a unity C file which includes all generated C files.
Compilation then fails due to multiple redefinition errors.

**To Reproduce**
Reproducing this is easy as everything but the most basic Vala code in conjungtion with unity builds triggers the bug:

`meson.build`
```
project('example', 'vala', 'c')

dependencies = [dependency('glib-2.0'), dependency('gobject-2.0')]
sources = files(['main.vala', 'foo.vala'])

executable('example', sources, dependencies: dependencies)
```

`main.vala`
```
public static int main(string[] args) {
    Foo foo = new Foo("main");
    return foo.identifier.length;
}
```

`foo.vala`
```
class Foo {
    public string identifier;

    public Foo(string identifier) {
        this.identifier = identifier;
    }
}
```

Prepare build and check that compilation works:

```
meson setup builddir
ninja -C builddir
```

Enabling unity builds should trigger bug:

```
meson configure -Dunity=on builddir
ninja -C builddir
```

**Expected behavior**
C code generated by `valac` does not support this type of unity build. The correct way for unity builds for Vala code would be to concatenate all vala source files and then generate C code from the resulting vala file.

I have created a workaround that checks if building a unity build with `meson.is_unity()` and concatenates all sources using a `custom_target` with a bash script. It would of course be nice if meson could handle this correctly by default.

I've attached that workaround and the example above.

[vala-unity.tar.gz](https://github.com/mesonbuild/meson/files/5616485/vala-unity.tar.gz)

**system parameters**
* Running Fedora 32
* Tested with meson 0.55.3 from Fedora 32 repo as well as meson 0.56.0 via pip
* Using Python 3.8.6
* Using Ninja 1.10.1
* Tested with both gcc and clang

**Comment by AnsgarKlein** [comment] 2020-11-30 14:33
Sorry I just realized this is a duplicate of #5280
This issue provides more information though

**Comment by eli-schwartz** [comment] 2020-11-30 14:43
Can you cross post it to there then?

Duplicate of #5280

**Closed by eli-schwartz** 2020-11-30 14:43 UTC

**Comment by eli-schwartz** [comment] 2020-11-30 14:46
Can you cross post it to there then?
