### ISSUE TITLE
lib64 detection is overzealous

### ISSUE THREAD

**Issue by alexlarsson** [mesonbuild/meson#2557] opened 2017-10-30 14:45 UTC
The flatpak freedesktop.org runtime doesn't use lib64, it always uses /usr/lib, even on x86-64. However, due to the linux ABI specification we have to have a `/lib/ld-linux-x86-64.so.2`, and flatpak runtimes are always usr-merged, with a symlink `/lib` -> `/usr/lib`.

So:
```
 $ flatpak run --command=ls org.freedesktop.Sdk/x86_64/1.6 -l /usr/lib64
total 0
lrwxrwxrwx 1 alex wheel 27 okt 30 15:07 ld-linux-x86-64.so.2 -> ../lib/ld-linux-x86-64.so.2
```

Meson detects this as "you should use lib64", so we have a patch to work around this in the sdk:
https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/meson-no-lib64.patch

It would be nice if this could be somewhat smarter, or configuratble when you build meson.

**Comment by ignatenkobrain** [comment] 2017-10-30 14:49
why not to specify --libdir in commandline?

**Comment by alexlarsson** [comment] 2017-10-30 14:52
I want to change the default libdir for all apps built with the sdk version of meson, not change a particular build.

**Comment by alexlarsson** [comment] 2017-10-30 14:53
Currently the default is:
```
    if os.path.isdir('/usr/lib64') and not os.path.islink('/usr/lib64'):
        return 'lib64'
    return 'lib'
```

I happen to have a /usr/lib64 which is not a symlink for reasons, but that doesn't mean i want meson to use that by default.

**Comment by nirbheek** [comment] 2017-11-29 06:54
Then the question is, is there a better way to detect what the default libdir is?

**Comment by TingPing** [comment] 2017-11-29 10:51
Load a distro override from a file maybe?

**Comment by alexlarsson** [comment] 2017-11-29 10:52
Allowing the person who builds meson to define the default should be good enough.

**Comment by TingPing** [comment] 2018-01-15 06:16
So just to expand this `autoconf` loads a shell script a `$datadir/config.site` which sets the various default directories. This gives the distributor complete control over this so it can be as simple or complex as their needs and I think is an ok fit for `meson` except it would be a Python module of course. I don't think a static file will do since there can be so many edge cases (`gentoo` apparently has a massive script).

**Comment by nirbheek** [comment] 2018-05-25 14:38
Duplicate of https://github.com/mesonbuild/meson/issues/2038

(consolidating libdir detection issues in one place)

**Closed by nirbheek** 2018-05-25 14:38 UTC
Labels: bug, help wanted
