### ISSUE TITLE
Can't get attribute 'OctalInt' on <module 'mesonbuild.coredata

### ISSUE THREAD

**Issue by paulnegz** [mesonbuild/meson#8887] opened 2021-06-16 02:14 UTC
I get the same error as #8425 and uninstalling and reinstalling does not fix the problem. I attempted to uninstall using the pip command 

**system parameters**
* operating system (Ubuntu 18.04, etc.)
* Python version 3.8.5
* `meson -- 0.58.1`
![meson](https://user-images.githubusercontent.com/37233089/122147455-8cb5d680-ce1e-11eb-86f2-330ca2a8985c.JPG)

**Comment by eli-schwartz** [comment] 2021-06-16 03:03
- please do not use screenshots of text, there is nothing readable in there
- As far as I can tell there is still nothing new here.

Duplicate of #8425

**Comment by eli-schwartz** [comment] 2021-06-16 03:03
Duplicate of #8425

**Closed by eli-schwartz** 2021-06-16 03:03 UTC
