### ISSUE TITLE
Recursive extract_all_objects() not working as expected on macOS

### ISSUE THREAD

**Issue by ePirat** [mesonbuild/meson#4281] opened 2018-09-28 11:23 UTC
I tried using extract_all_objects()  instead of a helper library + link_whole for a test, but I got a lot of linker errors with that:

```
[57/62] Linking target tests/checkasm.
FAILED: tests/checkasm 
cc  -o tests/checkasm 'tests/tests@@checkasm@exe/checkasm_checkasm.c.o' 'tests/tests@@checkasm@exe/checkasm_mc.c.o' 'dav1d_bitdepth_8@sta/src_ipred.c.o' 'dav1d_bitdepth_8@sta/src_itx.c.o' 'dav1d_bitdepth_8@sta/src_ipred_prepare.c.o' 'dav1d_bitdepth_8@sta/src_lf_apply.c.o' 'dav1d_bitdepth_8@sta/src_loopfilter.c.o' 'dav1d_bitdepth_8@sta/src_mc.c.o' 'dav1d_bitdepth_8@sta/src_cdef_apply.c.o' 'dav1d_bitdepth_8@sta/src_cdef.c.o' 'dav1d_bitdepth_8@sta/src_lr_apply.c.o' 'dav1d_bitdepth_8@sta/src_looprestoration.c.o' 'dav1d_bitdepth_8@sta/src_recon.c.o' 'dav1d_bitdepth_8@sta/src_x86_mc_init.c.o' 'dav1d_bitdepth_10@sta/src_ipred.c.o' 'dav1d_bitdepth_10@sta/src_itx.c.o' 'dav1d_bitdepth_10@sta/src_ipred_prepare.c.o' 'dav1d_bitdepth_10@sta/src_lf_apply.c.o' 'dav1d_bitdepth_10@sta/src_loopfilter.c.o' 'dav1d_bitdepth_10@sta/src_mc.c.o' 'dav1d_bitdepth_10@sta/src_cdef_apply.c.o' 'dav1d_bitdepth_10@sta/src_cdef.c.o' 'dav1d_bitdepth_10@sta/src_lr_apply.c.o' 'dav1d_bitdepth_10@sta/src_looprestoration.c.o' 'dav1d_bitdepth_10@sta/src_recon.c.o' 'dav1d_bitdepth_10@sta/src_x86_mc_init.c.o' 'libdav1dentrypoint@sta/src_lib.c.o' 'libdav1dentrypoint@sta/src_thread_task.c.o' 'dav1d_private@sta/src_picture.c.o' 'dav1d_private@sta/src_data.c.o' 'dav1d_private@sta/src_ref.c.o' 'dav1d_private@sta/src_getbits.c.o' 'dav1d_private@sta/src_obu.c.o' 'dav1d_private@sta/src_decode.c.o' 'dav1d_private@sta/src_cdf.c.o' 'dav1d_private@sta/src_msac.c.o' 'dav1d_private@sta/src_tables.c.o' 'dav1d_private@sta/src_scan.c.o' 'dav1d_private@sta/src_dequant_tables.c.o' 'dav1d_private@sta/src_intra_edge.c.o' 'dav1d_private@sta/src_lf_mask.c.o' 'dav1d_private@sta/src_ref_mvs.c.o' 'dav1d_private@sta/src_warpmv.c.o' 'dav1d_private@sta/src_wedge.c.o' 'dav1d_private@sta/src_qm.c.o' 'dav1d_private@sta/src_x86_cpu.c.o' -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-headerpad_max_install_names  
Undefined symbols for architecture x86_64:
  "_dav1d_avg_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_cpu_cpuid", referenced from:
      _get_cpu_flags in src_x86_cpu.c.o
  "_dav1d_cpu_xgetbv", referenced from:
      _get_cpu_flags in src_x86_cpu.c.o
  "_dav1d_mask_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_regular_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_regular_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_sharp_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_sharp_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_smooth_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_8tap_smooth_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_prep_bilin_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_regular_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_regular_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_sharp_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_sharp_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_smooth_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_smooth_regular_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_8tap_smooth_sharp_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_put_bilin_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_w_avg_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
  "_dav1d_w_mask_420_avx2", referenced from:
      _dav1d_mc_dsp_init_x86_8bpc in src_x86_mc_init.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[58/62] Generating 'dav1d_private@sta/mc.obj'.
ninja: build stopped: subcommand failed.
```

The code can be found here: https://code.videolan.org/ePirat/dav1d/tree/gramner-twoorioles/dav1d-checkasm

**Comment by xclaesse** [comment] 2018-09-28 12:49
Is it only for MacOS? I believe extract_all_objects() never was meant to be recursive.

**Comment by xclaesse** [comment] 2018-09-28 12:52
That's the case that should have been fixed by commit 60aaee55 in release 0.46, right?

**Comment by ePirat** [comment] 2018-09-28 18:35
Yes, I think so?

**Comment by ePirat** [comment] 2018-09-28 22:48
If I am not mistaken, these objects that are missing are the ones we compile with nasm and added to sources (those can't be added to the `objects` kwarg which is a very weird inconsistency, but thats another issue):

```
nasm_objs = nasm_gen.process(libdav1d_sources_asm)

[…]

libdav1d_private = static_library('dav1d_private',
    libdav1d_sources, nasm_objs,
    objects: [bitdepth_objs, entrypoints_objs],
    include_directories: dav1d_inc_dirs,
    c_args: [stackalign_flag],
    install: false,
    build_by_default: false,
)
```

**Comment by ePirat** [comment] 2018-10-01 10:36
This is a duplicate of #2479

**Comment by xclaesse** [comment] 2018-11-01 19:54
Shouldn't `nasm_objs` be mobed to `objects:` array? There are not source files, are they?

**Comment by ePirat** [comment] 2018-11-01 20:28
Probably the reason might be that a generator can generate objects but could also generate source files, no?

**Comment by xclaesse** [comment] 2018-11-01 20:31
Generated sources will be picked by extract_all_objects() but it filters out non-source files.

> those can't be added to the objects kwarg which is a very weird inconsistency, but thats another issue

I don't think it's another issue, to the opposite I think it's the root cause. Can you tell me more why that doesn't work ?

**Comment by ePirat** [comment] 2018-11-01 20:33
It throws a meson error:

```
src/meson.build:194:0: ERROR:  Generated files are not allowed in the 'objects' kwarg for target 'dav1d'.
It is meant only for pre-built object files that are shipped with the
source tree. Try adding it in the list of sources.
```

**Comment by xclaesse** [comment] 2018-11-01 20:34
oh. Indeed doc says the same 'never use this for object files that you build yourself'. Ok my mistake then. Yes so that filter I quoted above needs to be relaxed.

**Comment by ePirat** [comment] 2018-11-01 20:36
Note that the documentation about that makes not much sense. It is impossible to follow the advice of "never use this for object files that you build yourself", as object files obtained with `extract_objects()` have to be added to the `objects` kwarg, not to sources (it will error), which is very confusing.

**Closed** 2018-11-02 19:40 UTC
