### ISSUE TITLE
Non-string options cannot be passed to `meson setup --reconfigure`

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#5467] opened 2019-06-10 08:46 UTC
Running something like:

    mkdir build
    cd build
    meson setup $PWD ..
    meson setup --reconfigure --strip $PWD ..

will result in the following error:

```
  File "/home/work/upstream/meson/mesonbuild/mesonmain.py", line 127, in run
    return options.run_func(options)
  File "/home/work/upstream/meson/mesonbuild/msetup.py", line 240, in run
    app.generate()
  File "/home/work/upstream/meson/mesonbuild/msetup.py", line 158, in generate
    self._generate(env)
  File "/home/work/upstream/meson/mesonbuild/msetup.py", line 215, in _generate
    coredata.update_cmd_line_file(self.build_dir, self.options)
  File "/home/work/upstream/meson/mesonbuild/coredata.py", line 761, in update_cmd_line_file
    config['options'].update(options.cmd_line_options)
  File "/usr/lib64/python3.6/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/usr/lib64/python3.6/configparser.py", line 1237, in __setitem__
    self._parser._validate_value_types(option=key, value=value)
  File "/usr/lib64/python3.6/configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
```

because `other["strip"]` is the boolean `True` value.

**Comment by bonzini** [comment] 2020-08-17 16:18
Duplicate of #4888.

**Comment by eli-schwartz** [comment] 2021-03-09 14:03
Duplicate of #4888

**Closed by eli-schwartz** 2021-03-09 14:03 UTC
