### ISSUE TITLE
changing cpp_std does not trigger re-configuration by ninja

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2435] opened 2017-10-06 09:05 UTC
I changed, in meson.build:

```
project ('astroid', ['cpp', 'c'],
    default_options : [ 'cpp_std=c++11'] )
```

to 

```
project ('astroid', ['cpp', 'c'],
    default_options : [ 'cpp_std=c++14'] )
```

but when I run ninja in `build` there's `no work to do`.

**Comment by nirbheek** [comment] 2017-10-06 09:10
Duplicate of https://github.com/mesonbuild/meson/issues/2193.

**Closed by nirbheek** 2017-10-06 09:10 UTC
