### ISSUE TITLE
Call meson using python -m meson

### ISSUE THREAD

**Issue by naveen521kk** [mesonbuild/meson#7953] opened 2020-11-07 15:14 UTC
**Feature Request**
I would like to call meson using
```sh
python -m meson <args>
```
docs: [`__main__.py`](https://docs.python.org/3/library/__main__.html?highlight=__main__%20py#module-__main__)
Adding a simple `__main__.py` would solve this issue. But I noticed that the module name `mesonbuild` rather `meson` is there a particular reason why it is named so?

## Use Case
I am on Appveyor and I would like to meson there using their python because I am building something which requires the python header, so I could easily shift between `x86` and `x64` python version using direct path instead of path manipulation. I would simply call it using direct path rather than path manipulation.

Also, this would be so helpful, if I run it inside a python scipt and I could get the python executable using 
```py
import sys
print(sys.executable)
```
So, I could simply call it using the path recieved. Now, I find a `__main__.py` in repo, but why is it in root directory rather than inside `mesonbuild` directory?

## The solution
Copy the `meson.py` (with slight edit) inside the `mesonbuild`(should be `meson`?) as `__main__.py` and it is fixed.

**Comment by G-Sheridan** [comment] 2020-11-23 01:34
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by eli-schwartz** [comment] 2020-11-23 02:14
@naveen521kk,

You can currently do this via `python -m mesonbuild.mesonmain`.

The `__main__.py` file is intended merely to make this usable via `python -m zipapp /path/to/meson-checkout` to create a single-file executable out of the box. Although I don't know that it's doing a great job of it. :o

**Comment by naveen521kk** [comment] 2020-11-23 03:52
I don't think that is packed and published to PyPI. It shouldn't be actually.
So adding a `__main__.py` inside `mesonbuild` directory would work.
And for the zipapp thing, they could do, `python -m zipapp /path/to/meson-checkout --main meson.py` instead.

**Comment by scivision** [comment] 2020-11-24 15:14
using meson installed via `pip install -e meson/` this does work already:

```sh
python -m meson build
```
where run from the directory where meson.build file is, Meson configures the project in the build/ directory as usual.

---

However, when using a PyPi meson via `pip install meson`, the error:

```
python.exe: No module named meson.__main__; 'meson' is a package and cannot be directly executed
```

**Comment by eli-schwartz** [comment] 2020-11-24 15:27
@scivision

Given the module name is `mesonbuild`, not meson, I don't see how that's surprising in the least.

**Comment by jpakkane** [comment] 2020-11-24 15:34
We intentionally do not expose a Python module because it would mean we would have to maintain API compatibility and all that. If you want to use a certain Python to run Meson, do `/path/to/your/python3 /path/to/meson.py <args>`.

**Comment by scivision** [comment] 2020-11-24 15:39
OK that's good to know, thanks

**Comment by naveen521kk** [comment] 2020-11-25 09:04
> If you want to use a certain Python to run Meson, do /path/to/your/python3 /path/to/meson.py <args>.

That `meson.py` doesn't come up when installing using `pip` though.

**Comment by eli-schwartz** [comment] 2020-11-25 18:58
We can use meson.py directly in the zipapp, so I propose to delete `__main__.py` entirely due to confusion. See #8032 

If there's no `__main__.py`, users won't be confused ad think this is supported.

**Comment by eli-schwartz** [comment] 2020-11-25 19:00
> That `meson.py` doesn't come up when installing using `pip` though.

when installing using `pip`, the `meson` program is created as intended. I do not see the problem here. If you're using pip, then meson is bound to a specific python executable.

**Comment by naveen521kk** [comment] 2020-11-26 11:17
Ok. Now, exactly the problem is that there are multiple python version installed, and everything is in path. 

Suppose, let's say I have some old meson version installed in python3.6 and new meson version installed in python3.7. Both are in path variable and python3.6 comes first. Now, I will be unable to call the meson installed with python3.7 directly without path manipulation, which can be done but it would be lot better to call using `python3.7 -m meson` or `py -3.7 -m meson`.

**Comment by jpakkane** [comment] 2020-11-27 16:10
The "executables" created by Setuptools are just Python scripts (at least on non-Windows). You can do `/path/to/somepython3 /path/to/meson <args>` and it should work. I just tested it with a different program in a virtualenv and it seemed to work.

**Comment by naveen521kk** [comment] 2020-11-27 17:09
I don't understand what does `/path/to/meson` mean. Possibly if you meant the folder that pip installed then it may be very difficult to find.

**Comment by eli-schwartz** [comment] 2020-12-10 20:20
> The "executables" created by Setuptools are just Python scripts (at least on non-Windows). You can do `/path/to/somepython3 /path/to/meson <args>` and it should work. I just tested it with a different program in a virtualenv and it seemed to work.

The python script merely imports mesonbuild and calls the entrypoint main function. So I don't see how this could possibly work... unless multiple python versions each have mesonbuild installed to site-packages..

**Closed** 2021-05-05 15:11 UTC
