### ISSUE TITLE
pkg-config: Support for arbitrary variables

### ISSUE THREAD

**Issue by fooishbar** [mesonbuild/meson#1096] opened 2016-11-23 18:34 UTC
pkg-config supports querying arbitrary variables, which is something we make use of in two places in Wayland.

Firstly, we install a .pc for the wayland-scanner generator/utility, so it's a little bit easier to find and a little bit harder to get wrong. This involves a custom wayland_scanner variable in the pkg-config file.

Secondly, we also use it in other places for the plugin directory setting. GStreamer also does this (and a couple of other things, e.g. GST_API_VERSION), and as a result has to use configure_file rather than built-in pkg-config support. I take it from #620 that this is desirable to fix.

**Comment by QuLogic** [comment] 2016-11-23 23:45
This is a dupe of #726 and I think it's available already.

**Comment by nirbheek** [comment] 2016-11-23 23:49
Yes, this is already available, however you need 0.36.0 for this:

https://github.com/mesonbuild/meson/wiki/Reference-manual#dependency-object

A workaround if you need to use an older Meson is to use `run_command` to call `pkg-config --variable foo` manually.

**Comment by fooishbar** [comment] 2016-11-24 07:33
What about arbitrary variables in file generation?

**Comment by nirbheek** [comment] 2016-11-24 09:59
We're planning on adding more features to that, but it's not urgent since there's a good workaround. The recommended way to do non-trivial pkg-config file generation is to use `configure_file` on a `.pc.in` file. Most projects already have them, and using them helps keep Autotools and Meson build systems in-sync for projects that have both.

I see that in Wayland you also already have `.pc.in` files, so just running `configure_file` with `install_dir:` should work out for you.

**Comment by nirbheek** [comment] 2016-11-28 15:13
Closing this since improving pkg-config generation is already on the TODO list.

**Closed by nirbheek** 2016-11-28 15:13 UTC
Labels: support

**Comment by whot** [comment] 2017-05-18 00:24
fwiw, support for variables in file generation was added with commit 7ed19902be3f866ff599822b56cea5a34ec661d1
