### ISSUE TITLE
windows: master chokes on `c_std=gnu99` setting in meson.build

### ISSUE THREAD

**Issue by boxerab** [mesonbuild/meson#7611] opened 2020-08-18 18:46 UTC
These lines are from the latest `Pango` `meson.build`:

```
      # We only need c99, but glib needs GNU-specific features
          # https://github.com/mesonbuild/meson/issues/2289
          'c_std=gnu99',
        ],
```

version `0.54` of meson handles it correctly, but not master.

**Comment by xclaesse** [comment] 2020-08-18 18:49
What's the error message?

**Comment by rabindra-harlalka** [comment] 2020-08-18 18:53
> What's the error message?
```
The Meson build system
Version: 0.55.999
Source dir: C:\Work\...\src\pango
Build dir: C:\Work\...\src\pango\build
Build type: native build
Project name: pango
Project version: 1.45.1

C:\Work\...\src\pango\meson.build:1:0: ERROR: Value "gnu99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11".
```

**Comment by dcbaker** [comment] 2020-08-18 18:56
What compiler are you using?

**Comment by rabindra-harlalka** [comment] 2020-08-18 18:58
MSVC. Running from Visual Studio x64 command prompt; backed in the default (ninja)

**Comment by xclaesse** [comment] 2020-08-18 19:02
Ok, gave it a try, got :
```
meson.build:1:0: ERROR: Value "gnu89" (of type "string") for combo option "C language standard to use" is not one of the
 choices. Possible choices are (as string): "none", "c89", "c99", "c11".
```

Which makes sense, MSVC clearly does not support GNU C. Wondering why that ever worked, but indeed it was working with 0.55.

**Comment by boxerab** [comment] 2020-08-18 19:03
> 
> Which makes sense, MSVC clearly does not support GNU C. Wondering why that ever worked, but indeed it was working with 0.55.

a miracle! So, just need to replace `gnu` with `c` .

**Comment by xclaesse** [comment] 2020-08-18 19:04
cc @dcbaker since that's likely a regression from https://github.com/mesonbuild/meson/pull/6597.

@jpakkane did we have a policy that setting unknown c_std should gracefully fallback to some default value?

**Comment by xclaesse** [comment] 2020-08-18 19:17
Confirmed that GLib with MSVC is indeed broken now.

**Comment by xclaesse** [comment] 2020-08-18 19:28
For context, glib does in many places `#if defined(__GNUC__)`. So if the compiler supports gnu99 it uses it, but it can be built without it too.

**Comment by xclaesse** [comment] 2020-08-19 02:05
Bisected and it seems to be https://github.com/mesonbuild/meson/pull/7556. It actually would make sense, before that PR if I understand correctly MSVC compiler did not have c_std option at all, so it was unchecked.

cc @scivision @nirbheek

**Comment by scivision** [comment] 2020-08-19 02:16
Should that (my) PR simply be reverted? It seems i handled this flag too casually, not even adding a test case for it.

**Comment by xclaesse** [comment] 2020-08-19 03:18
I think we should revert while we figure out an actual solution here.

It's tricky because it's true that it makes no sense to set c_std=gnu99 for MSVC, but it also make sense to ask for gnu99 when using gcc/clang because the code can easily have macros that would use GNU extensions when available. I'm not even sure what difference does it make to gcc/clang when they build with -std=c99 vs -std=gnu99 tbh, would need the light of a compiler expert :p

Maybe we need a new option `c_std=gnu_if_available_99` :D

**Comment by boxerab** [comment] 2020-08-19 12:22
> I think we should revert while we figure out an actual solution here.
> 
> It's tricky because it's true that it makes no sense to set c_std=gnu99 for MSVC, but it also make sense to ask for gnu99 when using gcc/clang because the code can easily have macros that would use GNU extensions when available. I'm not even sure what difference does it make to gcc/clang when they build with -std=c99 vs -std=gnu99 tbh, would need the light of a compiler expert :p
> 
> Maybe we need a new option `c_std=gnu_if_available_99` :D

Can we just ignore this flag for MSVC ? As it does not and never will fully support C99. MS rationale : if you want C99, use C++.

**Comment by xclaesse** [comment] 2020-08-19 12:29
It looks like they added C11 recently, that's what https://github.com/mesonbuild/meson/pull/7556 is about.

**Comment by boxerab** [comment] 2020-08-19 12:40
thanks, so there just needs to be a filter on the value.

**Comment by tp-m** [comment] 2020-09-11 09:58
This breakage has now landed in a stable release (0.55.2), not great.

**Comment by xclaesse** [comment] 2020-09-11 12:13
@nirbheek I think https://github.com/mesonbuild/meson/issues/7599 needs to be reverted in 0.55.3 and release asap.

**Comment by xclaesse** [comment] 2020-09-11 12:18
Sorry, it's https://github.com/mesonbuild/meson/pull/7556.

**Comment by nirbheek** [comment] 2020-09-11 12:29
It's already been done in the branch, 0.55.3 will be released tonight.

**Closed** 2020-11-13 15:49 UTC
Labels: compilers, regression, windows
