### ISSUE TITLE
Can't seem to find compiler (MSYS2/MinGW), which can be run fine manually

### ISSUE THREAD

**Issue by lunakid** [mesonbuild/meson#5755] opened 2019-08-01 21:01 UTC
Please let me know what more information may be useful, beyond the console capture below:

```
D:\szabi\SW\devel\tool\build\meson\meson.exe build
The Meson build system
Version: 0.51.1
Source dir: E:\dev.tmp\c++\mingw-win32
Build dir: E:\dev.tmp\c++\mingw-win32\build
Build type: native build
Project name: mingw-win32
Project version: undefined

meson.build:1:0: ERROR: Unknown compiler(s): ['icl', 'cl', 'c++', 'g++', 'clang++', 'clang-cl']
The follow exceptions were encountered:
Running "icl " gave "[WinError 2] The system cannot find the file specified"
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
Running "c++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "g++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang++ --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang-cl /?" gave "[WinError 2] The system cannot find the file specified"

A full log can be found at E:\dev.tmp\c++\mingw-win32\build\meson-logs\meson-log.txt

E:\dev.tmp\c++\mingw-win32>g++
g++: fatal error: no input files
compilation terminated.

E:\dev.tmp\c++\mingw-win32>g++ main.cpp
E:\dev.tmp\c++\mingw-win32>

```

**Comment by lunakid** [comment] 2019-08-01 21:13
**OK, UPDATE:** the `PATH` env. var contained the path to `g++` in quotes. According to e.g. https://serverfault.com/a/349216/167625: "It seems that Windows can execute programs with "quoted" paths, but the DLL search routine can't handle them."

**Comment by nirbheek** [comment] 2019-08-02 08:00
Yeah, quotation marks and windows shell expansion don't mix very well. I'm going to close this as not a bug, thanks.

**Closed by nirbheek** 2019-08-02 08:00 UTC

**Comment by lunakid** [comment] 2019-08-02 13:30
Oh yes, but I think this one shouldn't be related to "shell expansion": in fact, the shell (`cmd`) apparently does iterate the `PATH` env. var. fine, when it contains quoted parts. It is the Win32 API, things like `CreateProcess` (and perhaps also `SearchPath`) that fail on quoted items in the list.
