### ISSUE TITLE
'\\' is getting escaped as '/' rather than '\'

### ISSUE THREAD

**Issue by nosracd** [mesonbuild/meson#8677] opened 2021-04-19 19:29 UTC
**Describe the bug**
`custom_target` and `run_target`'s `command` option does get parsed as I would expect: `\\` gets escaped as `/` rather than `\`. 

**To Reproduce**
Using this code for the `meson.build`, which writes text to two files via python:
```meson
project('Minimal Example')

python = import('python').find_installation('python3')
python_command = 'open("@0@", "w").write("test1 \\n test2")'

run_target('test_run_target.txt',
    command: [python, '-c', python_command.format('test_run_target.txt')])

custom_target('test_custom_target.txt',
    output: 'test_custom_target.txt',
    command: [python, '-c', python_command.format('test_custom_target.txt')])
```
Then to execute both targets run:
```
meson build
ninja -C build test_custom_target.txt
ninja -C build test_run_target.txt
```

**Expected behavior**
I expected the files that got created to each contain
```
test1
test2
```
but instead they each contain
```
test1 /n test2
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
This is a native build.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
This was produced on Ubuntu 20.04.
* what Python version are you using e.g. 3.8.0
Python 3.8.5
* what `meson --version`
0.57.2
* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by QuLogic** [comment] 2021-04-19 21:27
This is a duplicate of #1564.

**Comment by eli-schwartz** [comment] 2021-04-19 21:31
Duplicate of #1564

**Closed by eli-schwartz** 2021-04-19 21:31 UTC

**Comment by eli-schwartz** [comment] 2021-04-19 21:37
https://github.com/mesonbuild/meson/blob/6f76fce90436b503b841599b675155e4093d8855/mesonbuild/backend/backends.py#L1250-L1265

Thank you, GST.

Note that it's still possible to e.g.

- use `chr(10)` to emit newline, much uglier than backslash escapes but ¯\_(ツ)_/¯ 
- use a python script, not inline python

**Comment by nosracd** [comment] 2021-04-19 22:05
@eli-schwartz Sorry I missed that issue, but thanks for the feedback and the `chr(10)` advice!
